defmodule AshSurface.Projector.ExpoReceiptsTest do
  @moduledoc """
  State-based tests of `AshSurface.Projector.Expo` receipts.mjs emission.

  The MX receipt protocol invariants (envelope validation, verification-only
  export surface with no forging constructor, purity, hash verification and
  tamper refusal, client reconcile as a GET pass-through that never upgrades a
  classification) are pinned by EXECUTION in `GeneratedArtifactsExecTest` and
  `ExpoClientReconcileTest`. The envelope-line and forbidden-word text
  assertions that used to live here are superseded by those receipts.

  What remains cannot be observed by execution: the `// @generated` provenance
  header, and byte-determinism of the emission across prefix and run.
  """

  use ExUnit.Case, async: false

  alias Ash.Info.Manifest
  alias AshSurface.Fixtures.VolunteerMilestone
  alias AshSurface.Projector.Expo

  @prefix "zoela_surface"

  setup do
    assert {:ok, manifest} =
             Manifest.generate(
               otp_app: :ash_surface,
               action_entrypoints: [
                 {VolunteerMilestone, :record},
                 {VolunteerMilestone, :read}
               ]
             )

    profile = %{
      audience: :zoe_kingdom,
      actions: %{
        "AshSurface.Fixtures.VolunteerMilestone#record" => %{
          semanticId: "zoe:SelectOption",
          authorityBoundary: "SELECT",
          doAuthority: false,
          receiptRequired: true,
          evidenceRequired: true,
          possibleRefusals: ["REFUSED_NO_AUTHORITY", "REFUSED_EVIDENCE_REQUIRED"]
        }
      }
    }

    assert {:ok, surface} = AshSurface.from_manifest(manifest, profile: profile)

    assert {:ok, artifacts, _meta} = AshSurface.project(surface, Expo, prefix: @prefix)

    %{
      artifacts: artifacts,
      receipts: Map.fetch!(artifacts, "#{@prefix}.receipts.mjs"),
      surface: surface
    }
  end

  test "receipts.mjs carries the generated provenance header", %{receipts: receipts} do
    assert String.starts_with?(receipts, "// @generated by AshSurface.Projector.Expo")
  end

  describe "emission determinism" do
    test "receipts body is identical across projections and follows the requested prefix", %{
      artifacts: artifacts,
      receipts: receipts,
      surface: surface
    } do
      assert Map.has_key?(artifacts, "#{@prefix}.receipts.mjs")

      assert {:ok, other_artifacts, _meta} = AshSurface.project(surface, Expo, prefix: "mx_units")
      assert Map.has_key?(other_artifacts, "mx_units.receipts.mjs")

      # Golden stability: the receipts emission is a pure projection of the
      # protocol, byte-identical regardless of prefix or run.
      assert Map.fetch!(other_artifacts, "mx_units.receipts.mjs") == receipts
    end
  end
end
