defmodule AshSurface.Projector.ExpoSchemasTest do
  @moduledoc """
  State-based determinism contract for the `{prefix}.schemas.mjs` emission of
  `AshSurface.Projector.Expo`.

  Behaviour (zod type mapping, resource resolution, identifier sanitization,
  degradation, output boundary) is pinned by EXECUTION in
  `GeneratedArtifactsExecTest`, which imports the manufactured module under
  Node. What stays here cannot be observed by executing the module:

    * byte-determinism of the emission (same state, same bytes; prefix
      independent), and
    * the `// @generated` provenance header and the `zod` import specifier,
      which are intentional public contract.
  """

  use ExUnit.Case, async: true

  alias AshSurface.Projector.Expo

  defp surface(actions, resources) do
    AshSurface.TestSupport.VerifiedSurface.seal(%AshSurface.Surface{
      manifest: nil,
      contract: %{
        "surface" => %{"actions" => actions},
        "manifest" => %{"resources" => resources}
      },
      digest: "digest-test",
      action_ids: Enum.map(actions, & &1["id"])
    })
  end

  defp project_schemas(actions, resources \\ %{}, opts \\ [prefix: "zoela_surface"]) do
    prefix = Keyword.get(opts, :prefix, "zoela_surface")
    assert {:ok, artifacts, _meta} = AshSurface.project(surface(actions, resources), Expo, opts)
    assert is_binary(artifacts["#{prefix}.schemas.mjs"])
    artifacts["#{prefix}.schemas.mjs"]
  end

  test "identical state re-projects to byte-identical schemas.mjs" do
    actions = [%{"id" => "a.b", "resource" => "R"}, %{"id" => "c"}]

    resources = %{
      "res" => %{"name" => "R", "fields" => %{"x" => %{"type" => %{"kind" => "string"}}}}
    }

    assert project_schemas(actions, resources) == project_schemas(actions, resources)
  end

  test "schemas.mjs content is independent of the artifact prefix" do
    actions = [%{"id" => "ping"}]

    assert project_schemas(actions, %{}, prefix: "zoela_surface") ==
             project_schemas(actions, %{}, prefix: "other_prefix")
  end

  test "provenance header and the zod import specifier are the public preamble" do
    code = project_schemas([%{"id" => "ping"}])

    assert String.starts_with?(code, """
           // @generated by AshSurface.Projector.Expo (CalVer 26.9.17)
           // Do not edit directly; modify authoritative Ash resources or ontology instead.

           import { z } from "zod";
           """)
  end
end
