defmodule AshSurface.Projector.ExpoReceiptsTest do
  @moduledoc """
  State-based tests of `AshSurface.Projector.Expo` receipts.mjs emission.

  The subject is the emitted artifact state (no mocks): a real surface is built
  from the volunteer milestone fixture and projected through `AshSurface.project/3`.
  The receipts emission must satisfy three invariants of the MX consequence
  receipt protocol:

  1. Envelope fields bind AshSurface receipt semantics: the command correlation
     (`correlationId` <-> runtime `commandId`), the server receipt ref
     (`domainReceiptRef` <-> runtime `receiptRef`/event `receiptRef`), and the
     observed state digests (`pre/postStateDigest` <-> event `stateDigest`).
  2. Reconciliation primitives are pure observation: classification
     (COMPLETED / NOT_OBSERVED from the server, STILL_UNKNOWN when unobserved)
     is never produced or upgraded client-side.
  3. No receipt forging: nothing exported constructs a receipt without a
     server-issued ref; the export surface is verification-only.
  """

  use ExUnit.Case, async: false

  alias Ash.Info.Manifest
  alias AshSurface.Fixtures.VolunteerMilestone
  alias AshSurface.Projector.Expo

  @prefix "zoela_surface"

  setup do
    assert {:ok, manifest} =
             Manifest.generate(
               otp_app: :ash_surface,
               action_entrypoints: [
                 {VolunteerMilestone, :record},
                 {VolunteerMilestone, :read}
               ]
             )

    profile = %{
      audience: :zoe_kingdom,
      actions: %{
        "AshSurface.Fixtures.VolunteerMilestone#record" => %{
          semanticId: "zoe:SelectOption",
          authorityBoundary: "SELECT",
          doAuthority: false,
          receiptRequired: true,
          evidenceRequired: true,
          possibleRefusals: ["AUTHORITY_REFUSED", "EVIDENCE_REQUIRED", "UNKNOWN_AFTER_DISPATCH"]
        }
      }
    }

    assert {:ok, surface} = AshSurface.from_manifest(manifest, profile: profile)

    assert {:ok, artifacts, _meta} = AshSurface.project(surface, Expo, prefix: @prefix)

    %{
      artifacts: artifacts,
      receipts: Map.fetch!(artifacts, "#{@prefix}.receipts.mjs"),
      client: Map.fetch!(artifacts, "#{@prefix}.mjs"),
      surface: surface
    }
  end

  describe "MX receipt envelope semantics" do
    test "emits the envelope schema with commandId, receiptRef, and stateDigest bindings",
         %{receipts: receipts} do
      lines = String.split(receipts, "\n")

      # Envelope declaration and provenance header.
      assert "export const mxReceiptSchema = z.object({" in lines
      assert receipts =~ ~S|// MX Consequence Receipt Envelope & Offline Reconciliation Protocol.|
      assert receipts =~ ~S|// @generated by AshSurface.Projector.Expo|

      # commandId binding: the dispatch correlation is mandatory and non-empty.
      assert "  correlationId: z.string().min(1)," in lines

      # receiptRef binding: the server-issued domain receipt reference slot.
      assert "  domainReceiptRef: z.string().optional()," in lines

      # stateDigest binding: observed world state before and after consequence.
      assert "  preStateDigest: z.string().optional()," in lines
      assert "  postStateDigest: z.string().optional()," in lines

      # Exact subject / semantic identity of the acted-upon resource.
      assert "  exactSubject: z.string().min(1)," in lines
      assert "  actionId: z.string().min(1)," in lines
      assert "  semanticActionId: z.string().min(1)," in lines

      # Authority ladder matches the projector's boundary vocabulary.
      assert ~S|  authorityBoundary: z.enum(["OBSERVE", "SELECT", "CONSTRUCT", "DO"]),| in lines

      # Outcome vocabulary carries the standing terms, never a bare success flag.
      assert ~S|  outcome: z.enum(["COMPLETED", "REFUSED", "UNKNOWN_AFTER_DISPATCH"]),| in lines

      # Integrity: replay identity and a 64-char (sha256-class) receipt hash.
      assert "  replayKey: z.string().min(1)," in lines
      assert "  receiptHash: z.string().min(64)," in lines

      # Evidence chain defaults to empty, never to fabrication.
      assert ~S|  evidenceRefs: z.array(z.string()).default([]),| in lines
    end

    test "envelope cannot validate without transport evidence (server-observed receipt)", %{
      receipts: receipts
    } do
      # transportReceipt is required: no .optional() escape hatch exists.
      assert "  transportReceipt: z.record(z.string(), z.unknown())," in String.split(
               receipts,
               "\n"
             )

      refute receipts =~ ~S|transportReceipt: z.record(z.string(), z.unknown()).optional()|

      # The envelope is a verifier (parse/validate), closed by passthrough at the end.
      assert receipts =~ "}).passthrough();"
    end
  end

  describe "reconciliation primitives are pure observation" do
    test "canonicalStringify is a deterministic, side-effect-free digest helper", %{
      receipts: receipts
    } do
      assert receipts =~ "export function canonicalStringify(obj) {"
      assert receipts =~ "Object.keys(obj).sort()"

      # Purity: no entropy, no clock, no I/O inside the receipts emission.
      for impure <- [
            "Math.random",
            "Date.now",
            "new Date",
            "fetch(",
            "XMLHttpRequest",
            "WebSocket"
          ] do
        refute receipts =~ impure, "receipts emission must stay pure, found: #{impure}"
      end
    end

    test "client reconcile(commandId) is a GET pass-through that never upgrades classification",
         %{client: client, receipts: receipts} do
      # commandId binding on the reconciliation path.
      assert client =~ "async reconcile(commandId) {"

      # Observation only: a GET to the server-owned reconcile endpoint.
      assert client =~
               ~S|fetch(`${reconcileEndpoint}?commandId=${encodeURIComponent(commandId)}`)|

      # When the server cannot observe the command, standing stays unknown; the
      # client refuses to invent COMPLETED/NOT_OBSERVED/PENDING on its own.
      assert client =~ ~S|if (!res.ok) return { status: "STILL_UNKNOWN" };|
      assert client =~ "return await res.json();"

      refute client =~ "POST", "reconciliation must never re-dispatch (no retry, no actuation)"
      refute client =~ "PENDING", "no client-side PENDING classification may be fabricated"
      refute receipts =~ "PENDING", "classification vocabulary stays server-owned"
    end
  end

  describe "no receipt forging exports" do
    test "export surface is verification-only: no constructor without a server ref", %{
      receipts: receipts
    } do
      exports =
        Regex.scan(~r/export\s+(?:const|function)\s+([A-Za-z0-9_]+)/, receipts)
        |> Enum.map(fn [_match, name] -> name end)
        |> MapSet.new()

      assert MapSet.new(["mxReceiptSchema", "canonicalStringify"]) == exports

      # Nothing anywhere in the emission mints, builds, signs, or forges receipts.
      for forbidden <-
            ~w(buildReceipt createReceipt mintReceipt makeReceipt forgeReceipt signReceipt) do
        refute receipts =~ forbidden, "receipt forging export found: #{forbidden}"
      end

      refute receipts =~ "new Receipt"

      # The server ref and hash slots are validated fields only; they are never
      # assigned or computed client-side.
      refute receipts =~ "domainReceiptRef ="
      refute receipts =~ "receiptHash ="
    end
  end

  describe "emission determinism" do
    test "receipts body is identical across projections and follows the requested prefix", %{
      artifacts: artifacts,
      receipts: receipts,
      surface: surface
    } do
      assert Map.has_key?(artifacts, "#{@prefix}.receipts.mjs")

      assert {:ok, other_artifacts, _meta} = AshSurface.project(surface, Expo, prefix: "mx_units")
      assert Map.has_key?(other_artifacts, "mx_units.receipts.mjs")

      # Golden stability: the receipts emission is a pure projection of the
      # protocol, byte-identical regardless of prefix or run.
      assert Map.fetch!(other_artifacts, "mx_units.receipts.mjs") == receipts
    end
  end
end
