defmodule AshSurface.Projector.ExpoEventsTest do
  @moduledoc """
  State-based tests of the `events.mjs` emission from `AshSurface.Projector.Expo`.

  The events artifact is a READ-ONLY observation surface. These tests project a
  surface and assert observable properties of the emitted artifact:

  - every emitted event descriptor carries `authorityBoundary: OBSERVE`
  - sequencing / digest fields are present per the `AshSurface.Event` shape
  - the surface is subscription-only: parse/observe exports, no dispatch/mutation
  - golden fragments pin the manufactured projection shape
  """

  use ExUnit.Case, async: true

  alias AshSurface.Event
  alias AshSurface.Projector.Expo

  @prefix "zoela_surface"
  @artifact_key "#{@prefix}.events.mjs"

  setup do
    surface = %AshSurface.Surface{
      manifest: %{},
      contract: %{"surface" => %{"actions" => []}},
      digest: "test_digest",
      action_ids: []
    }

    assert {:ok, artifacts, meta} = Expo.project(surface, prefix: @prefix)
    assert meta.prefix == @prefix

    %{events: Map.fetch!(artifacts, @artifact_key)}
  end

  test "emits the events artifact alongside the rest of the projection", %{events: events} do
    assert is_binary(events)
    assert String.starts_with?(events, "// @generated by AshSurface.Projector.Expo")
  end

  describe "authority_boundary OBSERVE on every emitted event descriptor" do
    test "authorityBoundary is emitted as an OBSERVE-only literal with OBSERVE default",
         %{events: events} do
      assert events =~ ~S{authorityBoundary: z.literal("OBSERVE").default("OBSERVE")}

      refute events =~ ~s{z.enum(["OBSERVE",}

      for boundary <- ["\"SELECT\"", "\"CONSTRUCT\"", "\"DO\""] do
        refute events =~ "authorityBoundary: z.enum([" <> boundary
      end
    end

    test "OBSERVE is the only authority boundary token in the artifact", %{events: events} do
      boundaries = Regex.scan(~r/authorityBoundary[^\n]*/, events)

      assert boundaries != []

      for [line] <- boundaries do
        assert line =~ "OBSERVE"
        refute line =~ ~s{"SELECT"}
        refute line =~ ~s{"CONSTRUCT"}
        refute line =~ ~s{"DO"}
      end
    end
  end

  describe "sequencing and digest fields per the AshSurface.Event shape" do
    test "every serialized Event field is declared by the emitted schema", %{events: events} do
      serialized_keys =
        Event.create("zoe:KingdomNeed#need_42", 1, "need_selected",
          payload: %{"selected_candidate" => "person_01"},
          receipt_ref: "rcpt_b3_8f910a2"
        )
        |> Event.to_map()
        |> Map.keys()

      # payload (and future observation keys) flow through .passthrough(),
      # every sequencing/digest/identity field is declared explicitly.
      for key <- serialized_keys -- ["payload"] do
        assert events =~ "#{key}:",
               "expected emitted event descriptor to declare #{key}"
      end
    end

    test "sequencing is a nonnegative integer", %{events: events} do
      assert events =~ "sequence: z.number().int().nonnegative()"
    end

    test "state digest is a non-empty string", %{events: events} do
      assert events =~ "stateDigest: z.string().min(1)"
    end

    test "event identity is a non-empty string", %{events: events} do
      assert events =~ "eventId: z.string().min(1)"
    end

    test "occurrence timestamp is a non-empty string", %{events: events} do
      assert events =~ "occurredAt: z.string().min(1)"
    end
  end

  describe "subscription-only surface" do
    test "exports exactly the observation schema and read-only parser", %{events: events} do
      export_names =
        Regex.scan(~r/export\s+(?:const|function)\s+([A-Za-z0-9_$]+)/, events)
        |> Enum.map(fn [_, name] -> name end)

      assert Enum.sort(export_names) == ["eventProjectionSchema", "parseEvent"]
    end

    test "no dispatch or mutation identifiers are exported", %{events: events} do
      export_names =
        Regex.scan(~r/export\s+(?:const|function)\s+([A-Za-z0-9_$]+)/, events)
        |> Enum.map(fn [_, name] -> String.downcase(name) end)

      for forbidden <- [
            "dispatch",
            "mutate",
            "invoke",
            "publish",
            "emit",
            "send",
            "post",
            "apply",
            "create",
            "update",
            "delete"
          ] do
        refute forbidden in export_names,
               "events artifact must not export #{forbidden}/1"
      end
    end

    test "no transport, dispatch, or mutation call sites appear in the artifact",
         %{events: events} do
      refute events =~ "fetch("
      refute events =~ ".invoke("
      refute events =~ "dispatch("
      refute events =~ "mutate("
      refute events =~ "channel.push("
    end

    test "parsing is the only behavior the artifact performs", %{events: events} do
      assert events =~ "export function parseEvent(raw) {"
      assert events =~ "return eventProjectionSchema.parse(raw);"
    end
  end

  describe "golden fragments" do
    test "header declares generated read-only observation layer", %{events: events} do
      assert events =~
               "// @generated by AshSurface.Projector.Expo (CalVer 26.9.16)\n" <>
                 "// Read-only realtime observation and event projection layer."
    end

    test "schema shape and passthrough are pinned", %{events: events} do
      assert events =~ "export const eventProjectionSchema = z.object({"
      assert events =~ "}).passthrough();"

      assert events =~
               String.trim("""
                 eventId: z.string().min(1),
                 sequence: z.number().int().nonnegative(),
                 subjectRef: z.string().min(1),
                 eventType: z.string().min(1),
                 stateDigest: z.string().min(1),
               """)
    end

    test "optional observation references stay optional", %{events: events} do
      assert events =~ "evidenceRef: z.string().optional(),"
      assert events =~ "receiptRef: z.string().optional(),"
    end
  end
end
