defmodule AshSurface.Projector.ExpoClientTest do
  @moduledoc """
  State-based tests of the import contract of `AshSurface.Projector.Expo`'s
  client runtime factory (`{prefix}.mjs`) and TanStack adapter
  (`{prefix}.tanstack.mjs`) emissions.

  Behaviour - the factory wiring the shipped runtime with pre-bound schemas,
  the query key hierarchy, `createMutationOptions` wired to
  `invokeWithReceipt`, no post-dispatch replay - is pinned by EXECUTION in
  `GeneratedArtifactsExecTest` (and reconcile in `ExpoClientReconcileTest`).
  The golden source fragments that used to be asserted here are superseded.

  Kept because execution cannot observe them as intent: the relative import
  specifiers resolve to artifacts of the same projection, and the
  `// @generated` header carries the shipped runtime's version.
  """

  use ExUnit.Case, async: false

  alias Ash.Info.Manifest
  alias AshSurface.Fixtures.VolunteerMilestone
  alias AshSurface.Projector.Expo

  @prefix "zoela_surface"
  @client_file "#{@prefix}.mjs"
  @tanstack_file "#{@prefix}.tanstack.mjs"
  @tmp_dir Path.expand("../../../_build/test/projector_expo_client", __DIR__)

  setup do
    File.rm_rf!(@tmp_dir)
    File.mkdir_p!(@tmp_dir)

    assert {:ok, manifest} =
             Manifest.generate(
               otp_app: :ash_surface,
               action_entrypoints: [
                 {VolunteerMilestone, :record},
                 {VolunteerMilestone, :read}
               ]
             )

    profile = %{
      audience: :zoe_kingdom,
      actions: %{
        "AshSurface.Fixtures.VolunteerMilestone#record" => %{
          semanticId: "zoe:SelectOption",
          authorityBoundary: "SELECT",
          doAuthority: false,
          receiptRequired: true,
          evidenceRequired: true,
          possibleRefusals: ["REFUSED_NO_AUTHORITY", "REFUSED_EVIDENCE_REQUIRED"]
        }
      }
    }

    assert {:ok, surface} = AshSurface.from_manifest(manifest, profile: profile)

    assert {:ok, artifacts, meta} =
             AshSurface.project(surface, Expo, prefix: @prefix, target_dir: @tmp_dir)

    assert meta.prefix == @prefix
    assert meta.action_count == 2

    %{artifacts: artifacts}
  end

  describe "import contract of both emissions" do
    test "every relative import resolves to an artifact from the same projection", %{
      artifacts: artifacts
    } do
      for file <- [@client_file, @tanstack_file] do
        source = artifacts[file]

        relative_specs =
          for spec <- import_specifiers(source), String.starts_with?(spec, "./"), do: spec

        assert relative_specs != [], "expected #{file} to reference at least one sibling artifact"

        for spec <- relative_specs do
          assert Map.has_key?(artifacts, Path.basename(spec)),
                 "#{file} imports #{spec} which was not manufactured in this projection"
        end
      end
    end

    test "both artifacts carry the shipped runtime's version in their generated headers", %{
      artifacts: artifacts
    } do
      assert {:ok, runtime} = AshSurface.runtime_source()

      [version] =
        Regex.run(~r/SURFACE_RUNTIME_VERSION = "([^"]+)"/, runtime, capture: :all_but_first)

      for file <- [@client_file, @tanstack_file] do
        assert artifacts[file] =~ "// @generated by AshSurface.Projector.Expo (CalVer #{version})"
      end
    end
  end

  defp import_specifiers(source) do
    ~r/from\s+"([^"]+)"/
    |> Regex.scan(source)
    |> Enum.map(fn [_, spec] -> spec end)
  end
end
