defmodule AshSurface.Projector.IRProjectorTest.EchoSurfaceProjector do
  @moduledoc """
  Inline double for a surface-consuming projector under the single
  `AshSurface.Projector.IR` contract — the injected-collaborator seam
  TESTING.md admits for projectors.

  It is real state, not a mock: it recovers the surface with `to_surface/1`
  exactly as Expo and VoiceKiosk do, then echoes the surface and opts it
  received into its meta, so what crossed the boundary is observable as
  returned state.
  """

  @behaviour AshSurface.Projector.IR

  @impl true
  def project_ir(irs, opts \\ []) do
    with {:ok, surface} <- AshSurface.Projector.IR.to_surface(irs) do
      {:ok, %{"echo" => true, "action_ids" => surface.action_ids},
       %{surface: surface, opts: opts}}
    end
  end
end

defmodule AshSurface.Projector.IRProjectorTest.RefusingSurfaceProjector do
  @moduledoc "Double whose `project_ir/2` fails, to prove error passthrough."

  @behaviour AshSurface.Projector.IR

  @impl true
  def project_ir(_irs, _opts), do: {:error, :projector_refused}
end

defmodule AshSurface.Projector.IRProjectorTest.EchoNativeIRProjector do
  @moduledoc "Inline double implementing the IR-era `project_ir/2` callback."

  @behaviour AshSurface.Projector.IR

  @impl true
  def project_ir(irs, opts) do
    {:ok, :from_native_ir, %{irs: irs, opts: opts}}
  end
end

defmodule AshSurface.Projector.IRProjectorTest do
  @moduledoc """
  Chicago-style, state-based tests for the single projector contract
  (`AshSurface.Projector.IR`).

  The surface under projection is real: generated by `Ash.Info.Manifest` from
  the ETS-backed fixture resource, verified by `AshSurface.from_manifest/2`,
  and carried into the canonical IR shape declared by `IR`. The doubles above
  are the admitted projector seam and are themselves state-based echoes. No
  message spying, no mock frameworks.

  Invariants under test:

    * a surface-consuming projector observes the identical verified surface,
      re-extracted from the IR `ash` facts, and its artifacts, meta, and
      errors pass through `project/3` untouched;
    * anything that is not a `project_ir/2` module (wrong module, no module,
      non-module) is refused with a typed `{:unknown_projector_kind, _}` error
      at dispatch;
    * opts given to `project/3` reach the projector unchanged;
    * the canonical IR shape round-trips surface facts, and IR collections
      without exactly one complete surface IR are refused with typed errors;
      a mixed collection (one surface node beside foreign nodes) is refused
      as a whole — the foreign remainder is never silently pruned.
  """

  use ExUnit.Case, async: false

  alias Ash.Info.Manifest
  alias AshSurface.Fixtures.VolunteerMilestone
  alias AshSurface.Projector.IR

  @echo_surface AshSurface.Projector.IRProjectorTest.EchoSurfaceProjector
  @refusing AshSurface.Projector.IRProjectorTest.RefusingSurfaceProjector
  @echo_native AshSurface.Projector.IRProjectorTest.EchoNativeIRProjector

  setup do
    assert {:ok, manifest} =
             Manifest.generate(
               otp_app: :ash_surface,
               action_entrypoints: [
                 {VolunteerMilestone, :record},
                 {VolunteerMilestone, :read}
               ]
             )

    assert {:ok, surface} = AshSurface.from_manifest(manifest, profile: %{audience: :zoe_kingdom})
    assert {:ok, ir} = IR.from_surface(surface)

    %{surface: surface, ir: ir}
  end

  describe "project/3 over a surface-consuming projector" do
    test "runs the projector over IR and it observes the exact surface", %{
      surface: surface,
      ir: ir
    } do
      assert {:ok, artifacts, meta} = IR.project(@echo_surface, [ir], [])

      assert artifacts == %{"echo" => true, "action_ids" => surface.action_ids}

      # Manifest facts were re-extracted from IR.ash, never re-derived.
      assert meta.surface == surface
      assert meta.surface.manifest == surface.manifest
      assert meta.surface.contract == surface.contract
      assert meta.surface.digest == surface.digest
    end

    test "accepts a single IR node as well as a list", %{surface: surface, ir: ir} do
      assert {:ok, _artifacts, %{surface: ^surface}} = IR.project(@echo_surface, [ir], [])
      assert {:ok, _artifacts, %{surface: ^surface}} = IR.project(@echo_surface, ir, [])
    end

    test "the public facade dispatches through the same contract", %{surface: surface} do
      assert {:ok, artifacts, meta} = AshSurface.project(surface, @echo_surface, extra: 1)
      assert artifacts == %{"echo" => true, "action_ids" => surface.action_ids}
      assert meta.surface == surface
      assert meta.opts == [extra: 1]
    end

    test "passes opts through unchanged", %{ir: ir} do
      opts = [prefix: "zoela_surface", target_dir: nil, extra: {:nested, 1}]

      assert {:ok, _artifacts, meta} = IR.project(@echo_surface, [ir], opts)
      assert meta.opts == opts
    end

    test "returns the projector's error tuple unchanged", %{ir: ir} do
      assert {:error, :projector_refused} = IR.project(@refusing, [ir], [])
    end
  end

  describe "unknown projector kinds" do
    test "the removed legacy adapter surface is gone" do
      refute function_exported?(IR, :from_manifest_projector, 1)
      refute Code.ensure_loaded?(AshSurface.Projector)
      refute Code.ensure_loaded?(AshSurface.Projector.IR.ManifestProjector)
    end

    test "refuses unknown kinds at dispatch, with typed errors", %{ir: ir} do
      assert {:error, {:unknown_projector_kind, String}} = IR.project(String, [ir], [])
      assert {:error, {:unknown_projector_kind, IR}} = IR.project(IR, [ir], [])

      assert {:error, {:unknown_projector_kind, :not_a_projector}} =
               IR.project(:not_a_projector, [ir], [])

      assert {:error, {:unknown_projector_kind, %{kind: "fake"}}} =
               IR.project(%{kind: "fake"}, [ir], [])

      assert {:error, {:unknown_projector_kind, 42}} = IR.project(42, [ir], [])
    end
  end

  describe "native IR-shaped projectors" do
    test "dispatches a project_ir/2 implementer and passes irs and opts through", %{ir: ir} do
      opts = [prefix: "native"]

      assert {:ok, :from_native_ir, meta} = IR.project(@echo_native, [ir], opts)
      assert meta.irs == [ir]
      assert meta.opts == opts
    end
  end

  describe "canonical IR shape and re-extraction" do
    test "carries the verified surface facts under ash", %{surface: surface, ir: ir} do
      assert ir.kind == "ash_surface.surface"
      assert ir.ash.manifest == surface.manifest
      assert ir.ash.contract == surface.contract
      assert ir.ash.digest == surface.digest
      assert ir.ash.action_ids == surface.action_ids
    end

    test "round-trips: to_surface recovers the exact surface from IR", %{surface: surface, ir: ir} do
      assert {:ok, ^surface} = IR.to_surface([ir])
      assert {:ok, ^surface} = IR.to_surface(ir)
    end

    test "refuses IR collections without exactly one surface IR, with typed errors", %{ir: ir} do
      assert {:error, {:missing_surface_ir, 0}} = IR.to_surface([])
      assert {:error, {:missing_surface_ir, 1}} = IR.to_surface([%{kind: "foreign", ash: %{}}])
      assert {:error, {:duplicate_surface_irs, 2}} = IR.to_surface([ir, ir])
      assert {:error, {:invalid_ir, :not_even_a_map}} = IR.to_surface([:not_even_a_map])

      assert {:error, {:invalid_irs, :not_even_a_collection}} =
               IR.to_surface(:not_even_a_collection)
    end

    test "refuses a mixed collection instead of silently pruning the foreign remainder", %{
      ir: ir
    } do
      foreign = %{kind: "foreign", ash: %{}}
      other = %{kind: "other.kind", ash: %{}}

      assert {:error, {:foreign_ir, [^foreign]}} = IR.to_surface([ir, foreign])

      # Order is preserved: every foreign node is named, surface node or not.
      assert {:error, {:foreign_ir, [^foreign, ^other]}} = IR.to_surface([foreign, ir, other])
    end

    test "a surface-consuming projector refuses a mixed collection through project/3 too", %{
      ir: ir
    } do
      foreign = %{kind: "foreign", ash: %{}}

      assert {:error, {:foreign_ir, [^foreign]}} = IR.project(@echo_surface, [ir, foreign], [])
    end

    test "refuses a surface IR with incomplete ash facts, with a typed error" do
      assert {:error, {:invalid_surface_facts, []}} =
               IR.to_surface([%{kind: "ash_surface.surface", ash: %{}}])

      assert {:error, {:invalid_surface_facts, [:digest, :manifest]}} =
               IR.to_surface([
                 %{kind: "ash_surface.surface", ash: %{digest: "abc", manifest: %Manifest{}}}
               ])
    end
  end
end
