defmodule AshSurface.Projector.IRProjectorTest.EchoLegacyProjector do
  @moduledoc """
  Inline double for the OLD `AshSurface.Projector` behaviour — the one
  injected-collaborator seam TESTING.md admits for projectors.

  It is real state, not a mock: it echoes the exact surface and opts it
  received into its meta and manufactures a marker artifact, so what crossed
  the adapter is observable as returned state.
  """

  @behaviour AshSurface.Projector

  @impl true
  def project(surface, opts \\ []) do
    {:ok, %{"legacy" => true, "action_ids" => surface.action_ids},
     %{surface: surface, opts: opts}}
  end
end

defmodule AshSurface.Projector.IRProjectorTest.RefusingLegacyProjector do
  @moduledoc "Legacy double whose `project/2` fails, to prove error passthrough."

  @behaviour AshSurface.Projector

  @impl true
  def project(_surface, _opts \\ []), do: {:error, :legacy_refused}
end

defmodule AshSurface.Projector.IRProjectorTest.EchoNativeIRProjector do
  @moduledoc "Inline double implementing the IR-era `project_ir/2` callback."

  @behaviour AshSurface.Projector.IR

  @impl true
  def project_ir(irs, opts) do
    {:ok, :from_native_ir, %{irs: irs, opts: opts}}
  end
end

defmodule AshSurface.Projector.IRProjectorTest do
  @moduledoc """
  Chicago-style, state-based tests for the IR-era projector boundary
  (`AshSurface.Projector.IR`).

  The surface under projection is real: generated by `Ash.Info.Manifest` from
  the ETS-backed fixture resource, verified by `AshSurface.from_manifest/2`,
  and carried into the canonical IR shape declared by `IR`. The doubles above
  are the admitted projector seam and are themselves state-based echoes. No
  message spying, no mock frameworks.

  Invariants under test:

    * a legacy projector wrapped by `from_manifest_projector/1` runs unchanged
      over IR — it observes the identical verified surface, re-extracted from
      the IR `ash` facts, and its artifacts, meta, and errors pass through
      untouched;
    * anything that is not a legacy projector module (wrong module, no module,
      non-module) is refused with a typed `{:unknown_projector_kind, _}` error,
      at both adaptation and dispatch;
    * opts given to `project_ir` reach the wrapped projector unchanged;
    * the canonical IR shape round-trips surface facts, and IR collections
      without exactly one complete surface IR are refused with typed errors;
      a mixed collection (one surface node beside foreign nodes) is refused
      as a whole — the foreign remainder is never silently pruned.
  """

  use ExUnit.Case, async: false

  alias Ash.Info.Manifest
  alias AshSurface.Fixtures.VolunteerMilestone
  alias AshSurface.Projector.IR
  alias AshSurface.Projector.IR.ManifestProjector

  @echo_legacy AshSurface.Projector.IRProjectorTest.EchoLegacyProjector
  @refusing_legacy AshSurface.Projector.IRProjectorTest.RefusingLegacyProjector
  @echo_native AshSurface.Projector.IRProjectorTest.EchoNativeIRProjector

  setup do
    assert {:ok, manifest} =
             Manifest.generate(
               otp_app: :ash_surface,
               action_entrypoints: [
                 {VolunteerMilestone, :record},
                 {VolunteerMilestone, :read}
               ]
             )

    assert {:ok, surface} = AshSurface.from_manifest(manifest, profile: %{audience: :zoe_kingdom})
    assert {:ok, ir} = IR.from_surface(surface)

    %{surface: surface, ir: ir}
  end

  describe "from_manifest_projector/1 + project/3 over a legacy projector" do
    test "wraps a legacy AshSurface.Projector and runs it unchanged over IR", %{
      surface: surface,
      ir: ir
    } do
      assert {:ok, adapter} = IR.from_manifest_projector(@echo_legacy)
      assert adapter.projector == @echo_legacy

      assert {:ok, artifacts, meta} = IR.project(adapter, [ir], [])

      assert artifacts == %{
               "legacy" => true,
               "action_ids" => surface.action_ids
             }

      # The legacy projector observed the exact pre-IR surface: manifest facts
      # were re-extracted from IR.ash, never re-derived.
      assert meta.surface == surface
      assert meta.surface.manifest == surface.manifest
      assert meta.surface.contract == surface.contract
      assert meta.surface.digest == surface.digest
    end

    test "accepts a single IR node as well as a list", %{surface: surface, ir: ir} do
      assert {:ok, adapter} = IR.from_manifest_projector(@echo_legacy)

      assert {:ok, _artifacts, %{surface: ^surface}} = IR.project(adapter, [ir], [])
      assert {:ok, _artifacts, %{surface: ^surface}} = IR.project(adapter, ir, [])
    end

    test "passes opts through to the legacy projector unchanged", %{ir: ir} do
      opts = [prefix: "zoela_surface", target_dir: nil, extra: {:nested, 1}]

      assert {:ok, adapter} = IR.from_manifest_projector(@echo_legacy)

      assert {:ok, _artifacts, meta} = IR.project(adapter, [ir], opts)
      assert meta.opts == opts

      assert {:ok, _artifacts, meta} = ManifestProjector.project_ir(adapter, [ir], opts)
      assert meta.opts == opts
    end

    test "returns the legacy projector's error tuple unchanged", %{ir: ir} do
      assert {:error, :legacy_refused} = IR.project(adapter_for(@refusing_legacy), [ir], [])
    end
  end

  describe "unknown projector kinds" do
    test "refuses non-legacy modules and non-modules, with typed errors" do
      # A real, loaded module of the wrong kind.
      assert {:error, {:unknown_projector_kind, String}} = IR.from_manifest_projector(String)
      assert {:error, {:unknown_projector_kind, IR}} = IR.from_manifest_projector(IR)

      # Atoms that name no projector at all.
      assert {:error, {:unknown_projector_kind, :not_a_projector}} =
               IR.from_manifest_projector(:not_a_projector)

      # Non-module kinds.
      assert {:error, {:unknown_projector_kind, 42}} = IR.from_manifest_projector(42)
      assert {:error, {:unknown_projector_kind, "expo"}} = IR.from_manifest_projector("expo")
    end

    test "refuses unknown kinds at dispatch too, with typed errors", %{ir: ir} do
      assert {:error, {:unknown_projector_kind, String}} = IR.project(String, [ir], [])

      assert {:error, {:unknown_projector_kind, :not_a_projector}} =
               IR.project(:not_a_projector, [ir], [])

      assert {:error, {:unknown_projector_kind, %{kind: "fake"}}} =
               IR.project(%{kind: "fake"}, [ir], [])
    end
  end

  describe "native IR-era projectors" do
    test "dispatches a project_ir/2 implementer and passes irs and opts through", %{ir: ir} do
      opts = [prefix: "native"]

      assert {:ok, :from_native_ir, meta} = IR.project(@echo_native, [ir], opts)
      assert meta.irs == [ir]
      assert meta.opts == opts
    end
  end

  describe "canonical IR shape and re-extraction" do
    test "carries the verified surface facts under ash", %{surface: surface, ir: ir} do
      assert ir.kind == "ash_surface.surface"
      assert ir.ash.manifest == surface.manifest
      assert ir.ash.contract == surface.contract
      assert ir.ash.digest == surface.digest
      assert ir.ash.action_ids == surface.action_ids
    end

    test "round-trips: to_surface recovers the exact surface from IR", %{surface: surface, ir: ir} do
      assert {:ok, ^surface} = IR.to_surface([ir])
      assert {:ok, ^surface} = IR.to_surface(ir)
    end

    test "refuses IR collections without exactly one surface IR, with typed errors", %{ir: ir} do
      assert {:error, {:missing_surface_ir, 0}} = IR.to_surface([])
      assert {:error, {:missing_surface_ir, 1}} = IR.to_surface([%{kind: "foreign", ash: %{}}])
      assert {:error, {:duplicate_surface_irs, 2}} = IR.to_surface([ir, ir])
      assert {:error, {:invalid_ir, :not_even_a_map}} = IR.to_surface([:not_even_a_map])

      assert {:error, {:invalid_irs, :not_even_a_collection}} =
               IR.to_surface(:not_even_a_collection)
    end

    test "refuses a mixed collection instead of silently pruning the foreign remainder", %{
      ir: ir
    } do
      foreign = %{kind: "foreign", ash: %{}}
      other = %{kind: "other.kind", ash: %{}}

      assert {:error, {:foreign_ir, [^foreign]}} = IR.to_surface([ir, foreign])

      # Order is preserved: every foreign node is named, surface node or not.
      assert {:error, {:foreign_ir, [^foreign, ^other]}} = IR.to_surface([foreign, ir, other])
    end

    test "the manifest adapter refuses a mixed collection through project/3 too", %{ir: ir} do
      adapter = adapter_for(@echo_legacy)
      foreign = %{kind: "foreign", ash: %{}}

      assert {:error, {:foreign_ir, [^foreign]}} = IR.project(adapter, [ir, foreign], [])
    end

    test "refuses a surface IR with incomplete ash facts, with a typed error" do
      assert {:error, {:invalid_surface_facts, []}} =
               IR.to_surface([%{kind: "ash_surface.surface", ash: %{}}])

      assert {:error, {:invalid_surface_facts, [:digest, :manifest]}} =
               IR.to_surface([
                 %{kind: "ash_surface.surface", ash: %{digest: "abc", manifest: %Manifest{}}}
               ])
    end
  end

  defp adapter_for(projector) do
    assert {:ok, adapter} = IR.from_manifest_projector(projector)
    adapter
  end
end
