// @generated by AshSurface.Projectors.JS (CalVer 26.10.1); prefix "ash_surface_client"
// Do not edit directly; change the admitted IR sources, then re-project.
// Law: pi_JS(IR) = JavaScript + JSDoc + Zod. TypeScript-free, no build step.
// DO-boundary actions project dispatch-INTENT descriptors only: an intent
// is data and carries no execution authority; this artifact contains no
// invoke/dispatch execution path.

import { z } from "zod";

/**
 * A dispatch intent for a DO-boundary action. DATA ONLY: minting an
 * intent never executes the action. Execution requires a separately
 * admitted, brokered, receipt-bearing dispatch path.
 * @typedef {Object} DispatchIntent
 * @property {"DISPATCH_INTENT"} kind
 * @property {string} actionId
 * @property {Record<string, unknown>} input - boundary-validated by the action Zod schema when present
 */

/** Zod boundary schema for `Cart.a0` (IR.Schema.zod, verbatim). */
export const Cart_a0_schema = z.object({
  title: z.string().min(1),
  due_on: z.string().optional()
});

/** Zod boundary schema for `Cart.a1` (IR.Schema.zod, verbatim). */
export const Cart_a1_schema = z.object({
  status: z.enum(["open", "done"]).optional()
});

/** Zod boundary schema for `Cart.a2` (IR.Schema.zod, verbatim). */
export const Cart_a2_schema = z.record(z.string(), z.unknown());

/** Zod boundary schema for `Cart.a3` (IR.Schema.zod, verbatim). */
export const Cart_a3_schema = z.string().uuid().optional().nullable();

/** Zod boundary schema for `Cart.a4` (IR.Schema.zod, verbatim). */
export const Cart_a4_schema = z.number().int().min(-1.5e3).max(10,);

/** Zod boundary schema for `Cart.a5` (IR.Schema.zod, verbatim). */
export const Cart_a5_schema = z.object({"quoted key": z.boolean(), n: z.literal(null)}).passthrough();

/** Zod boundary schema for `Cart.a6` (IR.Schema.zod, verbatim). */
export const Cart_a6_schema = z.coerce.number();

/**
 * JSDoc-typed namespace for resource `Cart` (7 actions: a0, a1, a2, a3, a4, a5, a6).
 * @typedef {Object} CartNamespace
 * @property {Object} a0 - `Cart.a0` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} a1 - `Cart.a1` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} a2 - `Cart.a2` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} a3 - `Cart.a3` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} a4 - `Cart.a4` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} a5 - `Cart.a5` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} a6 - `Cart.a6` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 */
export const Cart = Object.freeze({
  /** `Cart.a0` — not delegated; no dispatch intent. */
  a0: Object.freeze({
    id: "Cart.a0",
    resource: "Cart",
    action: "a0",
    actionType: "read",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    schema: Cart_a0_schema
  }),
  /** `Cart.a1` — not delegated; no dispatch intent. */
  a1: Object.freeze({
    id: "Cart.a1",
    resource: "Cart",
    action: "a1",
    actionType: "read",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    schema: Cart_a1_schema
  }),
  /** `Cart.a2` — not delegated; no dispatch intent. */
  a2: Object.freeze({
    id: "Cart.a2",
    resource: "Cart",
    action: "a2",
    actionType: "read",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    schema: Cart_a2_schema
  }),
  /** `Cart.a3` — not delegated; no dispatch intent. */
  a3: Object.freeze({
    id: "Cart.a3",
    resource: "Cart",
    action: "a3",
    actionType: "read",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    schema: Cart_a3_schema
  }),
  /** `Cart.a4` — not delegated; no dispatch intent. */
  a4: Object.freeze({
    id: "Cart.a4",
    resource: "Cart",
    action: "a4",
    actionType: "read",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    schema: Cart_a4_schema
  }),
  /** `Cart.a5` — not delegated; no dispatch intent. */
  a5: Object.freeze({
    id: "Cart.a5",
    resource: "Cart",
    action: "a5",
    actionType: "read",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    schema: Cart_a5_schema
  }),
  /** `Cart.a6` — not delegated; no dispatch intent. */
  a6: Object.freeze({
    id: "Cart.a6",
    resource: "Cart",
    action: "a6",
    actionType: "read",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    schema: Cart_a6_schema
  })
});

/**
 * Every action descriptor, sorted by id. DO-boundary descriptors carry
 * descriptorKind "DISPATCH_INTENT"; every other descriptor is a plain
 * "DESCRIPTOR". Members are the namespace objects themselves, so
 * descriptor identity is shared.
 */
export const ACTIONS = Object.freeze([
  Cart.a0,
  Cart.a1,
  Cart.a2,
  Cart.a3,
  Cart.a4,
  Cart.a5,
  Cart.a6
]);

/** Zod boundary schemas by action id, present only where the IR delegated one. */
export const SCHEMAS = Object.freeze({
  "Cart.a0": Cart_a0_schema,
  "Cart.a1": Cart_a1_schema,
  "Cart.a2": Cart_a2_schema,
  "Cart.a3": Cart_a3_schema,
  "Cart.a4": Cart_a4_schema,
  "Cart.a5": Cart_a5_schema,
  "Cart.a6": Cart_a6_schema
});

/** Resource namespaces, sorted by resource name. */
export const NAMESPACES = Object.freeze({
  Cart
});

/** Descriptor lookup by action id; null when unknown. */
export function getAction(id) {
  return ACTIONS.find((a) => a.id === id) ?? null;
}

/**
 * Mints a dispatch INTENT for a DO-boundary action. Refused for unknown
 * actions and for any action whose delegated boundary is not exactly
 * "DO". Input is boundary-validated by the action's Zod schema when the
 * IR delegated one. Never executes anything.
 * @param {string} id
 * @param {Record<string, unknown>} input
 * @returns {DispatchIntent}
 */
export function dispatchIntent(id, input) {
  const action = getAction(id);
  if (action === null) {
    throw new Error("REFUSED_UNKNOWN_ACTION: " + id);
  }
  if (action.descriptorKind !== "DISPATCH_INTENT") {
    throw new Error("REFUSED_NOT_DO_BOUNDARY: " + id + " has descriptorKind " + action.descriptorKind);
  }
  const parsed = action.schema ? action.schema.parse(input) : input;
  return Object.freeze({ kind: "DISPATCH_INTENT", actionId: id, input: parsed });
}
