// @generated by AshSurface.Projectors.JS (CalVer 26.10.1); prefix "ash_surface_client"
// Do not edit directly; change the admitted IR sources, then re-project.
// Law: pi_JS(IR) = JavaScript + JSDoc + Zod. TypeScript-free, no build step.
// DO-boundary actions project dispatch-INTENT descriptors only: an intent
// is data and carries no execution authority; this artifact contains no
// invoke/dispatch execution path.

import { z } from "zod";

/**
 * A dispatch intent for a DO-boundary action. DATA ONLY: minting an
 * intent never executes the action. Execution requires a separately
 * admitted, brokered, receipt-bearing dispatch path.
 * @typedef {Object} DispatchIntent
 * @property {"DISPATCH_INTENT"} kind
 * @property {string} actionId
 * @property {Record<string, unknown>} input - boundary-validated by the action Zod schema when present
 */

/** Zod boundary schema for `Crate.create` (input schema of the compiled IR.Schema.zod program). */
export const Crate_create_schema = z.object({

}).passthrough();

/** Zod boundary schema for `Crate.read` (input schema of the compiled IR.Schema.zod program). */
export const Crate_read_schema = z.object({

}).passthrough();

/** Zod boundary schema for `Note.destroy` (input schema of the compiled IR.Schema.zod program). */
export const Note_destroy_schema = z.object({

}).passthrough();

/** Zod boundary schema for `Note.read` (input schema of the compiled IR.Schema.zod program). */
export const Note_read_schema = z.object({

}).passthrough();

/** Zod boundary schema for `Shelf.read` (input schema of the compiled IR.Schema.zod program). */
export const Shelf_read_schema = z.object({

}).passthrough();

/**
 * JSDoc-typed namespace for resource `Crate` (2 actions: create, read).
 * @typedef {Object} CrateNamespace
 * @property {Object} create - `Crate.create` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} read - `Crate.read` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 */
export const Crate = Object.freeze({
  /** `Crate.create` — not delegated; no dispatch intent. */
  create: Object.freeze({
    id: "Crate.create",
    resource: "Crate",
    action: "create",
    actionType: "create",
    authorityBoundary: null,
    receiptRequired: true,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: "Create",
    schema: Crate_create_schema
  }),
  /** `Crate.read` — not delegated; no dispatch intent. */
  read: Object.freeze({
    id: "Crate.read",
    resource: "Crate",
    action: "read",
    actionType: "read",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: "Read",
    schema: Crate_read_schema
  })
});

/**
 * JSDoc-typed namespace for resource `Note` (2 actions: destroy, read).
 * @typedef {Object} NoteNamespace
 * @property {Object} destroy - `Note.destroy` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} read - `Note.read` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 */
export const Note = Object.freeze({
  /** `Note.destroy` — not delegated; no dispatch intent. */
  destroy: Object.freeze({
    id: "Note.destroy",
    resource: "Note",
    action: "destroy",
    actionType: "destroy",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: "Destroy",
    schema: Note_destroy_schema
  }),
  /** `Note.read` — not delegated; no dispatch intent. */
  read: Object.freeze({
    id: "Note.read",
    resource: "Note",
    action: "read",
    actionType: "read",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: "Read",
    schema: Note_read_schema
  })
});

/**
 * JSDoc-typed namespace for resource `Shelf` (1 action: read).
 * @typedef {Object} ShelfNamespace
 * @property {Object} read - `Shelf.read` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 */
export const Shelf = Object.freeze({
  /** `Shelf.read` — not delegated; no dispatch intent. */
  read: Object.freeze({
    id: "Shelf.read",
    resource: "Shelf",
    action: "read",
    actionType: "read",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: "https://vocab.example/Shelf",
    label: "Read",
    schema: Shelf_read_schema
  })
});

/**
 * Every action descriptor, sorted by id. DO-boundary descriptors carry
 * descriptorKind "DISPATCH_INTENT"; every other descriptor is a plain
 * "DESCRIPTOR". Members are the namespace objects themselves, so
 * descriptor identity is shared.
 */
export const ACTIONS = Object.freeze([
  Crate.create,
  Crate.read,
  Note.destroy,
  Note.read,
  Shelf.read
]);

/** Zod boundary schemas by action id, present only where the IR delegated one. */
export const SCHEMAS = Object.freeze({
  "Crate.create": Crate_create_schema,
  "Crate.read": Crate_read_schema,
  "Note.destroy": Note_destroy_schema,
  "Note.read": Note_read_schema,
  "Shelf.read": Shelf_read_schema
});

/** Resource namespaces, sorted by resource name. */
export const NAMESPACES = Object.freeze({
  Crate,
  Note,
  Shelf
});

/** Descriptor lookup by action id; null when unknown. */
export function getAction(id) {
  return ACTIONS.find((a) => a.id === id) ?? null;
}

/**
 * Mints a dispatch INTENT for a DO-boundary action. Refused for unknown
 * actions and for any action whose delegated boundary is not exactly
 * "DO". Input is boundary-validated by the action's Zod schema when the
 * IR delegated one. Never executes anything.
 * @param {string} id
 * @param {Record<string, unknown>} input
 * @returns {DispatchIntent}
 */
export function dispatchIntent(id, input) {
  const action = getAction(id);
  if (action === null) {
    throw new Error("REFUSED_UNKNOWN_ACTION: " + id);
  }
  if (action.descriptorKind !== "DISPATCH_INTENT") {
    throw new Error("REFUSED_NOT_DO_BOUNDARY: " + id + " has descriptorKind " + action.descriptorKind);
  }
  const parsed = action.schema ? action.schema.parse(input) : input;
  return Object.freeze({ kind: "DISPATCH_INTENT", actionId: id, input: parsed });
}
