// @generated by AshSurface.Projector.Expo (CalVer 26.9.13)
// Explicit authority boundaries and semantic identities for machine discoverability.

export const ACTIONS = Object.freeze([
  {
    "action": "read",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": false,
    "id": "AshSurface.Fixtures.VolunteerMilestone#read",
    "possibleRefusals": [],
    "profile": {},
    "receiptRequired": null,
    "resource": "AshSurface.Fixtures.VolunteerMilestone",
    "semanticId": null
  },
  {
    "action": "record",
    "authorityBoundary": "SELECT",
    "doAuthority": false,
    "evidenceRequired": true,
    "id": "AshSurface.Fixtures.VolunteerMilestone#record",
    "possibleRefusals": [
      "AUTHORITY_REFUSED",
      "EVIDENCE_REQUIRED",
      "UNKNOWN_AFTER_DISPATCH"
    ],
    "profile": {
      "authorityBoundary": "SELECT",
      "doAuthority": false,
      "evidenceRequired": true,
      "possibleRefusals": [
        "AUTHORITY_REFUSED",
        "EVIDENCE_REQUIRED",
        "UNKNOWN_AFTER_DISPATCH"
      ],
      "receiptRequired": true,
      "semanticId": "zoe:SelectOption"
    },
    "receiptRequired": true,
    "resource": "AshSurface.Fixtures.VolunteerMilestone",
    "semanticId": "zoe:SelectOption"
  },
  {
    "action": "read",
    "authorityBoundary": null,
    "doAuthority": null,
    "evidenceRequired": false,
    "id": "AshSurface.Projector.ExpoDeterminism.WideResource#read",
    "possibleRefusals": [],
    "profile": {},
    "receiptRequired": null,
    "resource": "AshSurface.Projector.ExpoDeterminism.WideResource",
    "semanticId": null
  },
  {
    "action": "record",
    "authorityBoundary": "CONSTRUCT",
    "doAuthority": false,
    "evidenceRequired": false,
    "id": "AshSurface.Projector.ExpoDeterminism.WideResource#record",
    "possibleRefusals": [
      "AUTHORITY_REFUSED",
      "UNKNOWN_AFTER_DISPATCH"
    ],
    "profile": {
      "authorityBoundary": "CONSTRUCT",
      "doAuthority": false,
      "evidenceRequired": false,
      "possibleRefusals": [
        "AUTHORITY_REFUSED",
        "UNKNOWN_AFTER_DISPATCH"
      ],
      "receiptRequired": true,
      "semanticId": "zoe:ConstructWide",
      "wide": {
        "wide_key_29": "value_29",
        "wide_key_8": "value_8",
        "wide_key_21": "value_21",
        "wide_key_4": "value_4",
        "wide_key_13": "value_13",
        "wide_key_17": "value_17",
        "wide_key_3": "value_3",
        "wide_key_26": "value_26",
        "wide_key_6": "value_6",
        "wide_key_18": "value_18",
        "wide_key_28": "value_28",
        "wide_key_7": "value_7",
        "wide_key_23": "value_23",
        "wide_key_31": "value_31",
        "wide_key_35": "value_35",
        "wide_key_33": "value_33",
        "wide_key_22": "value_22",
        "wide_key_2": "value_2",
        "wide_key_27": "value_27",
        "wide_key_9": "value_9",
        "wide_key_14": "value_14",
        "wide_key_30": "value_30",
        "wide_key_5": "value_5",
        "wide_key_37": "value_37",
        "wide_key_15": "value_15",
        "wide_key_32": "value_32",
        "wide_key_19": "value_19",
        "wide_key_16": "value_16",
        "wide_key_38": "value_38",
        "wide_key_20": "value_20",
        "wide_key_39": "value_39",
        "wide_key_36": "value_36",
        "wide_key_11": "value_11",
        "wide_key_12": "value_12",
        "wide_key_1": "value_1",
        "wide_key_25": "value_25",
        "wide_key_10": "value_10",
        "wide_key_40": "value_40",
        "wide_key_24": "value_24",
        "wide_key_34": "value_34"
      }
    },
    "receiptRequired": true,
    "resource": "AshSurface.Projector.ExpoDeterminism.WideResource",
    "semanticId": "zoe:ConstructWide"
  }
]);

export function getAction(id) {
  return ACTIONS.find((a) => a.id === id) ?? null;
}

export function hasDoAuthority(id) {
  const action = getAction(id);
  return action ? action.doAuthority === true : false;
}

export function getAuthorityBoundary(id) {
  const action = getAction(id);
  return action ? action.authorityBoundary : "OBSERVE";
}
