// @generated by AshSurface.Projector.Expo (CalVer 26.9.13)
// Do not edit directly; modify authoritative Ash resources or ontology instead.

import { z } from "zod";

export const AshSurface_Fixtures_VolunteerMilestone_read_inputSchema = z.object({
  cost_physical: z.number().int(),
  id: z.string().uuid(),
  member_id: z.string(),
  milestone_id: z.string(),
  reward_spiritual: z.number().int(),
  status: z.string()
}).passthrough();

export const AshSurface_Fixtures_VolunteerMilestone_read_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const AshSurface_Fixtures_VolunteerMilestone_record_inputSchema = z.object({
  cost_physical: z.number().int(),
  id: z.string().uuid(),
  member_id: z.string(),
  milestone_id: z.string(),
  reward_spiritual: z.number().int(),
  status: z.string()
}).passthrough();

export const AshSurface_Fixtures_VolunteerMilestone_record_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const AshSurface_Projector_ExpoDeterminism_WideResource_read_inputSchema = z.object({
  field_36: z.string(),
  field_12: z.string(),
  field_37: z.string(),
  field_15: z.string(),
  field_22: z.string(),
  field_23: z.string(),
  field_27: z.string(),
  field_10: z.string(),
  field_7: z.string(),
  field_38: z.string(),
  field_20: z.string(),
  field_9: z.string(),
  field_26: z.string(),
  field_31: z.string(),
  field_13: z.string(),
  field_21: z.string(),
  field_17: z.string(),
  field_28: z.string(),
  field_14: z.string(),
  field_29: z.string(),
  field_25: z.string(),
  field_4: z.string(),
  field_11: z.string(),
  id: z.string().uuid(),
  field_35: z.string(),
  field_30: z.string(),
  field_16: z.string(),
  field_39: z.string(),
  field_6: z.string(),
  field_8: z.string(),
  field_19: z.string(),
  field_5: z.string(),
  field_3: z.string(),
  field_32: z.string(),
  field_18: z.string(),
  field_40: z.string(),
  field_1: z.string(),
  field_33: z.string(),
  field_34: z.string(),
  field_2: z.string(),
  field_24: z.string()
}).passthrough();

export const AshSurface_Projector_ExpoDeterminism_WideResource_read_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const AshSurface_Projector_ExpoDeterminism_WideResource_record_inputSchema = z.object({
  field_36: z.string(),
  field_12: z.string(),
  field_37: z.string(),
  field_15: z.string(),
  field_22: z.string(),
  field_23: z.string(),
  field_27: z.string(),
  field_10: z.string(),
  field_7: z.string(),
  field_38: z.string(),
  field_20: z.string(),
  field_9: z.string(),
  field_26: z.string(),
  field_31: z.string(),
  field_13: z.string(),
  field_21: z.string(),
  field_17: z.string(),
  field_28: z.string(),
  field_14: z.string(),
  field_29: z.string(),
  field_25: z.string(),
  field_4: z.string(),
  field_11: z.string(),
  id: z.string().uuid(),
  field_35: z.string(),
  field_30: z.string(),
  field_16: z.string(),
  field_39: z.string(),
  field_6: z.string(),
  field_8: z.string(),
  field_19: z.string(),
  field_5: z.string(),
  field_3: z.string(),
  field_32: z.string(),
  field_18: z.string(),
  field_40: z.string(),
  field_1: z.string(),
  field_33: z.string(),
  field_34: z.string(),
  field_2: z.string(),
  field_24: z.string()
}).passthrough();

export const AshSurface_Projector_ExpoDeterminism_WideResource_record_outputSchema = z.object({
  success: z.boolean(),
  data: z.record(z.string(), z.unknown()).optional(),
  receiptRef: z.string().optional(),
  error: z.string().optional()
}).passthrough();


export const SCHEMAS = {
  "AshSurface.Fixtures.VolunteerMilestone#read": { input: AshSurface_Fixtures_VolunteerMilestone_read_inputSchema, output: AshSurface_Fixtures_VolunteerMilestone_read_outputSchema },
  "AshSurface.Fixtures.VolunteerMilestone#record": { input: AshSurface_Fixtures_VolunteerMilestone_record_inputSchema, output: AshSurface_Fixtures_VolunteerMilestone_record_outputSchema },
  "AshSurface.Projector.ExpoDeterminism.WideResource#read": { input: AshSurface_Projector_ExpoDeterminism_WideResource_read_inputSchema, output: AshSurface_Projector_ExpoDeterminism_WideResource_read_outputSchema },
  "AshSurface.Projector.ExpoDeterminism.WideResource#record": { input: AshSurface_Projector_ExpoDeterminism_WideResource_record_inputSchema, output: AshSurface_Projector_ExpoDeterminism_WideResource_record_outputSchema }
};
