import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createClient } from "../../priv/static/ash_surface_runtime.mjs";

/**
 * Cross-language digest parity tables (chicago-digest-parity-051).
 *
 * ONE suite covering EVERY digest-bearing contract that exists on this base:
 * per contract, the JS twin recomputes each Elixir digest from the canonical
 * JSON in the fixture artifact, and the parity table is printed as part of the
 * test output (observable artifact, not an internal claim).
 *
 * Fixture subject: `test/js/fixtures/digest_cross_language_fixtures.json` —
 * byte-frozen output of the REAL Elixir pipeline, generated by
 * `AshSurface.DigestParityFixtures` (test/support) and pinned on the Elixir
 * side by `AshSurface.DigestParityFixtureTest` (on-disk bytes == fresh
 * pipeline encoding). The JS side reads exactly those committed bytes.
 *
 * Tables (fixture rows -> law under test):
 *
 *   T1 contract    — AshSurface.from_manifest/2 surface digest: the frozen
 *                    canon (canonical_term -> :erlang.term_to_binary ->
 *                    SHA-256, lower hex) over the contract map. Recomputed
 *                    from the fixture contract JSON by the ETF twin below,
 *                    and again over the runtime-held contract after the real
 *                    Zod parse (createClient).
 *   T2 event       — AshSurface.Event.create/4 state digest:
 *                    sha256("subject:sequence:type:" + canonicalJson(payload))
 *                    plus the ev_ content id derived from the first 32 hex.
 *   T3 observation — AshSurface.Observation.create/3 state digest:
 *                    sha256("subject:" + canonicalJson(facts)) plus the obs_
 *                    content id.
 *   T4 ir          — AshSurface.IR.Codec.from_map/1 digest over the
 *                    five-section staging IR (same frozen ETF canon over a
 *                    JSON-isomorphic preimage).
 *   T5 receipt     — the runtime receipt-hash law: sha256 over canonical JSON
 *                    of the receipt payload (Elixir twin:
 *                    AshSurface.CanonicalJSON.sha256_hex/1; JS twin: the
 *                    canonicalJson twin below, same law as the consumer e2e
 *                    runner's canonicalStringify).
 *
 * Canonical-JSON twin law (AshSurface.CanonicalJSON): maps encode as
 * recursively string-keyed, key-sorted (UTF-8 byte order) JSON objects; list
 * order is semantic and preserved; scalars verbatim.
 *
 * ETF twin law (the frozen canonical-term canon): maps become key-sorted
 * lists of 2-tuples; lists map element-wise; leaves pass through; encoded in
 * the Erlang external term format (BIT_BINARY 0x6d, SMALL_ATOM_UTF8 0x77 for
 * nil/true/false, SMALL_INTEGER 0x61, INTEGER 0x62, SMALL_BIG 0x6e,
 * NEW_FLOAT 0x46, NIL 0x6a, LIST 0x6c, SMALL_TUPLE 0x68).
 *
 * Sibling-note (merge-time extension): episode (036) and the full receipt
 * digest law (038) land on sibling branches; the suite grows a table per
 * integrated law — the fixture document is the single place rows are added.
 *
 * Falsifier (executed, recorded in the ticket History): diverging the JS
 * canonicalizer (key-sort disabled) turns every table RED; restoring turns
 * GREEN.
 */

const here = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = path.join(here, "fixtures", "digest_cross_language_fixtures.json");
const FIXTURES = JSON.parse(fs.readFileSync(FIXTURE_PATH, "utf8"));

/** t26 + v2 pinned digests; the v3 tables deepen, never re-pin them. */
const PRIOR_DIGESTS = new Set([
  // digest_cross_language.test.mjs (t26: F1-F3)
  "1d2f78480ad8261b83dd7182fc84aa54aa833f58fc813939a713c16d9d9f2d5f",
  "ddb95be74b2ce5b78fbe5ce8d14807d2af75426083cb0623abb587ff827cbbf1",
  "c4f7b471c2ae774ccc97d9ec64c7c9476ac291d4e88efcd3f0bfd8d94524e0b0",
  // digest_cross_language_v2.test.mjs (F4-F6)
  "f29ff4f43a88e146f61b2c9f048b385d6f6b9c9d533f2fb94a863ac5eabee7b4",
  "6bb3092a3b5aa86248cd79e67294473b007d8ef4d10b59585b3d32ea4b36b13f",
  "3ff07988feec581c25b4b8670bffa48b28b8f2d6fadcd01887f6e60a0f446469",
]);

// ---------------------------------------------------------------------------
// Canonical-JSON twin of AshSurface.CanonicalJSON.encode/1
// ---------------------------------------------------------------------------

function byUtf8Bytes(a, b) {
  return Buffer.compare(Buffer.from(a, "utf8"), Buffer.from(b, "utf8"));
}

function canonicalJson(value) {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  const keys = Object.keys(value).sort(byUtf8Bytes);
  return `{${keys.map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`;
}

function sha256Hex(bytes) {
  return crypto.createHash("sha256").update(bytes).digest("hex");
}

// ---------------------------------------------------------------------------
// ETF twin of the frozen canonical-term canon (AshSurface.digest/1,
// AshSurface.IR.Codec.digest/1)
// ---------------------------------------------------------------------------

/** Marker for map entries, which canonical_term/1 turns into 2-tuples. */
class EtfTuple {
  constructor(elements) {
    this.elements = elements;
  }
}

function canonicalTerm(value) {
  if (Array.isArray(value)) return value.map(canonicalTerm);
  if (value !== null && typeof value === "object") {
    return Object.keys(value)
      .sort(byUtf8Bytes)
      .map((key) => new EtfTuple([key, canonicalTerm(value[key])]));
  }
  return value;
}

function encodeBinary(value, chunks) {
  const bytes = Buffer.from(value, "utf8");
  const length = Buffer.alloc(4);
  length.writeUInt32BE(bytes.length);
  chunks.push(Buffer.from([0x6d]), length, bytes);
}

function encodeSmallAtomUtf8(name, chunks) {
  const bytes = Buffer.from(name, "utf8");
  if (bytes.length > 255) throw new Error(`atom too long for SMALL_ATOM_UTF8: ${name}`);
  chunks.push(Buffer.from([0x77, bytes.length]), bytes);
}

function encodeInteger(value, chunks) {
  if (value >= 0 && value <= 255) {
    chunks.push(Buffer.from([0x61, value]));
  } else if (value >= -2147483648 && value <= 2147483647) {
    const buffer = Buffer.alloc(5);
    buffer[0] = 0x62;
    buffer.writeInt32BE(value, 1);
    chunks.push(buffer);
  } else {
    const magnitude = BigInt(value < 0 ? -value : value);
    const digits = [];
    for (let mag = magnitude; mag > 0n; mag >>= 8n) digits.push(Number(mag & 0xffn));
    chunks.push(Buffer.from([0x6e, digits.length, value < 0 ? 1 : 0]), Buffer.from(digits));
  }
}

function encodeTerm(value, chunks) {
  if (value === null) return encodeSmallAtomUtf8("nil", chunks);
  if (value === true) return encodeSmallAtomUtf8("true", chunks);
  if (value === false) return encodeSmallAtomUtf8("false", chunks);
  if (typeof value === "string") return encodeBinary(value, chunks);
  if (typeof value === "number") {
    if (Number.isInteger(value) && Number.isSafeInteger(value)) return encodeInteger(value, chunks);
    const buffer = Buffer.alloc(9);
    buffer[0] = 0x46;
    buffer.writeDoubleBE(value, 1);
    chunks.push(buffer);
    return;
  }
  if (value instanceof EtfTuple) {
    chunks.push(Buffer.from([0x68, value.elements.length]));
    for (const element of value.elements) encodeTerm(element, chunks);
    return;
  }
  if (Array.isArray(value)) {
    if (value.length === 0) {
      chunks.push(Buffer.from([0x6a]));
      return;
    }
    const length = Buffer.alloc(4);
    length.writeUInt32BE(value.length);
    chunks.push(Buffer.from([0x6c]), length);
    for (const element of value) encodeTerm(element, chunks);
    chunks.push(Buffer.from([0x6a]));
    return;
  }
  throw new Error(`value is not part of the canonical term space: ${typeof value}`);
}

/** SHA-256 over the ETF encoding of the canonical term. */
function canonicalTermDigest(value) {
  const chunks = [Buffer.from([0x83])];
  encodeTerm(canonicalTerm(value), chunks);
  return sha256Hex(Buffer.concat(chunks));
}

// ---------------------------------------------------------------------------
// Table machinery
// ---------------------------------------------------------------------------

/** Reverses key insertion order at every object depth (arrays mapped through). */
function reverseKeyOrder(value) {
  if (Array.isArray(value)) return value.map(reverseKeyOrder);
  if (value !== null && typeof value === "object") {
    const reversed = {};
    for (const key of Object.keys(value).reverse()) reversed[key] = reverseKeyOrder(value[key]);
    return reversed;
  }
  return value;
}

function printParityTable(title, rows) {
  console.log(`\nparity table — ${title}`);
  console.table(
    rows.map((row) => ({
      fixture: row.fixture,
      elixir: row.elixir,
      jsRecomputed: row.js,
      parity: row.elixir === row.js ? "MATCH" : "DIVERGED",
    })),
  );
}

function assertTableParity(title, rows) {
  for (const row of rows) {
    assert.equal(
      row.js,
      row.elixir,
      `${title} / ${row.fixture}: JS twin recomputed ${row.js}, Elixir froze ${row.elixir}`,
    );
  }
  printParityTable(title, rows);
}

// ---------------------------------------------------------------------------
// The five parity tables
// ---------------------------------------------------------------------------

const TABLES = FIXTURES.tables;
const TABLE_NAMES = ["contract", "event", "observation", "ir", "receipt"];

test("fixture artifact carries all five parity tables", () => {
  assert.deepEqual(Object.keys(TABLES).sort(), TABLE_NAMES.slice().sort());
  for (const name of TABLE_NAMES) assert.ok(TABLES[name].length >= 2, `${name}: rows present`);
});

test("T1 contract: JS twin recomputes every Elixir surface digest from the contract JSON", () => {
  const rows = TABLES.contract.map((fixture) => {
    const raw = canonicalTermDigest(JSON.parse(JSON.stringify(fixture.contract)));
    const client = createClient({ contract: JSON.parse(JSON.stringify(fixture.contract)) });
    assert.equal(client.runtimeVersion, "26.9.17", `${fixture.name}: runtime version`);
    const held = canonicalTermDigest(client.contract);
    assert.equal(held, raw, `${fixture.name}: runtime-held contract digests identically`);
    return { fixture: fixture.name, elixir: fixture.elixirDigest, js: held };
  });
  assertTableParity("T1 contract (AshSurface.from_manifest/2 surface digest)", rows);
});

test("T2 event: JS twin recomputes every state digest and ev_ content id", () => {
  const rows = TABLES.event.map((fixture) => {
    const preimage = `${fixture.subjectRef}:${fixture.sequence}:${fixture.eventType}:${canonicalJson(fixture.payload)}`;
    const digest = sha256Hex(preimage);
    assert.equal(
      "ev_" + digest.slice(0, 16),
      fixture.elixirEventId,
      `${fixture.name}: event id derives from the digest (first 16 hex chars)`,
    );
    return { fixture: fixture.name, elixir: fixture.elixirStateDigest, js: digest };
  });
  assertTableParity("T2 event (AshSurface.Event.create/4 state digest)", rows);
});

test("T3 observation: JS twin recomputes every state digest and obs_ content id", () => {
  const rows = TABLES.observation.map((fixture) => {
    const preimage = `${fixture.exactSubject}:${canonicalJson(fixture.facts)}`;
    const digest = sha256Hex(preimage);
    assert.equal(
      "obs_" + digest.slice(0, 16),
      fixture.elixirObservationId,
      `${fixture.name}: observation id derives from the digest (first 16 hex chars)`,
    );
    return { fixture: fixture.name, elixir: fixture.elixirStateDigest, js: digest };
  });
  assertTableParity("T3 observation (AshSurface.Observation.create/3 state digest)", rows);
});

test("T4 ir: JS twin recomputes every staging-IR digest over the five-section map", () => {
  const rows = TABLES.ir.map((fixture) => ({
    fixture: fixture.name,
    elixir: fixture.elixirDigest,
    js: canonicalTermDigest(fixture.sections),
  }));
  assertTableParity("T4 ir (AshSurface.IR.Codec.from_map/1 staging digest)", rows);
});

test("T5 receipt: JS twin re-derives every receipt hash from the canonical payload", () => {
  const rows = TABLES.receipt.map((fixture) => ({
    fixture: fixture.name,
    elixir: fixture.elixirReceiptHash,
    js: sha256Hex(canonicalJson(fixture.payload)),
  }));
  assertTableParity("T5 receipt (runtime receipt-hash law, CanonicalJSON twin)", rows);
});

// ---------------------------------------------------------------------------
// Cross-table laws
// ---------------------------------------------------------------------------

test("every golden is 64-hex lowercase, none re-pins a t26/v2 digest, rows distinct except twins", () => {
  const digestKey = {
    contract: "elixirDigest",
    event: "elixirStateDigest",
    observation: "elixirStateDigest",
    ir: "elixirDigest",
    receipt: "elixirReceiptHash",
  };

  for (const name of TABLE_NAMES) {
    const rows = TABLES[name];
    const twins = name !== "contract" && name !== "ir"; // rows [0] and [1] are order twins
    const seen = new Map();

    for (const [index, row] of rows.entries()) {
      const digest = row[digestKey[name]];
      assert.match(digest, /^[0-9a-f]{64}$/, `${name}/${row.name}`);
      assert.equal(
        PRIOR_DIGESTS.has(digest),
        false,
        `${name}/${row.name}: re-pins a prior suite`,
      );
      const firstIndex = seen.get(digest);
      const twinPair = twins && index === 1 && firstIndex === 0;
      assert.ok(
        firstIndex === undefined || twinPair,
        `${name}/${row.name}: unexpected digest duplicate of row ${firstIndex}`,
      );
      seen.set(digest, index);
    }
  }
});

test("order-twin rows agree: canonical sort erases insertion order in every table", () => {
  assert.equal(TABLES.event[0].elixirStateDigest, TABLES.event[1].elixirStateDigest);
  assert.equal(TABLES.observation[0].elixirStateDigest, TABLES.observation[1].elixirStateDigest);
  assert.equal(TABLES.receipt[0].elixirReceiptHash, TABLES.receipt[1].elixirReceiptHash);
});

test("deep key-order permutation never moves any digest in any table", () => {
  for (const fixture of TABLES.contract) {
    const client = createClient({ contract: reverseKeyOrder(JSON.parse(JSON.stringify(fixture.contract))) });
    assert.equal(canonicalTermDigest(client.contract), fixture.elixirDigest, fixture.name);
  }
  for (const fixture of TABLES.event) {
    const subject = fixture.subjectRef;
    const preimage = `${subject}:${fixture.sequence}:${fixture.eventType}:${canonicalJson(reverseKeyOrder(fixture.payload))}`;
    assert.equal(sha256Hex(preimage), fixture.elixirStateDigest, fixture.name);
  }
  for (const fixture of TABLES.observation) {
    const preimage = `${fixture.exactSubject}:${canonicalJson(reverseKeyOrder(fixture.facts))}`;
    assert.equal(sha256Hex(preimage), fixture.elixirStateDigest, fixture.name);
  }
  for (const fixture of TABLES.ir) {
    assert.equal(canonicalTermDigest(reverseKeyOrder(fixture.sections)), fixture.elixirDigest, fixture.name);
  }
  for (const fixture of TABLES.receipt) {
    assert.equal(sha256Hex(canonicalJson(reverseKeyOrder(fixture.payload))), fixture.elixirReceiptHash, fixture.name);
  }
});

test("sensitivity: any single content mutation flips the digest in every table", () => {
  // T1 contract
  const mutatedContract = JSON.parse(JSON.stringify(TABLES.contract[0].contract));
  mutatedContract.surface.profile.glyphs[0] = "αα";
  assert.notEqual(canonicalTermDigest(mutatedContract), TABLES.contract[0].elixirDigest);

  // T2 event
  const mutatedPayload = reverseKeyOrder(TABLES.event[0].payload);
  mutatedPayload.string = "héllo ✗";
  assert.notEqual(
    sha256Hex(`${TABLES.event[0].subjectRef}:${TABLES.event[0].sequence}:${TABLES.event[0].eventType}:${canonicalJson(mutatedPayload)}`),
    TABLES.event[0].elixirStateDigest,
  );

  // T3 observation
  const mutatedFacts = reverseKeyOrder(TABLES.observation[0].facts);
  mutatedFacts.score = 0.25;
  assert.notEqual(
    sha256Hex(`${TABLES.observation[0].exactSubject}:${canonicalJson(mutatedFacts)}`),
    TABLES.observation[0].elixirStateDigest,
  );

  // T4 ir
  const mutatedSections = reverseKeyOrder(TABLES.ir[2].sections);
  mutatedSections.actions["Σ🜂#capability"].glyph = "Σ🜂✗";
  assert.notEqual(canonicalTermDigest(mutatedSections), TABLES.ir[2].elixirDigest);

  // T5 receipt
  const mutatedReceipt = reverseKeyOrder(TABLES.receipt[0].payload);
  mutatedReceipt.dispatchState = "unknown_after_dispatch";
  assert.notEqual(sha256Hex(canonicalJson(mutatedReceipt)), TABLES.receipt[0].elixirReceiptHash);
});
