import test from "node:test";
import assert from "node:assert/strict";
import { after } from "node:test";
import { createHash } from "node:crypto";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

// ---------------------------------------------------------------------------
// ir_projector_deep — DEPTH over v18's artifact validation.
//
// v18's ir_projection.test.mjs proves the manufactured bridge (artifact +
// sidecar re-manufactured by a targeted mix run). This suite deepens the
// ARTIFACT side of that contract against a FROZEN fixture, because the
// projector (AshSurface.Projectors.JS.project_ir/2) lives on the parallel
// branch exp/v18 (7d8e705) and is not present on this branch. The frozen
// bytes below are that projector's byte-deterministic output over v18's own
// fixture IR (four entries, two resources), manufactured once:
//
//   sha256 956a5012d03504f16b697ac3e6ae4509ed6e4b12d9f449e57c6e57c558e64efc
//
// Everything is declared LOCALLY here (artifact bytes, normalized IR truth,
// sample inputs) — no bridge, no shared fixtures, no duplication of the
// shallow suite's projector-side determinism claims. Scope is strictly the
// artifact contract:
//
//   one .mjs exporting JSDoc-typed namespaces, ACTIONS/SCHEMAS/NAMESPACES,
//   Zod schemas embedded verbatim from IR.Schema.zod, getAction, and
//   dispatchIntent with DO-boundary-only refusals — intents are data, never
//   execution.
// ---------------------------------------------------------------------------

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const ARTIFACT_DIR = path.join(REPO_ROOT, "tmp", "js_projector_deep");
const ARTIFACT_FILENAME = "ash_surface_client.mjs";
const FROZEN_SHA256 = "956a5012d03504f16b697ac3e6ae4509ed6e4b12d9f449e57c6e57c558e64efc";

const ARTIFACT_SOURCE = `// @generated by AshSurface.Projectors.JS (CalVer 26.9.17); prefix "ash_surface_client"
// Do not edit directly; change the admitted IR sources, then re-project.
// Law: pi_JS(IR) = JavaScript + JSDoc + Zod. TypeScript-free, no build step.
// DO-boundary actions project dispatch-INTENT descriptors only: an intent
// is data and carries no execution authority; this artifact contains no
// invoke/dispatch execution path.

import { z } from "zod";

/**
 * A dispatch intent for a DO-boundary action. DATA ONLY: minting an
 * intent never executes the action. Execution requires a separately
 * admitted, brokered, receipt-bearing dispatch path.
 * @typedef {Object} DispatchIntent
 * @property {"DISPATCH_INTENT"} kind
 * @property {string} actionId
 * @property {Record<string, unknown>} input - boundary-validated by the action Zod schema when present
 */

/** Zod boundary schema for \`Todo.create\` (IR.Schema.zod, verbatim). */
export const Todo_create_schema = z.object({
  title: z.string().min(1),
  due_on: z.string().optional()
});

/** Zod boundary schema for \`Todo.list\` (IR.Schema.zod, verbatim). */
export const Todo_list_schema = z.object({
  status: z.enum(["open", "done"]).optional()
});

/**
 * JSDoc-typed namespace for resource \`Member\` (2 actions: deactivate, profile).
 * @typedef {Object} MemberNamespace
 * @property {Object} deactivate - \`Member.deactivate\` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} profile - \`Member.profile\` (authorityBoundary: "CONSTRUCT", descriptorKind: "DESCRIPTOR")
 */
export const Member = Object.freeze({
  /** \`Member.deactivate\` — not delegated; no dispatch intent. */
  deactivate: Object.freeze({
    id: "Member.deactivate",
    resource: "Member",
    action: "deactivate",
    actionType: "destroy",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    schema: null
  }),
  /** \`Member.profile\` — "CONSTRUCT"; no dispatch intent. */
  profile: Object.freeze({
    id: "Member.profile",
    resource: "Member",
    action: "profile",
    actionType: "read",
    authorityBoundary: "CONSTRUCT",
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: "Member profile",
    schema: null
  })
});

/**
 * JSDoc-typed namespace for resource \`Todo\` (2 actions: create, list).
 * @typedef {Object} TodoNamespace
 * @property {Object} create - \`Todo.create\` (authorityBoundary: "DO", descriptorKind: "DISPATCH_INTENT")
 * @property {Object} list - \`Todo.list\` (authorityBoundary: "OBSERVE", descriptorKind: "DESCRIPTOR")
 */
export const Todo = Object.freeze({
  /** \`Todo.create\` — "DO"; dispatch-intent only. */
  create: Object.freeze({
    id: "Todo.create",
    resource: "Todo",
    action: "create",
    actionType: "create",
    authorityBoundary: "DO",
    receiptRequired: true,
    descriptorKind: "DISPATCH_INTENT",
    capabilityIri: "cap:todo.write",
    label: "Create todo",
    schema: Todo_create_schema
  }),
  /** \`Todo.list\` — "OBSERVE"; no dispatch intent. */
  list: Object.freeze({
    id: "Todo.list",
    resource: "Todo",
    action: "list",
    actionType: "read",
    authorityBoundary: "OBSERVE",
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    schema: Todo_list_schema
  })
});

/**
 * Every action descriptor, sorted by id. DO-boundary descriptors carry
 * descriptorKind "DISPATCH_INTENT"; every other descriptor is a plain
 * "DESCRIPTOR". Members are the namespace objects themselves, so
 * descriptor identity is shared.
 */
export const ACTIONS = Object.freeze([
  Member.deactivate,
  Member.profile,
  Todo.create,
  Todo.list
]);

/** Zod boundary schemas by action id, present only where the IR delegated one. */
export const SCHEMAS = Object.freeze({
  "Todo.create": Todo_create_schema,
  "Todo.list": Todo_list_schema
});

/** Resource namespaces, sorted by resource name. */
export const NAMESPACES = Object.freeze({
  Member,
  Todo
});

/** Descriptor lookup by action id; null when unknown. */
export function getAction(id) {
  return ACTIONS.find((a) => a.id === id) ?? null;
}

/**
 * Mints a dispatch INTENT for a DO-boundary action. Refused for unknown
 * actions and for any action whose delegated boundary is not exactly
 * "DO". Input is boundary-validated by the action's Zod schema when the
 * IR delegated one. Never executes anything.
 * @param {string} id
 * @param {Record<string, unknown>} input
 * @returns {DispatchIntent}
 */
export function dispatchIntent(id, input) {
  const action = getAction(id);
  if (action === null) {
    throw new Error("REFUSED_UNKNOWN_ACTION: " + id);
  }
  if (action.descriptorKind !== "DISPATCH_INTENT") {
    throw new Error("REFUSED_NOT_DO_BOUNDARY: " + id + " has descriptorKind " + action.descriptorKind);
  }
  const parsed = action.schema ? action.schema.parse(input) : input;
  return Object.freeze({ kind: "DISPATCH_INTENT", actionId: id, input: parsed });
}
`;

// Frozen IR truth: the normalized AshSurface.Projector.IR entries v18's
// fixture projects from (delegated facts read verbatim; nil when no source
// delegated — never inferred).
const IR_ACTIONS = [
  {
    id: "Member.deactivate",
    resource: "Member",
    action: "deactivate",
    actionType: "destroy",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    zod: null,
  },
  {
    id: "Member.profile",
    resource: "Member",
    action: "profile",
    actionType: "read",
    authorityBoundary: "CONSTRUCT",
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: "Member profile",
    zod: null,
  },
  {
    id: "Todo.create",
    resource: "Todo",
    action: "create",
    actionType: "create",
    authorityBoundary: "DO",
    receiptRequired: true,
    descriptorKind: "DISPATCH_INTENT",
    capabilityIri: "cap:todo.write",
    label: "Create todo",
    zod: 'z.object({\n  title: z.string().min(1),\n  due_on: z.string().optional()\n})',
  },
  {
    id: "Todo.list",
    resource: "Todo",
    action: "list",
    actionType: "read",
    authorityBoundary: "OBSERVE",
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    zod: 'z.object({\n  status: z.enum(["open", "done"]).optional()\n})',
  },
];

// Boundary samples the delegated Zod schemas must accept / reject. These are
// derived from what the IR schema strings describe, not from the artifact.
const SAMPLES = {
  "Todo.create": {
    valid: { title: "ship the projection", due_on: "2026-09-16" },
    invalid: { title: "" },
    structuralInvalid: [{}, { title: 42 }, { due_on: 9 }],
  },
  "Todo.list": {
    valid: {},
    validValued: { status: "done" },
    invalid: { status: "bogus" },
    structuralInvalid: [{ status: 7 }],
  },
};

// --- fixture integrity, then materialize + import --------------------------

const digest = createHash("sha256").update(ARTIFACT_SOURCE).digest("hex");
assert.equal(
  digest,
  FROZEN_SHA256,
  "frozen fixture drifted: regenerate from the v18 projector before editing"
);

mkdirSync(ARTIFACT_DIR, { recursive: true });
const artifactPath = path.join(ARTIFACT_DIR, ARTIFACT_FILENAME);
writeFileSync(artifactPath, ARTIFACT_SOURCE);
after(() => rmSync(ARTIFACT_DIR, { recursive: true, force: true }));

// Importing the artifact IS the parse proof: any syntax error fails here.
const artifact = await import(pathToFileURL(artifactPath).href);
const { ACTIONS, SCHEMAS, NAMESPACES, getAction, dispatchIntent } = artifact;

const doActions = IR_ACTIONS.filter((a) => a.descriptorKind === "DISPATCH_INTENT");
const nonDoActions = IR_ACTIONS.filter((a) => a.descriptorKind !== "DISPATCH_INTENT");
const withZod = IR_ACTIONS.filter((a) => a.zod !== null);
const withoutZod = IR_ACTIONS.filter((a) => a.zod === null);
const resources = [...new Set(IR_ACTIONS.map((a) => a.resource))].sort();
const DATA_FIELDS = [
  "action",
  "actionType",
  "authorityBoundary",
  "capabilityIri",
  "descriptorKind",
  "id",
  "label",
  "receiptRequired",
  "resource",
  "schema",
];

// --- helpers ---------------------------------------------------------------

function exportDeclarations(source) {
  const decls = [];
  const re = /^export\s+(?:const|function)\s+([A-Za-z_$][\w$]*)/gm;
  for (let m = re.exec(source); m !== null; m = re.exec(source)) {
    decls.push({ name: m[1], index: m.index });
  }
  return decls;
}

function precedingJsdoc(source, index) {
  return /\*\/\s*$/.test(source.slice(0, index));
}

// Returns the JSDoc block adjoining an anchor: the nearest "/**" at or
// before the anchor, closed by the "*/" that ends that same block.
function jsdocBlock(source, anchor) {
  const at = source.indexOf(anchor);
  if (at === -1) return "";
  const start = source.lastIndexOf("/**", at);
  if (start === -1) return "";
  const end = source.indexOf("*/", start);
  return end !== -1 ? source.slice(start, end) : "";
}

// --- fixture integrity -------------------------------------------------------

test("frozen artifact is byte-intact under its recorded digest", () => {
  assert.equal(
    createHash("sha256").update(ARTIFACT_SOURCE).digest("hex"),
    FROZEN_SHA256
  );
});

// --- export surface ----------------------------------------------------------

test("artifact exports exactly the contract surface, nothing else", () => {
  assert.deepEqual(Object.keys(artifact).sort(), [
    "ACTIONS",
    "Member",
    "NAMESPACES",
    "SCHEMAS",
    "Todo",
    "Todo_create_schema",
    "Todo_list_schema",
    "dispatchIntent",
    "getAction",
  ]);
});

test("sole dependency is the static zod import; no other module loading", () => {
  const imports = ARTIFACT_SOURCE.match(/(^|\n)\s*import\b[^;]*;/g) ?? [];
  assert.equal(imports.length, 1);
  assert.match(imports[0], /import\s*\{\s*z\s*\}\s*from\s*"zod"\s*;/);
  // No dynamic import/require anywhere: the artifact cannot load code at runtime.
  assert.doesNotMatch(ARTIFACT_SOURCE, /\bimport\s*\(/);
  assert.doesNotMatch(ARTIFACT_SOURCE, /\brequire\s*\(/);
});

// --- JSDoc types on every export ---------------------------------------------

test("every export declaration is immediately preceded by a JSDoc block", () => {
  const decls = exportDeclarations(ARTIFACT_SOURCE);
  assert.equal(decls.length, 9, "expected the nine contract exports");
  for (const decl of decls) {
    assert.ok(
      precedingJsdoc(ARTIFACT_SOURCE, decl.index),
      `export ${decl.name} must carry a JSDoc type block`
    );
  }
});

test("namespace typedefs type every member action, exactly once each", () => {
  for (const resource of resources) {
    const block = jsdocBlock(ARTIFACT_SOURCE, `export const ${resource} = Object.freeze({`);
    assert.match(block, new RegExp(`@typedef \\{Object\\} ${resource}Namespace`));

    const members = IR_ACTIONS.filter((a) => a.resource === resource).map((a) => a.action);
    for (const action of members) {
      const props = block.match(new RegExp(`@property \\{Object\\} ${action}\\b`, "g")) ?? [];
      assert.equal(props.length, 1, `${resource}.${action} documented exactly once`);
    }
    // No phantom members: every @property names a real IR action.
    const documented = [...block.matchAll(/@property \{Object\} (\w+)\b/g)].map((m) => m[1]);
    assert.deepEqual(documented.sort(), [...members].sort());
  }
});

test("dispatchIntent is JSDoc-typed against the DispatchIntent typedef", () => {
  const typedef = jsdocBlock(ARTIFACT_SOURCE, "@typedef {Object} DispatchIntent");
  for (const prop of ["kind", "actionId", "input"]) {
    assert.match(typedef, new RegExp(`@property .+\\b${prop}\\b`));
  }

  const doc = jsdocBlock(ARTIFACT_SOURCE, "export function dispatchIntent");
  assert.match(doc, /@param \{string\} id\b/);
  assert.match(doc, /@param \{Record<string, unknown>\} input\b/);
  assert.match(doc, /@returns \{DispatchIntent\}/);
});

test("getAction carries its lookup contract in JSDoc", () => {
  const doc = jsdocBlock(ARTIFACT_SOURCE, "export function getAction");
  assert.match(doc, /Descriptor lookup by action id/);
});

// --- Zod exports parse what the IR schemas describe ---------------------------

test("SCHEMAS keys are exactly the actions whose IR delegated a zod string", () => {
  assert.deepEqual(
    Object.keys(SCHEMAS).sort(),
    withZod.map((a) => a.id).sort()
  );
  for (const truth of withoutZod) {
    assert.ok(!(truth.id in SCHEMAS), `${truth.id} delegated no schema`);
  }
});

test("descriptor.schema is the registry schema itself, or null when undelegated", () => {
  for (const truth of withZod) {
    assert.equal(getAction(truth.id).schema, SCHEMAS[truth.id], `${truth.id} schema identity`);
  }
  for (const truth of withoutZod) {
    assert.equal(getAction(truth.id).schema, null, `${truth.id} must not invent a schema`);
  }
});

test("positive: schema-bearing actions parse the inputs the IR schema describes", () => {
  for (const truth of withZod) {
    const parsed = SCHEMAS[truth.id].parse(SAMPLES[truth.id].valid);
    assert.deepEqual(parsed, SAMPLES[truth.id].valid, `${truth.id} valid input parses`);
  }
  const valued = SCHEMAS["Todo.list"].parse(SAMPLES["Todo.list"].validValued);
  assert.deepEqual(valued, { status: "done" }, "Todo.list admits an enum value");
});

test("negative: sample, structural, and unknown-enum inputs surface ZodError", () => {
  for (const truth of withZod) {
    assert.throws(
      () => SCHEMAS[truth.id].parse(SAMPLES[truth.id].invalid),
      { name: "ZodError" },
      `${truth.id} delegated-sample rejection`
    );
    for (const bad of SAMPLES[truth.id].structuralInvalid) {
      assert.throws(
        () => SCHEMAS[truth.id].parse(bad),
        { name: "ZodError" },
        `${truth.id} must reject ${JSON.stringify(bad)}`
      );
    }
  }
});

// --- DO-boundary law: intent constructor only, never invoke -------------------

test("capability-gated DO actions are exactly the IR's DO facts, with capability evidence", () => {
  assert.equal(doActions.length, 1);
  for (const truth of doActions) {
    const descriptor = getAction(truth.id);
    assert.equal(descriptor.authorityBoundary, "DO");
    assert.equal(descriptor.descriptorKind, "DISPATCH_INTENT");
    // Capability gating is carried, not self-granted: an IRI + receipt demand.
    assert.equal(typeof descriptor.capabilityIri, "string");
    assert.ok(descriptor.capabilityIri.length > 0, "DO actions carry a capability IRI");
    assert.equal(descriptor.receiptRequired, true, "DO actions demand receipts");
  }
});

test("dispatchIntent and getAction are the ONLY exported functions; no invoke export", () => {
  const fns = Object.keys(artifact).filter((k) => typeof artifact[k] === "function").sort();
  assert.deepEqual(fns, ["dispatchIntent", "getAction"]);
  for (const forbidden of ["invoke", "dispatch", "execute", "fetch", "send", "call"]) {
    assert.ok(!(forbidden in artifact), `no ${forbidden} export`);
  }
});

test("every descriptor member is inert data: no function-valued members anywhere", () => {
  for (const descriptor of ACTIONS) {
    assert.deepEqual(Object.keys(descriptor).sort(), DATA_FIELDS);
    for (const [key, value] of Object.entries(descriptor)) {
      assert.ok(
        typeof value !== "function",
        `${descriptor.id}.${key} must be data, not a callable`
      );
    }
  }
});

test("artifact source contains no execution path (invoke/fetch/await/transport)", () => {
  for (const pattern of [
    /\binvoke\s*\(/,
    /\bfetch\s*\(/,
    /\bawait\b/,
    /XMLHttpRequest/,
    /WebSocket/,
    /\.send\s*\(/,
    /\.then\s*\(/,
  ]) {
    assert.doesNotMatch(ARTIFACT_SOURCE, pattern);
  }
});

test("dispatchIntent mints frozen data validated through the action's own schema", () => {
  const [doAction] = doActions;
  const intent = dispatchIntent(doAction.id, SAMPLES[doAction.id].valid);

  assert.deepEqual(Object.keys(intent).sort(), ["actionId", "input", "kind"]);
  assert.equal(intent.kind, "DISPATCH_INTENT");
  assert.equal(intent.actionId, doAction.id);
  assert.deepEqual(intent.input, SCHEMAS[doAction.id].parse(SAMPLES[doAction.id].valid));
  assert.ok(Object.isFrozen(intent), "an intent is frozen data");

  const second = dispatchIntent(doAction.id, SAMPLES[doAction.id].valid);
  assert.notEqual(second, intent, "each mint is fresh data, not a cached authority token");
});

test("invalid input is refused by ZodError at the intent mint boundary", () => {
  const [doAction] = doActions;
  assert.throws(
    () => dispatchIntent(doAction.id, SAMPLES[doAction.id].invalid),
    { name: "ZodError" }
  );
  for (const bad of SAMPLES[doAction.id].structuralInvalid) {
    assert.throws(() => dispatchIntent(doAction.id, bad), { name: "ZodError" });
  }
});

test("non-DO and unknown actions are refused with typed, informative errors", () => {
  for (const truth of nonDoActions) {
    assert.throws(
      () => dispatchIntent(truth.id, {}),
      (err) =>
        err instanceof Error &&
        err.message.startsWith("REFUSED_NOT_DO_BOUNDARY: " + truth.id) &&
        err.message.includes(truth.descriptorKind)
    );
  }
  assert.throws(() => dispatchIntent("Nope.missing", {}), /REFUSED_UNKNOWN_ACTION: Nope\.missing/);
  assert.throws(() => dispatchIntent("Todo.nope", {}), /REFUSED_UNKNOWN_ACTION: Todo\.nope/);
});

// --- namespace tree matches the IR action set exactly -------------------------

test("NAMESPACES keys are exactly the IR resources", () => {
  assert.deepEqual(Object.keys(NAMESPACES), resources);
  assert.ok(Object.isFrozen(NAMESPACES));
});

test("each namespace's members are exactly that resource's IR actions", () => {
  for (const resource of resources) {
    const expected = IR_ACTIONS.filter((a) => a.resource === resource).map((a) => a.action).sort();
    assert.deepEqual(
      Object.keys(NAMESPACES[resource]).sort(),
      expected,
      `${resource} namespace tree is exact`
    );
    assert.ok(Object.isFrozen(NAMESPACES[resource]));
  }
});

test("ACTIONS is the id-sorted IR action set, sharing identity with namespaces", () => {
  assert.deepEqual(ACTIONS.map((a) => a.id), IR_ACTIONS.map((a) => a.id).sort());
  for (const truth of IR_ACTIONS) {
    assert.equal(NAMESPACES[truth.resource][truth.action], getAction(truth.id));
  }
});

test("descriptors restate every normalized IR fact", () => {
  for (const truth of IR_ACTIONS) {
    const d = getAction(truth.id);
    assert.equal(d.id, truth.id);
    assert.equal(d.resource, truth.resource);
    assert.equal(d.action, truth.action);
    assert.equal(d.actionType, truth.actionType);
    assert.equal(d.authorityBoundary, truth.authorityBoundary);
    assert.equal(d.receiptRequired, truth.receiptRequired);
    assert.equal(d.descriptorKind, truth.descriptorKind);
    assert.equal(d.capabilityIri, truth.capabilityIri);
    assert.equal(d.label, truth.label);
    assert.ok(Object.isFrozen(d));
  }
});

test("getAction resolves only the IR action set; everything else is null", () => {
  for (const truth of IR_ACTIONS) {
    assert.notEqual(getAction(truth.id), null);
  }
  assert.equal(getAction("Todo.nope"), null, "known resource, unknown action");
  assert.equal(getAction("Nope.missing"), null, "unknown resource");
  assert.equal(getAction(""), null);
});

test("frozen surfaces refuse mutation at runtime (strict-mode TypeError)", () => {
  const [doAction] = doActions;
  const descriptor = getAction(doAction.id);
  assert.throws(() => {
    descriptor.label = "forged";
  }, TypeError);
  assert.throws(() => {
    ACTIONS.push(descriptor);
  }, TypeError);
  assert.throws(() => {
    NAMESPACES.Todo.invoke = () => {};
  }, TypeError);
  assert.throws(() => {
    const intent = dispatchIntent(doAction.id, SAMPLES[doAction.id].valid);
    intent.input = {};
  }, TypeError);
});
