defmodule AshSurface.Projector.Expo do
  @moduledoc """
  Projector for React Native / Expo applications (ZOELA consumer substrate).

  Manufactures:
  - `{prefix}.schemas.mjs`: Pre-compiled Zod input & output boundary schemas
  - `{prefix}.actions.mjs`: Machine-discoverable MX action descriptors with explicit authority boundaries
  - `{prefix}.events.mjs`: Read-only realtime observation & event projections
  - `{prefix}.receipts.mjs`: MX receipt envelope and reconciliation primitives
  - `{prefix}.human.mjs`: DfCM member-facing TODAY/BIBLE/LIFE/ZOE/YOU projection helpers
  - `{prefix}.mjs`: Executable client runtime factory pre-bound with manufactured schemas
  """

  @behaviour AshSurface.Projector

  @impl true
  def project(%AshSurface.Surface{} = surface, opts \\ []) do
    prefix = Keyword.get(opts, :prefix, "zoela_surface")
    target_dir = Keyword.get(opts, :target_dir)

    actions = get_in(surface.contract, ["surface", "actions"]) || []
    resources = get_in(surface.contract, ["manifest", "resources"]) || %{}

    schemas_code = render_schemas(actions, resources)
    actions_code = render_actions(actions)
    events_code = render_events()
    receipts_code = render_receipts()
    human_code = render_human()
    demo_code = render_demo(prefix)
    client_code = render_client(prefix)
    tanstack_code = render_tanstack(actions, prefix)

    artifacts = %{
      "#{prefix}.schemas.mjs" => schemas_code,
      "#{prefix}.actions.mjs" => actions_code,
      "#{prefix}.events.mjs" => events_code,
      "#{prefix}.receipts.mjs" => receipts_code,
      "#{prefix}.human.mjs" => human_code,
      "#{prefix}.demo.mjs" => demo_code,
      "#{prefix}.mjs" => client_code,
      "#{prefix}.tanstack.mjs" => tanstack_code
    }

    if target_dir do
      File.mkdir_p!(target_dir)

      Enum.each(artifacts, fn {filename, content} ->
        File.write!(Path.join(target_dir, filename), content)
      end)
    end

    {:ok, artifacts, %{prefix: prefix, action_count: length(actions), human_surface: true}}
  end

  defp render_schemas(actions, resources) do
    action_schemas =
      Enum.map(actions, fn action ->
        id = action["id"]
        safe_name = sanitize_identifier(id)
        resource_name = action["resource"]

        fields =
          case find_resource(resources, resource_name) do
            %{"fields" => f} when is_map(f) -> f
            _ -> %{}
          end

        input_fields =
          Enum.map(fields, fn {fname, fdef} ->
            "  #{fname}: #{map_zod_type(fdef)}"
          end)
          |> Enum.join(",\n")

        """
        export const #{safe_name}_inputSchema = z.object({
        #{input_fields}
        }).passthrough();

        export const #{safe_name}_outputSchema = z.object({
          success: z.boolean(),
          data: z.record(z.string(), z.unknown()).optional(),
          receiptRef: z.string().optional(),
          error: z.string().optional()
        }).passthrough();
        """
      end)
      |> Enum.join("\n\n")

    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.17)
    // Do not edit directly; modify authoritative Ash resources or ontology instead.

    import { z } from "zod";

    #{action_schemas}

    export const SCHEMAS = {
    #{Enum.map_join(actions, ",\n", fn a -> "  #{inspect(a["id"])}: { input: #{sanitize_identifier(a["id"])}_inputSchema, output: #{sanitize_identifier(a["id"])}_outputSchema }" end)}
    };
    """
  end

  # The delegated boundary lookup emitted below FAILS CLOSED
  # (finish-tripwires-024): an id that admits no descriptor has no delegated
  # boundary, so `getAuthorityBoundary` answers null — the v26.9.16 law
  # (absent == not delegated == null) extended to the absent action. The
  # former `: "OBSERVE"` fallback fabricated the safest-sounding boundary for
  # an unknown id on the delegated lookup path; unknown ≠ OBSERVE. Enforced by
  # ExpoActionsTest's TRIPWIRE over the rendered artifact.
  defp render_actions(actions) do
    actions_json = Jason.encode!(actions, pretty: true)

    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.17)
    // Explicit authority boundaries and semantic identities for machine discoverability.

    export const ACTIONS = Object.freeze(#{actions_json});

    export function getAction(id) {
      return ACTIONS.find((a) => a.id === id) ?? null;
    }

    export function hasDoAuthority(id) {
      const action = getAction(id);
      return action ? action.doAuthority === true : false;
    }

    export function getAuthorityBoundary(id) {
      const action = getAction(id);
      return action ? action.authorityBoundary : null;
    }
    """
  end

  defp render_events do
    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.17)
    // Read-only realtime observation and event projection layer.

    import { z } from "zod";

    export const eventProjectionSchema = z.object({
      eventId: z.string().min(1),
      sequence: z.number().int().nonnegative(),
      subjectRef: z.string().min(1),
      eventType: z.string().min(1),
      stateDigest: z.string().min(1),
      evidenceRef: z.string().nullable().optional(),
      receiptRef: z.string().nullable().optional(),
      payload: z.record(z.string(), z.unknown()).nullable().optional(),
      occurredAt: z.string().min(1),
      authorityBoundary: z.literal("OBSERVE").default("OBSERVE"),
    }).passthrough();

    export function parseEvent(raw) {
      return eventProjectionSchema.parse(raw);
    }
    """
  end

  defp render_receipts do
    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.17)
    // MX Consequence Receipt Envelope & Offline Reconciliation Protocol.
    //
    // receiptHash integrity law (chicago-receipthash-038). receiptHash is NOT
    // free-form: it is the lowercase-hex SHA-256 of receiptHashPreimage(receipt)
    // — canonical JSON over the envelope's named content fields, EXCLUDING
    // receiptHash itself. The content-field list hashed:
    //   episodeId, correlationId, exactSubject, actionId, semanticActionId,
    //   authorityBoundary, actorRef, preStateDigest, inputDigest, policyRef,
    //   taskNetworkRef, transportReceipt, domainReceiptRef, evidenceRefs,
    //   outcome, postStateDigest, standingBefore, standingAfter, replayKey,
    //   timestamp
    // The runtime transport receipt mints the same law over its named payload:
    //   actionId, input, consequence, dispatchState, selectedTransport,
    //   timestamp
    // Canonical bytes: recursively key-sorted objects, order-preserving arrays
    // (`canonicalStringify` below; Elixir twin `AshSurface.CanonicalJSON`).
    // Any field reorder therefore leaves the hash unchanged; any value change
    // must move it.

    import { z } from "zod";

    export const mxReceiptSchema = z.object({
      episodeId: z.string().min(1),
      correlationId: z.string().min(1),
      exactSubject: z.string().min(1),
      actionId: z.string().min(1),
      semanticActionId: z.string().min(1),
      authorityBoundary: z.enum(["OBSERVE", "SELECT", "CONSTRUCT", "DO"]),
      actorRef: z.string().optional(),
      preStateDigest: z.string().optional(),
      inputDigest: z.string().min(1),
      policyRef: z.string().optional(),
      taskNetworkRef: z.string().optional(),
      transportReceipt: z.record(z.string(), z.unknown()),
      domainReceiptRef: z.string().optional(),
      evidenceRefs: z.array(z.string()).default([]),
      outcome: z.enum(["COMPLETED", "REFUSED", "UNKNOWN_AFTER_DISPATCH"]),
      postStateDigest: z.string().optional(),
      standingBefore: z.string().optional(),
      standingAfter: z.string().optional(),
      replayKey: z.string().min(1),
      // Integrity commitment over the content fields above (never over this
      // slot): lowercase-hex sha256 of receiptHashPreimage(receipt).
      receiptHash: z.string().min(64),
      timestamp: z.string().min(1),
    }).passthrough();

    export function canonicalStringify(obj) {
      if (obj === null || typeof obj !== "object") return JSON.stringify(obj);
      if (Array.isArray(obj)) return `[${obj.map(canonicalStringify).join(",")}]`;
      const keys = Object.keys(obj).sort();
      return `{${keys.map((k) => `${JSON.stringify(k)}:${canonicalStringify(obj[k])}`).join(",")}}`;
    }

    // Verification-only preimage of the receiptHash integrity law: canonical
    // JSON bytes over every named content field of the receipt EXCEPT the
    // receiptHash slot itself. Hashing stays with the platform crypto provider
    // (SubtleCrypto / node:crypto): receiptHash is sha256(preimage) rendered
    // as lowercase hex. Nothing is constructed, assigned, or signed here.
    export function receiptHashPreimage(receipt) {
      if (receipt === null || typeof receipt !== "object" || Array.isArray(receipt)) {
        throw new TypeError("receiptHashPreimage: receipt must be an envelope object");
      }
      const content = { ...receipt };
      delete content.receiptHash;
      return canonicalStringify(content);
    }
    """
  end

  defp render_human do
    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.21)
    // Human projection helpers. This artifact presents choices and commitments,
    // but cannot acquire DO authority or dispatch a consequence.

    import {
      humanSurfaceSchema,
      parseHumanSurfaceProjection,
    } from "ash_surface";

    export const HUMAN_AREAS = Object.freeze(["TODAY", "BIBLE", "LIFE", "ZOE", "YOU"]);
    export const HUMAN_GRAMMAR = Object.freeze([
      "SEE",
      "UNDERSTAND",
      "EXPLORE",
      "CHOOSE",
      "ACT",
      "LEARN",
    ]);

    export function parseHumanSurface(raw) {
      return parseHumanSurfaceProjection(raw);
    }

    export function getArea(raw, areaName) {
      const surface = humanSurfaceSchema.parse(raw);
      if (!HUMAN_AREAS.includes(areaName)) {
        throw new TypeError("Unknown human area: " + String(areaName));
      }

      return surface[areaName.toLowerCase()];
    }

    export function preservedPossibilities(raw) {
      const surface = humanSurfaceSchema.parse(raw);

      return surface.possibilitySets.flatMap((set) =>
        set.possibilities.filter(
          (option) => option.status === "PRESERVED" || option.status === "CANDIDATE",
        ),
      );
    }

    export function explanationsFor(raw, subjectRef) {
      const surface = humanSurfaceSchema.parse(raw);
      return surface.explanations.filter((explanation) => explanation.subjectRef === subjectRef);
    }

    export function personalizationContext(raw, contextId) {
      const surface = humanSurfaceSchema.parse(raw);
      return surface.personalizationContexts.find((item) => item.contextId === contextId) ?? null;
    }

    export function manufactureTraceFor(raw, artifactRef) {
      const surface = humanSurfaceSchema.parse(raw);
      return surface.manufactureTraces.find((item) => item.artifactRef === artifactRef) ?? null;
    }

    export function devotionalQueue(raw, episodeId) {
      const surface = humanSurfaceSchema.parse(raw);
      const episode = surface.devotionalEpisodes.find((item) => item.episodeId === episodeId);
      if (!episode) return null;

      return Object.freeze({
        episodeId,
        title: episode.title,
        continuousPlay: episode.continuousPlay,
        playbackPolicy: episode.playbackPolicy,
        durationSeconds: episode.durationSeconds,
        segments: Object.freeze([...episode.segments].sort((a, b) => a.position - b.position)),
      });
    }

    export function commitmentPreview(raw, actionRef) {
      const surface = humanSurfaceSchema.parse(raw);
      const boundary = surface.commitmentBoundaries.find((item) => item.actionRef === actionRef);
      if (!boundary) return null;

      return Object.freeze({
        boundaryId: boundary.boundaryId,
        actionRef: boundary.actionRef,
        consequenceSummary: boundary.consequenceSummary,
        externalEffects: Object.freeze([...boundary.externalEffects]),
        reversibility: boundary.reversibility,
        confirmationState: boundary.confirmationState,
        confirmationRequired: boundary.confirmationRequired,
        nextHandoff: boundary.nextHandoff,
        authorityCeiling: boundary.authorityCeiling,
        doAuthority: boundary.doAuthority,
      });
    }

    export function journeyTimeline(raw) {
      const surface = humanSurfaceSchema.parse(raw);

      return Object.freeze(
        surface.journeys
          .flatMap((journey) =>
            journey.entries.map((entry) => ({
              ...entry,
              journeyId: journey.journeyId,
              privacyScope: journey.privacyScope,
            })),
          )
          .sort((left, right) => left.occurredAt.localeCompare(right.occurredAt)),
      );
    }

    export function assertNoDoAuthority(raw) {
      const surface = humanSurfaceSchema.parse(raw);

      if (surface.doAuthority !== false || surface.authorityBoundary !== "OBSERVE") {
        throw new Error("Human surface attempted to exceed OBSERVE authority");
      }

      for (const set of surface.possibilitySets) {
        for (const option of set.possibilities) {
          if (option.doAuthority !== false || option.authorityCeiling === "DO") {
            throw new Error("Possibility " + option.possibilityId + " attempted DO authority");
          }
        }
      }

      for (const context of surface.personalizationContexts) {
        if (
          context.doAuthority !== false ||
          context.authorityBoundary !== "OBSERVE" ||
          context.privacyScope !== "SUBJECT_PRIVATE" ||
          context.shareScope !== "SUBJECT_ONLY"
        ) {
          throw new Error("Personalization context " + context.contextId + " violates privacy/authority");
        }
      }

      for (const trace of surface.manufactureTraces) {
        if (trace.doAuthority !== false || trace.authorityBoundary !== "OBSERVE") {
          throw new Error("Manufacture trace " + trace.traceId + " attempted authority");
        }
      }

      for (const boundary of surface.commitmentBoundaries) {
        if (
          boundary.doAuthority !== false ||
          boundary.authorityCeiling !== "CONSTRUCT" ||
          boundary.nextHandoff !== "BRCE"
        ) {
          throw new Error("Commitment boundary " + boundary.boundaryId + " bypasses BRCE");
        }
      }

      return true;
    }
    """
  end

  defp render_demo(prefix) do
    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.21)
    // Deterministic human demo consumer. Local playback and intent construction
    // are allowed; network dispatch, provider reads, and consequence-bearing DO
    // are deliberately absent.

    import {
      parseHumanSurface,
      preservedPossibilities,
      explanationsFor,
      personalizationContext,
      manufactureTraceFor,
      devotionalQueue,
      commitmentPreview,
      journeyTimeline,
      assertNoDoAuthority,
    } from "./#{prefix}.human.mjs";

    export function buildZoeDemoViewModel(raw) {
      const surface = parseHumanSurface(raw);
      assertNoDoAuthority(surface);

      if (surface.zoe?.liveProviderReads !== false) {
        throw new Error("ZOE demo consumer requires liveProviderReads=false");
      }

      const possibilities = preservedPossibilities(surface);
      const episodeId = surface.bible?.devotionalEpisodeRefs?.[0] ?? null;
      const devotional = episodeId ? devotionalQueue(surface, episodeId) : null;
      const contextId = surface.life?.personalizationContextRefs?.[0] ?? null;
      const context = contextId ? personalizationContext(surface, contextId) : null;
      const traceRef = surface.life?.manufactureTraceRefs?.[0] ?? null;
      const trace =
        surface.manufactureTraces.find((item) => item.traceId === traceRef) ??
        surface.manufactureTraces[0] ??
        null;
      const whySubject = trace?.artifactRef ?? devotional?.episodeId ?? null;
      const explanations = whySubject ? explanationsFor(surface, whySubject) : [];
      const why = explanations[0] ?? surface.explanations[0] ?? null;
      const commitment =
        surface.commitmentBoundaries.length > 0
          ? commitmentPreview(surface, surface.commitmentBoundaries[0].actionRef)
          : null;

      return Object.freeze({
        syntheticOnly: true,
        exactSubject: surface.exactSubject,
        areas: Object.freeze([...surface.areas]),
        grammar: Object.freeze([...surface.grammar]),
        possibilities: Object.freeze([...possibilities]),
        devotional,
        whyThis: why,
        personalization: context,
        manufactureTrace: trace,
        journey: journeyTimeline(surface),
        commitment,
        authorityBoundary: surface.authorityBoundary,
        doAuthority: false,
        liveProviderReads: false,
      });
    }

    export function createContinuousDevotionalPlayer(raw, episodeId, options = {}) {
      const surface = parseHumanSurface(raw);
      assertNoDoAuthority(surface);
      const queue = devotionalQueue(surface, episodeId);

      if (!queue) throw new Error("Unknown devotional episode: " + String(episodeId));
      if (queue.continuousPlay !== true || queue.playbackPolicy !== "STRAIGHT_THROUGH") {
        throw new Error("Devotional episode is not admitted for straight-through playback");
      }

      const adapter = options.adapter ?? createTimedDemoPlaybackAdapter();
      const listeners = new Set();
      let currentHandle = null;
      let runPromise = null;
      let cancelled = false;
      let state = Object.freeze({
        status: "IDLE",
        episodeId,
        index: -1,
        segmentRef: null,
        receipt: null,
      });

      const emit = (next) => {
        state = Object.freeze({ ...state, ...next });
        for (const listener of listeners) listener(state);
      };

      async function run() {
        cancelled = false;

        for (let index = 0; index < queue.segments.length; index += 1) {
          if (cancelled) break;

          const segment = queue.segments[index];
          currentHandle = adapter.open(segment);
          if (!currentHandle || typeof currentHandle.play !== "function") {
            throw new TypeError("playback adapter must return a handle with play()");
          }

          emit({
            status: "PLAYING",
            index,
            segmentRef: segment.ref,
            receipt: null,
          });

          await currentHandle.play();
          currentHandle = null;
        }

        if (!cancelled) {
          const receipt = Object.freeze({
            kind: "LOCAL_PLAYBACK_COMPLETED",
            episodeId,
            segmentRefs: Object.freeze(queue.segments.map((segment) => segment.ref)),
            externalEffects: false,
            authorityBoundary: "OBSERVE",
            doAuthority: false,
          });

          emit({
            status: "COMPLETED",
            index: queue.segments.length - 1,
            segmentRef: queue.segments.at(-1)?.ref ?? null,
            receipt,
          });
        }

        runPromise = null;
        return state;
      }

      return Object.freeze({
        snapshot() {
          return state;
        },
        subscribe(listener) {
          if (typeof listener !== "function") throw new TypeError("listener must be a function");
          listeners.add(listener);
          listener(state);
          return () => listeners.delete(listener);
        },
        start() {
          if (!runPromise) runPromise = run();
          return runPromise;
        },
        pause() {
          if (state.status !== "PLAYING" || !currentHandle?.pause) return state;
          currentHandle.pause();
          emit({ status: "PAUSED" });
          return state;
        },
        resume() {
          if (state.status !== "PAUSED" || !currentHandle?.resume) return state;
          currentHandle.resume();
          emit({ status: "PLAYING" });
          return state;
        },
        stop() {
          cancelled = true;
          currentHandle?.stop?.();
          currentHandle = null;
          emit({ status: "STOPPED", receipt: null });
          return state;
        },
      });
    }

    export function createTimedDemoPlaybackAdapter(options = {}) {
      const millisPerSecond = options.millisPerSecond ?? 1;

      return Object.freeze({
        open(segment) {
          let remaining = Math.max(0, segment.durationSeconds * millisPerSecond);
          let timer = null;
          let startedAt = null;
          let settled = false;
          let resolveDone;

          const done = new Promise((resolve) => {
            resolveDone = resolve;
          });

          const arm = () => {
            if (settled) return;
            startedAt = Date.now();
            timer = setTimeout(() => {
              settled = true;
              timer = null;
              remaining = 0;
              resolveDone();
            }, remaining);
          };

          return Object.freeze({
            play() {
              if (!settled && timer === null) arm();
              return done;
            },
            pause() {
              if (settled || timer === null) return;
              clearTimeout(timer);
              timer = null;
              remaining = Math.max(0, remaining - (Date.now() - startedAt));
            },
            resume() {
              if (!settled && timer === null) arm();
              return done;
            },
            stop() {
              if (timer !== null) clearTimeout(timer);
              timer = null;
              if (!settled) {
                settled = true;
                resolveDone();
              }
            },
          });
        },
      });
    }

    export function createHtmlAudioAdapter(options = {}) {
      const resolveAudioRef = options.resolveAudioRef ?? ((audioRef) => audioRef);
      const audioFactory =
        options.audioFactory ??
        ((src) => {
          if (typeof Audio !== "function") {
            throw new Error("HTML Audio is unavailable; provide audioFactory");
          }
          return new Audio(src);
        });

      return Object.freeze({
        open(segment) {
          if (!segment.audioRef) {
            return createTimedDemoPlaybackAdapter({ millisPerSecond: 0 }).open(segment);
          }

          const src = resolveAudioRef(segment.audioRef, segment);
          if (!src) throw new Error("No admitted media source for " + segment.audioRef);

          const audio = audioFactory(src, segment);
          let settled = false;
          let resolveDone;
          let rejectDone;
          const done = new Promise((resolve, reject) => {
            resolveDone = resolve;
            rejectDone = reject;
          });

          const cleanup = () => {
            audio.removeEventListener?.("ended", onEnded);
            audio.removeEventListener?.("error", onError);
          };
          const onEnded = () => {
            if (settled) return;
            settled = true;
            cleanup();
            resolveDone();
          };
          const onError = (event) => {
            if (settled) return;
            settled = true;
            cleanup();
            rejectDone(event instanceof Error ? event : new Error("audio playback failed"));
          };

          audio.addEventListener?.("ended", onEnded);
          audio.addEventListener?.("error", onError);

          return Object.freeze({
            async play() {
              await audio.play();
              return done;
            },
            pause() {
              audio.pause();
            },
            async resume() {
              await audio.play();
              return done;
            },
            stop() {
              audio.pause();
              try {
                audio.currentTime = 0;
              } catch {
                // Some injected media handles expose read-only currentTime.
              }
              if (!settled) {
                settled = true;
                cleanup();
                resolveDone();
              }
            },
          });
        },
      });
    }

    export function constructBrceIntent(raw, actionRef) {
      const surface = parseHumanSurface(raw);
      assertNoDoAuthority(surface);
      const boundary = commitmentPreview(surface, actionRef);

      if (!boundary) throw new Error("No commitment boundary for " + String(actionRef));

      return Object.freeze({
        kind: "CONSTRUCT_INTENT",
        exactSubject: surface.exactSubject,
        boundaryId: boundary.boundaryId,
        actionRef: boundary.actionRef,
        consequenceSummary: boundary.consequenceSummary,
        externalEffects: Object.freeze([...boundary.externalEffects]),
        reversibility: boundary.reversibility,
        confirmationRequired: boundary.confirmationRequired,
        authorityCeiling: "CONSTRUCT",
        nextHandoff: "BRCE",
        dispatched: false,
        doAuthority: false,
      });
    }

    export function renderZoeDemoHtml(raw) {
      const view = buildZoeDemoViewModel(raw);
      const esc = escapeHtml;
      const why = view.whyThis;
      const trace = view.manufactureTrace;
      const context = view.personalization;
      const commitment = view.commitment;

      const possibilities = view.possibilities
        .map(
          (option) =>
            '<li data-testid="possibility"><strong>' +
            esc(option.label) +
            "</strong><span>" +
            esc(option.summary ?? "") +
            "</span></li>",
        )
        .join("");

      const basis = (why?.basis ?? []).map((item) => "<li>" + esc(item) + "</li>").join("");
      const caveats = (why?.caveats ?? []).map((item) => "<li>" + esc(item) + "</li>").join("");
      const journey = view.journey
        .map(
          (entry) =>
            '<li data-testid="journey-entry"><strong>' +
            esc(entry.label) +
            "</strong><span>" +
            esc(entry.occurredAt) +
            "</span></li>",
        )
        .join("");

      return [
        '<main data-testid="zoe-demo" data-authority="OBSERVE">',
        '<p data-testid="demo-ceiling">Synthetic demo · no live provider reads · no external effects</p>',
        "<h1>Today</h1>",
        '<ul data-testid="dfcm-frontier">' + possibilities + "</ul>",
        '<section data-testid="devotional"><h2>' + esc(view.devotional?.title ?? "Devotional") + "</h2>",
        '<p>Straight-through playback: ' + esc(String(view.devotional?.continuousPlay === true)) + "</p>",
        '<button data-demo-action="play">Play straight through</button>',
        '<button data-demo-action="pause">Pause</button>',
        '<button data-demo-action="resume">Resume</button>',
        '<output data-testid="playback-status">IDLE</output></section>',
        '<section data-testid="why-this"><h2>' + esc(why?.title ?? "Why this?") + "</h2>",
        "<p>" + esc(why?.summary ?? "") + "</p>",
        "<p>Claim: " + esc(why?.claimKind ?? "") + " · Evidence: " + esc(why?.evidenceState ?? "") + "</p>",
        "<p>Falsifier: " + esc(why?.falsifier ?? "") + "</p>",
        "<ul>" + basis + "</ul><ul>" + caveats + "</ul>",
        "<p>Personalization source: " + esc(context?.facets?.[0]?.source ?? "NONE") + "</p>",
        '<p data-testid="chatman-equation">' + esc(trace?.equation ?? "") + "</p>",
        "<p>O*: " + esc((trace?.oStarRefs ?? []).join(", ")) + "</p>",
        "<p>Receipt: " + esc((trace?.receiptRefs ?? []).join(", ")) + "</p></section>",
        '<section data-testid="journey"><h2>You</h2><ol>' + journey + "</ol></section>",
        '<section data-testid="commitment"><h2>ZOE</h2>',
        "<p>" + esc(commitment?.consequenceSummary ?? "") + "</p>",
        "<p>Next handoff: " + esc(commitment?.nextHandoff ?? "") + "</p>",
        '<button data-demo-action="construct-brce-intent">Confirm intent</button>',
        '<output data-testid="brce-status">Not constructed</output></section>',
        "</main>",
      ].join("");
    }

    function escapeHtml(value) {
      return String(value)
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#039;");
    }
    """
  end

  defp render_client(prefix) do
    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.17)
    // Complete, executable client manufactured with pre-bound Zod boundary schemas.

    import { createClient } from "ash_surface";
    import { SCHEMAS } from "./#{prefix}.schemas.mjs";
    import { ACTIONS } from "./#{prefix}.actions.mjs";

    export function createZoelaClient({ contract, transports = {}, prefer = "http", reconcileEndpoint }) {
      const client = createClient({
        contract,
        transports,
        prefer,
        schemas: SCHEMAS,
      });

      return Object.freeze({
        ...client,
        actionsMetadata: ACTIONS,
        async reconcile(commandId) {
          if (!reconcileEndpoint) {
            throw new Error("No reconcileEndpoint configured on client");
          }
          const res = await fetch(`${reconcileEndpoint}?commandId=${encodeURIComponent(commandId)}`);
          if (!res.ok) return { status: "STILL_UNKNOWN" };
          return await res.json();
        }
      });
    }
    """
  end

  defp render_tanstack(_actions, prefix) do
    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.17)
    // TanStack Query cache adapter for Expo / React Native.

    import { getAction } from "./#{prefix}.actions.mjs";

    export const queryKeys = {
      all: ["ash_surface"],
      resource: (res) => ["ash_surface", res],
      action: (res, act) => ["ash_surface", res, act],
    };

    export function createMutationOptions(client, actionId) {
      const meta = getAction(actionId);
      const action = client.get(actionId);

      return {
        mutationKey: queryKeys.action(meta?.resource, meta?.action),
        mutationFn: async (input) => {
          return await action.invokeWithReceipt(input);
        }
      };
    }
    """
  end

  defp map_zod_type(%{"type" => %{"kind" => kind}} = def) do
    base =
      case kind do
        "string" -> "z.string()"
        "integer" -> "z.number().int()"
        "boolean" -> "z.boolean()"
        "uuid" -> "z.string().uuid()"
        "float" -> "z.number()"
        "decimal" -> "z.number()"
        "utc_datetime" -> "z.string()"
        "datetime" -> "z.string()"
        "map" -> "z.record(z.string(), z.unknown())"
        "array" -> "z.array(z.unknown())"
        _ -> "z.unknown()"
      end

    if def["allow_nil?"] == true do
      "#{base}.optional().nullable()"
    else
      base
    end
  end

  defp map_zod_type(_), do: "z.unknown().optional()"

  defp find_resource(resources, name) when is_map(resources) do
    Enum.find_value(resources, fn
      {_k, %{"name" => ^name} = r} -> r
      {_k, %{"module" => ^name} = r} -> r
      _ -> nil
    end)
  end

  defp find_resource(resources, name) when is_list(resources) do
    Enum.find(resources, fn
      %{"name" => ^name} -> true
      %{"module" => ^name} -> true
      _ -> false
    end)
  end

  defp find_resource(_, _), do: nil

  defp sanitize_identifier(id) do
    id
    |> String.replace(~r/[^a-zA-Z0-9_]/, "_")
  end
end
