defmodule AshSurface.Projector.Expo do
  @moduledoc """
  Projector for React Native / Expo applications (ZOELA consumer substrate).

  Manufactures:
  - `{prefix}.schemas.mjs`: Pre-compiled Zod input & output boundary schemas
  - `{prefix}.actions.mjs`: Machine-discoverable MX action descriptors with explicit authority boundaries
  - `{prefix}.events.mjs`: Read-only realtime observation & event projections
  - `{prefix}.receipts.mjs`: MX receipt envelope and reconciliation primitives
  - `{prefix}.mjs`: Executable client runtime factory pre-bound with manufactured schemas
  """

  @behaviour AshSurface.Projector

  @impl true
  def project(%AshSurface.Surface{} = surface, opts \\ []) do
    prefix = Keyword.get(opts, :prefix, "zoela_surface")
    target_dir = Keyword.get(opts, :target_dir)

    actions = get_in(surface.contract, ["surface", "actions"]) || []
    resources = get_in(surface.contract, ["manifest", "resources"]) || %{}

    schemas_code = render_schemas(actions, resources)
    actions_code = render_actions(actions)
    events_code = render_events()
    receipts_code = render_receipts()
    client_code = render_client(prefix)
    tanstack_code = render_tanstack(actions, prefix)

    artifacts = %{
      "#{prefix}.schemas.mjs" => schemas_code,
      "#{prefix}.actions.mjs" => actions_code,
      "#{prefix}.events.mjs" => events_code,
      "#{prefix}.receipts.mjs" => receipts_code,
      "#{prefix}.mjs" => client_code,
      "#{prefix}.tanstack.mjs" => tanstack_code
    }

    if target_dir do
      File.mkdir_p!(target_dir)

      Enum.each(artifacts, fn {filename, content} ->
        File.write!(Path.join(target_dir, filename), content)
      end)
    end

    {:ok, artifacts, %{prefix: prefix, action_count: length(actions)}}
  end

  defp render_schemas(actions, resources) do
    action_schemas =
      Enum.map(actions, fn action ->
        id = action["id"]
        safe_name = sanitize_identifier(id)
        resource_name = action["resource"]

        fields =
          case find_resource(resources, resource_name) do
            %{"fields" => f} when is_map(f) -> f
            _ -> %{}
          end

        input_fields =
          Enum.map(fields, fn {fname, fdef} ->
            "  #{fname}: #{map_zod_type(fdef)}"
          end)
          |> Enum.join(",\n")

        """
        export const #{safe_name}_inputSchema = z.object({
        #{input_fields}
        }).passthrough();

        export const #{safe_name}_outputSchema = z.object({
          success: z.boolean(),
          data: z.record(z.string(), z.unknown()).optional(),
          receiptRef: z.string().optional(),
          error: z.string().optional()
        }).passthrough();
        """
      end)
      |> Enum.join("\n\n")

    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.16)
    // Do not edit directly; modify authoritative Ash resources or ontology instead.

    import { z } from "zod";

    #{action_schemas}

    export const SCHEMAS = {
    #{Enum.map_join(actions, ",\n", fn a -> "  #{inspect(a["id"])}: { input: #{sanitize_identifier(a["id"])}_inputSchema, output: #{sanitize_identifier(a["id"])}_outputSchema }" end)}
    };
    """
  end

  defp render_actions(actions) do
    actions_json = Jason.encode!(actions, pretty: true)

    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.16)
    // Explicit authority boundaries and semantic identities for machine discoverability.

    export const ACTIONS = Object.freeze(#{actions_json});

    export function getAction(id) {
      return ACTIONS.find((a) => a.id === id) ?? null;
    }

    export function hasDoAuthority(id) {
      const action = getAction(id);
      return action ? action.doAuthority === true : false;
    }

    export function getAuthorityBoundary(id) {
      const action = getAction(id);
      return action ? action.authorityBoundary : "OBSERVE";
    }
    """
  end

  defp render_events do
    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.16)
    // Read-only realtime observation and event projection layer.

    import { z } from "zod";

    export const eventProjectionSchema = z.object({
      eventId: z.string().min(1),
      sequence: z.number().int().nonnegative(),
      subjectRef: z.string().min(1),
      eventType: z.string().min(1),
      stateDigest: z.string().min(1),
      evidenceRef: z.string().optional(),
      receiptRef: z.string().optional(),
      occurredAt: z.string().min(1),
      authorityBoundary: z.literal("OBSERVE").default("OBSERVE"),
    }).passthrough();

    export function parseEvent(raw) {
      return eventProjectionSchema.parse(raw);
    }
    """
  end

  defp render_receipts do
    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.16)
    // MX Consequence Receipt Envelope & Offline Reconciliation Protocol.

    import { z } from "zod";

    export const mxReceiptSchema = z.object({
      episodeId: z.string().min(1),
      correlationId: z.string().min(1),
      exactSubject: z.string().min(1),
      actionId: z.string().min(1),
      semanticActionId: z.string().min(1),
      authorityBoundary: z.enum(["OBSERVE", "SELECT", "CONSTRUCT", "DO"]),
      actorRef: z.string().optional(),
      preStateDigest: z.string().optional(),
      inputDigest: z.string().min(1),
      policyRef: z.string().optional(),
      taskNetworkRef: z.string().optional(),
      transportReceipt: z.record(z.string(), z.unknown()),
      domainReceiptRef: z.string().optional(),
      evidenceRefs: z.array(z.string()).default([]),
      outcome: z.enum(["COMPLETED", "REFUSED", "UNKNOWN_AFTER_DISPATCH"]),
      postStateDigest: z.string().optional(),
      standingBefore: z.string().optional(),
      standingAfter: z.string().optional(),
      replayKey: z.string().min(1),
      receiptHash: z.string().min(64),
      timestamp: z.string().min(1),
    }).passthrough();

    export function canonicalStringify(obj) {
      if (obj === null || typeof obj !== "object") return JSON.stringify(obj);
      if (Array.isArray(obj)) return `[${obj.map(canonicalStringify).join(",")}]`;
      const keys = Object.keys(obj).sort();
      return `{${keys.map((k) => `${JSON.stringify(k)}:${canonicalStringify(obj[k])}`).join(",")}}`;
    }
    """
  end

  defp render_client(prefix) do
    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.16)
    // Complete, executable client manufactured with pre-bound Zod boundary schemas.

    import { createClient } from "ash_surface";
    import { SCHEMAS } from "./#{prefix}.schemas.mjs";
    import { ACTIONS } from "./#{prefix}.actions.mjs";

    export function createZoelaClient({ contract, transports = {}, prefer = "http", reconcileEndpoint }) {
      const client = createClient({
        contract,
        transports,
        prefer,
        schemas: SCHEMAS,
      });

      return Object.freeze({
        ...client,
        actionsMetadata: ACTIONS,
        async reconcile(commandId) {
          if (!reconcileEndpoint) {
            throw new Error("No reconcileEndpoint configured on client");
          }
          const res = await fetch(`${reconcileEndpoint}?commandId=${encodeURIComponent(commandId)}`);
          if (!res.ok) return { status: "STILL_UNKNOWN" };
          return await res.json();
        }
      });
    }
    """
  end

  defp render_tanstack(_actions, prefix) do
    """
    // @generated by AshSurface.Projector.Expo (CalVer 26.9.16)
    // TanStack Query cache adapter for Expo / React Native.

    import { getAction } from "./#{prefix}.actions.mjs";

    export const queryKeys = {
      all: ["ash_surface"],
      resource: (res) => ["ash_surface", res],
      action: (res, act) => ["ash_surface", res, act],
    };

    export function createMutationOptions(client, actionId) {
      const meta = getAction(actionId);
      const action = client.get(actionId);

      return {
        mutationKey: queryKeys.action(meta?.resource, meta?.action),
        mutationFn: async (input) => {
          return await action.invokeWithReceipt(input);
        }
      };
    }
    """
  end

  defp map_zod_type(%{"type" => %{"kind" => kind}} = def) do
    base =
      case kind do
        "string" -> "z.string()"
        "integer" -> "z.number().int()"
        "boolean" -> "z.boolean()"
        "uuid" -> "z.string().uuid()"
        "float" -> "z.number()"
        "decimal" -> "z.number()"
        "utc_datetime" -> "z.string()"
        "datetime" -> "z.string()"
        "map" -> "z.record(z.string(), z.unknown())"
        "array" -> "z.array(z.unknown())"
        _ -> "z.unknown()"
      end

    if def["allow_nil?"] == true do
      "#{base}.optional().nullable()"
    else
      base
    end
  end

  defp map_zod_type(_), do: "z.unknown().optional()"

  defp find_resource(resources, name) when is_map(resources) do
    Enum.find_value(resources, fn
      {_k, %{"name" => ^name} = r} -> r
      {_k, %{"module" => ^name} = r} -> r
      _ -> nil
    end)
  end

  defp find_resource(resources, name) when is_list(resources) do
    Enum.find(resources, fn
      %{"name" => ^name} -> true
      %{"module" => ^name} -> true
      _ -> false
    end)
  end

  defp find_resource(_, _), do: nil

  defp sanitize_identifier(id) do
    id
    |> String.replace(~r/[^a-zA-Z0-9_]/, "_")
  end
end
