defmodule AshSurface.Projectors.JS do
  @moduledoc """
  JSDoc + Zod client projector over the canonical `AshSurface.IR`.

  `project_ir/2` emits ONE `.mjs` artifact (default prefix
  `ash_surface_client`) exporting:

  - JSDoc-typed resource namespaces of action descriptors,
  - Zod boundary schemas, embedded verbatim from the admitted
    `IR.Schema.zod` strings,
  - action descriptors where DO-boundary actions carry dispatch-INTENT
    descriptors only: `dispatchIntent/2` mints frozen data and there is no
    invoke/dispatch execution path anywhere in the artifact.

  The projection is byte-deterministic: entries are id-sorted, namespaces
  resource-sorted, and descriptor field order is fixed.
  """

  alias AshSurface.Projector.IREntry

  @calver "26.9.13"
  @default_prefix "ash_surface_client"

  @doc """
  Projects one IR (or a list of IRs) into a single JSDoc + Zod `.mjs` client
  artifact.

  Options:

  - `:prefix` — artifact filename prefix (default `#{@default_prefix}`);
    the sole emitted file is `#{String.replace_suffix(@default_prefix, "", ".mjs")}`.
  - `:target_dir` — when set, the artifact is also written there.

  Returns `{:ok, artifacts, meta}` where `artifacts` has exactly one entry and
  `meta` carries `:prefix`, `:action_count`, and `:namespace_count`.
  """
  @spec project_ir(AshSurface.IR.t() | [AshSurface.IR.t()], keyword()) ::
          {:ok, %{optional(String.t()) => String.t()}, map()}
  def project_ir(ir, opts \\ []) do
    prefix = Keyword.get(opts, :prefix, @default_prefix)
    entries = IREntry.entries(ir)
    code = render(entries, prefix)
    filename = prefix <> ".mjs"

    case Keyword.get(opts, :target_dir) do
      nil ->
        :ok

      target_dir ->
        File.mkdir_p!(target_dir)
        File.write!(Path.join(target_dir, filename), code)
    end

    {:ok, %{filename => code},
     %{
       prefix: prefix,
       action_count: length(entries),
       namespace_count: entries |> Enum.map(& &1.resource) |> Enum.uniq() |> length()
     }}
  end

  defp render(entries, prefix) do
    [
      header(prefix),
      schema_consts(entries),
      namespaces(entries),
      registries(entries)
    ]
    |> Enum.reject(&(&1 == ""))
    |> Enum.join("\n\n")
    |> Kernel.<>("\n")
  end

  defp header(prefix) do
    """
    // @generated by AshSurface.Projectors.JS (CalVer #{@calver}); prefix #{js_string(prefix)}
    // Do not edit directly; change the admitted IR sources, then re-project.
    // Law: pi_JS(IR) = JavaScript + JSDoc + Zod. TypeScript-free, no build step.
    // DO-boundary actions project dispatch-INTENT descriptors only: an intent
    // is data and carries no execution authority; this artifact contains no
    // invoke/dispatch execution path.

    import { z } from "zod";

    /**
     * A dispatch intent for a DO-boundary action. DATA ONLY: minting an
     * intent never executes the action. Execution requires a separately
     * admitted, brokered, receipt-bearing dispatch path.
     * @typedef {Object} DispatchIntent
     * @property {"DISPATCH_INTENT"} kind
     * @property {string} actionId
     * @property {Record<string, unknown>} input - boundary-validated by the action Zod schema when present
     */\
    """
  end

  defp schema_consts(entries) do
    entries
    |> Enum.filter(& &1.zod)
    |> Enum.map(fn entry ->
      """
      /** Zod boundary schema for `#{entry.id}` (IR.Schema.zod, verbatim). */
      export const #{schema_const(entry)} = #{entry.zod};\
      """
    end)
    |> Enum.join("\n\n")
  end

  defp namespaces(entries) do
    entries
    |> Enum.group_by(& &1.resource)
    |> Enum.sort_by(fn {resource, _} -> resource end)
    |> Enum.map(fn {resource, group} -> namespace_block(resource, group) end)
    |> Enum.join("\n\n")
  end

  defp namespace_block(resource, group) do
    member_docs =
      group
      |> Enum.map(fn entry ->
        " * @property {Object} #{entry.action} - `#{entry.id}` (authorityBoundary: #{boundary_doc(entry)}, descriptorKind: \"#{descriptor_kind(entry)}\")"
      end)
      |> Enum.join("\n")

    members =
      group
      |> Enum.map(fn entry ->
        """
        #{indent(2)}/** `#{entry.id}` — #{boundary_doc(entry)}; #{intent_doc(entry)}. */
        #{indent(2)}#{entry.action}: #{descriptor(entry)}\
        """
      end)
      |> Enum.join(",\n")

    """
    /**
     * JSDoc-typed namespace for resource `#{resource}` (#{length(group)} #{pluralize(length(group), "action")}: #{Enum.map_join(group, ", ", & &1.action)}).
     * @typedef {Object} #{resource}Namespace
    #{member_docs}
     */
    export const #{resource} = Object.freeze({
    #{members}
    });\
    """
  end

  defp descriptor(entry) do
    fields = [
      "id: #{js_string(entry.id)}",
      "resource: #{js_string(entry.resource)}",
      "action: #{js_string(entry.action)}",
      "actionType: #{js_string(entry.action_type)}",
      "authorityBoundary: #{js_string(entry.authority_boundary)}",
      "receiptRequired: #{entry.receipt_required}",
      "descriptorKind: #{js_string(descriptor_kind(entry))}",
      "capabilityIri: #{js_string(entry.capability_iri)}",
      "label: #{js_string(entry.label)}",
      "schema: #{schema_ref(entry)}"
    ]

    fields_body = Enum.map_join(fields, ",\n", &(indent(4) <> &1))

    "Object.freeze({\n" <> fields_body <> "\n" <> indent(2) <> "})"
  end

  defp registries(entries) do
    """
    /**
     * Every action descriptor, sorted by id. DO-boundary descriptors carry
     * descriptorKind "DISPATCH_INTENT"; every other descriptor is a plain
     * "DESCRIPTOR". Members are the namespace objects themselves, so
     * descriptor identity is shared.
     */
    export const ACTIONS = Object.freeze([
    #{Enum.map_join(entries, ",\n", &(indent(2) <> member_ref(&1)))}
    ]);

    /** Zod boundary schemas by action id, present only where the IR delegated one. */
    export const SCHEMAS = Object.freeze({
    #{schema_registry(entries)}
    });

    /** Resource namespaces, sorted by resource name. */
    export const NAMESPACES = Object.freeze({
    #{namespace_registry(entries)}
    });

    /** Descriptor lookup by action id; null when unknown. */
    export function getAction(id) {
      return ACTIONS.find((a) => a.id === id) ?? null;
    }

    /**
     * Mints a dispatch INTENT for a DO-boundary action. Refused for unknown
     * actions and for any action whose delegated boundary is not exactly
     * "DO". Input is boundary-validated by the action's Zod schema when the
     * IR delegated one. Never executes anything.
     * @param {string} id
     * @param {Record<string, unknown>} input
     * @returns {DispatchIntent}
     */
    export function dispatchIntent(id, input) {
      const action = getAction(id);
      if (action === null) {
        throw new Error("REFUSED_UNKNOWN_ACTION: " + id);
      }
      if (action.descriptorKind !== "DISPATCH_INTENT") {
        throw new Error("REFUSED_NOT_DO_BOUNDARY: " + id + " has descriptorKind " + action.descriptorKind);
      }
      const parsed = action.schema ? action.schema.parse(input) : input;
      return Object.freeze({ kind: "DISPATCH_INTENT", actionId: id, input: parsed });
    }\
    """
  end

  defp schema_registry(entries) do
    entries
    |> Enum.filter(& &1.zod)
    |> Enum.map(&(indent(2) <> "#{js_string(&1.id)}: #{schema_const(&1)}"))
    |> Enum.join(",\n")
  end

  defp namespace_registry(entries) do
    entries
    |> Enum.map(& &1.resource)
    |> Enum.uniq()
    |> Enum.sort()
    |> Enum.map(&(indent(2) <> &1))
    |> Enum.join(",\n")
  end

  defp member_ref(entry), do: "#{entry.resource}.#{entry.action}"
  defp schema_const(entry), do: "#{sanitize(entry.id)}_schema"
  defp schema_ref(%{zod: nil}), do: "null"
  defp schema_ref(entry), do: schema_const(entry)

  defp descriptor_kind(entry),
    do: if(IREntry.do_boundary?(entry), do: "DISPATCH_INTENT", else: "DESCRIPTOR")

  defp boundary_doc(%{authority_boundary: nil}), do: "not delegated"
  defp boundary_doc(entry), do: "\"#{entry.authority_boundary}\""

  defp intent_doc(entry) do
    if IREntry.do_boundary?(entry) do
      "dispatch-intent only"
    else
      "no dispatch intent"
    end
  end

  defp sanitize(name), do: String.replace(name, ~r/[^A-Za-z0-9_$]/, "_")

  defp js_string(nil), do: "null"
  defp js_string(value) when is_binary(value), do: Jason.encode!(value)
  defp js_string(value) when is_boolean(value), do: to_string(value)

  defp indent(n), do: String.duplicate(" ", n)

  defp pluralize(1, word), do: word
  defp pluralize(n, word) when n > 1, do: word <> "s"
end
