// @generated by AshSurface.Projectors.JS (CalVer 26.9.13); prefix "ash_surface_client"
// Do not edit directly; change the admitted IR sources, then re-project.
// Law: pi_JS(IR) = JavaScript + JSDoc + Zod. TypeScript-free, no build step.
// DO-boundary actions project dispatch-INTENT descriptors only: an intent
// is data and carries no execution authority; this artifact contains no
// invoke/dispatch execution path.

import { z } from "zod";

/**
 * A dispatch intent for a DO-boundary action. DATA ONLY: minting an
 * intent never executes the action. Execution requires a separately
 * admitted, brokered, receipt-bearing dispatch path.
 * @typedef {Object} DispatchIntent
 * @property {"DISPATCH_INTENT"} kind
 * @property {string} actionId
 * @property {Record<string, unknown>} input - boundary-validated by the action Zod schema when present
 */

/** Zod boundary schema for `Todo.create` (IR.Schema.zod, verbatim). */
export const Todo_create_schema = z.object({
  title: z.string().min(1),
  due_on: z.string().optional()
});

/** Zod boundary schema for `Todo.list` (IR.Schema.zod, verbatim). */
export const Todo_list_schema = z.object({
  status: z.enum(["open", "done"]).optional()
});

/**
 * JSDoc-typed namespace for resource `Member` (2 actions: deactivate, profile).
 * @typedef {Object} MemberNamespace
 * @property {Object} deactivate - `Member.deactivate` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 * @property {Object} profile - `Member.profile` (authorityBoundary: "CONSTRUCT", descriptorKind: "DESCRIPTOR")
 */
export const Member = Object.freeze({
  /** `Member.deactivate` — not delegated; no dispatch intent. */
  deactivate: Object.freeze({
    id: "Member.deactivate",
    resource: "Member",
    action: "deactivate",
    actionType: "destroy",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    schema: null
  }),
  /** `Member.profile` — "CONSTRUCT"; no dispatch intent. */
  profile: Object.freeze({
    id: "Member.profile",
    resource: "Member",
    action: "profile",
    actionType: "read",
    authorityBoundary: "CONSTRUCT",
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: "Member profile",
    schema: null
  })
});

/**
 * JSDoc-typed namespace for resource `Todo` (2 actions: create, list).
 * @typedef {Object} TodoNamespace
 * @property {Object} create - `Todo.create` (authorityBoundary: "DO", descriptorKind: "DISPATCH_INTENT")
 * @property {Object} list - `Todo.list` (authorityBoundary: "OBSERVE", descriptorKind: "DESCRIPTOR")
 */
export const Todo = Object.freeze({
  /** `Todo.create` — "DO"; dispatch-intent only. */
  create: Object.freeze({
    id: "Todo.create",
    resource: "Todo",
    action: "create",
    actionType: "create",
    authorityBoundary: "DO",
    receiptRequired: true,
    descriptorKind: "DISPATCH_INTENT",
    capabilityIri: "cap:todo.write",
    label: "Create todo",
    schema: Todo_create_schema
  }),
  /** `Todo.list` — "OBSERVE"; no dispatch intent. */
  list: Object.freeze({
    id: "Todo.list",
    resource: "Todo",
    action: "list",
    actionType: "read",
    authorityBoundary: "OBSERVE",
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    schema: Todo_list_schema
  })
});

/**
 * Every action descriptor, sorted by id. DO-boundary descriptors carry
 * descriptorKind "DISPATCH_INTENT"; every other descriptor is a plain
 * "DESCRIPTOR". Members are the namespace objects themselves, so
 * descriptor identity is shared.
 */
export const ACTIONS = Object.freeze([
  Member.deactivate,
  Member.profile,
  Todo.create,
  Todo.list
]);

/** Zod boundary schemas by action id, present only where the IR delegated one. */
export const SCHEMAS = Object.freeze({
  "Todo.create": Todo_create_schema,
  "Todo.list": Todo_list_schema
});

/** Resource namespaces, sorted by resource name. */
export const NAMESPACES = Object.freeze({
  Member,
  Todo
});

/** Descriptor lookup by action id; null when unknown. */
export function getAction(id) {
  return ACTIONS.find((a) => a.id === id) ?? null;
}

/**
 * Mints a dispatch INTENT for a DO-boundary action. Refused for unknown
 * actions and for any action whose delegated boundary is not exactly
 * "DO". Input is boundary-validated by the action's Zod schema when the
 * IR delegated one. Never executes anything.
 * @param {string} id
 * @param {Record<string, unknown>} input
 * @returns {DispatchIntent}
 */
export function dispatchIntent(id, input) {
  const action = getAction(id);
  if (action === null) {
    throw new Error("REFUSED_UNKNOWN_ACTION: " + id);
  }
  if (action.descriptorKind !== "DISPATCH_INTENT") {
    throw new Error("REFUSED_NOT_DO_BOUNDARY: " + id + " has descriptorKind " + action.descriptorKind);
  }
  const parsed = action.schema ? action.schema.parse(input) : input;
  return Object.freeze({ kind: "DISPATCH_INTENT", actionId: id, input: parsed });
}
