#!/usr/bin/env bash
# bump_version.sh — the cross-surface version bump MECHANISM.
#
# Law (t09/t35 canon): mix.exs @version, lib/ash_surface.ex
# @surface_schema_version / @generator_identity / marketplaceIdentity, the JS
# runtime's SURFACE_RUNTIME_VERSION, and the projector CalVer headers must all
# move together, and every golden that freezes a consequence of the version
# must be regenerated in the same change. This script is the only lawful way
# to bump: it rewrites the constants, regenerates the computed goldens from
# the REAL pipelines (self-proven at the old version first), and fails on any
# unhandled drift instead of leaving a half-bumped tree.
#
# Golden families affected by a bump:
#   TEXT — literal "<old>" occurrences, rewritten verbatim (see TEXT_FILES).
#   RUNTIME_SHA — test/ash_surface/runtime_source_test.exs
#       @golden_runtime_sha256: SHA-256 of the whole runtime file (t09).
#   CONTRACT_DIGEST — test/ash_surface/digest_test.exs @golden: 5 SHA-256
#       digests over the full contract (surfaceSchemaVersion,
#       generatorIdentity and marketplaceIdentity participate in the digest).
#   JS_DIGEST — test/js/digest_cross_language.test.mjs elixirDigest: 3 digests
#       over the embedded contractJson fixtures (same fields participate).
#   JS_DIGEST_V2 — test/js/digest_cross_language_v2.test.mjs: 3 elixirDigest
#       pins (F4/F5/F6) over escape-bearing contractJson fixtures; the file's
#       T26_DIGESTS negative pins are re-pointed at the new v1 digests so
#       "v2 must deepen, never re-pin t26" stays meaningful after the bump.
#   IR_DIGEST — test/ash_surface/ir_codec_test.exs @golden: 5 digests over
#       the IR fixtures (identity carries the version), recomputed through
#       the real IR.Codec from_map/to_map/digest pipeline.
#   ARTIFACT_SHA — test/js/ir_projector_deep.test.mjs FROZEN_SHA256: hash of
#       the frozen projector artifact, re-derived through the real
#       Projectors.JS.project_ir/2 over the mirrored fixture IR.
#
# Usage:
#   bash scripts/bump_version.sh --check <new-version>   # print the plan only
#   bash scripts/bump_version.sh <new-version>           # apply + full gates
#
# Exit codes:
#   0 — plan/apply verified; on apply, all gates green
#   1 — unhandled drift or golden self-proof failure (fail-closed)
#   2 — usage error
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# ---------------------------------------------------------------------------
# Configuration: the handled surface. Everything else containing the old
# version string is UNHANDLED drift and fails the run.
# ---------------------------------------------------------------------------

TEXT_FILES="
mix.exs
lib/ash_surface.ex
lib/ash_surface/projector/expo.ex
priv/static/ash_surface_runtime.mjs
test/ash_surface/version_sync_test.exs
test/js/version_sync.test.mjs
test/ash_surface/manifest_serializer_test.exs
test/ash_surface/mx_closed_loop_episode_test.exs
test/ash_surface/mx_closed_loop_deep_test.exs
test/ash_surface/projector/expo_schemas_test.exs
test/ash_surface/projector/expo_events_test.exs
test/js/digest_cross_language.test.mjs
test/js/e2e_hermetic.test.mjs
test/js/zoela_mx_consumer_fixture.test.mjs
test/js/receipts_primitives.test.mjs
lib/ash_surface/projectors/js.ex
test/ash_surface/ir_codec_test.exs
test/ash_surface/ir_struct_test.exs
test/ash_surface/projectors/live_view_test.exs
test/js/digest_cross_language_v2.test.mjs
test/js/ir_projector_deep.test.mjs
"

# Computed goldens (regenerated by the embedded generator, never hand-edited).
GOLDEN_RUNTIME="test/ash_surface/runtime_source_test.exs"
GOLDEN_DIGEST="test/ash_surface/digest_test.exs"
GOLDEN_JS="test/js/digest_cross_language.test.mjs"
GOLDEN_JS_V2="test/js/digest_cross_language_v2.test.mjs"
GOLDEN_IR_CODEC="test/ash_surface/ir_codec_test.exs"
GOLDEN_ARTIFACT="test/js/ir_projector_deep.test.mjs"

GATE_LIST="mix compile --warnings-as-errors|mix format --check-formatted|mix test|npm test"

usage() {
  sed -n '2,37p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

die() { echo "BUMP_FAIL: $*" >&2; exit 1; }
count_of() { grep -oF -- "$2" "$1" | wc -l | tr -d ' '; }

# ---------------------------------------------------------------------------
# Args: [--check] <new-version>
# ---------------------------------------------------------------------------
CHECK=0
NEW=""
for arg in "$@"; do
  case "$arg" in
    --check) CHECK=1 ;;
    -h|--help) usage; exit 0 ;;
    -*) echo "unknown flag: $arg" >&2; usage; exit 2 ;;
    *)
      [ -n "$NEW" ] && { echo "multiple versions given" >&2; exit 2; }
      NEW="$arg" ;;
  esac
done

[ -n "$NEW" ] || { usage; exit 2; }
echo "$NEW" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || die "version '$NEW' is not X.Y.Z"

OLD="$(perl -ne 'print $1 if /^\s*\@version\s+"([^"]+)"/' mix.exs)"
[ -n "$OLD" ] || die "no @version found in mix.exs"
[ "$OLD" != "$NEW" ] || die "new version $NEW equals the current version"

# ---------------------------------------------------------------------------
# Drift scan: occurrences of OLD anywhere in the working tree outside the
# handled set. Fail-closed: unknown carriers of the version refuse the bump.
# ---------------------------------------------------------------------------
scan_old() {
  grep -rlF --exclude-dir=deps --exclude-dir=node_modules --exclude-dir=_build \
    --exclude-dir=tmp --exclude-dir=.git \
    -- "$OLD" . 2>/dev/null | sed 's{^\./{{' | sort -u
}

DRIFT="$(comm -23 <(scan_old) <(printf '%s%s\n%s\n%s\n%s\n%s\n%s\n' "$TEXT_FILES" "$GOLDEN_RUNTIME" "$GOLDEN_DIGEST" "$GOLDEN_JS" "$GOLDEN_JS_V2" "$GOLDEN_IR_CODEC" "$GOLDEN_ARTIFACT" | sort -u))"
if [ -n "$DRIFT" ]; then
  echo "BUMP_FAIL: unhandled drift — '$OLD' appears outside the handled set:" >&2
  printf '  %s\n' $DRIFT >&2
  echo "Extend TEXT_FILES (or the generator) in the same change; refusing to bump." >&2
  exit 1
fi

# Every handled text file must still carry the old version at least once;
# a zero count means the file shape drifted from this mechanism.
for f in $TEXT_FILES; do
  [ -f "$f" ] || die "handled file missing: $f"
  [ "$(count_of "$f" "$OLD")" -ge 1 ] || die "handled file $f contains no '$OLD' (shape drift; update this script)"
done

# ---------------------------------------------------------------------------
# Generator: recomputes the three computed-golden families through the REAL
# digest pipeline. It first re-derives every CURRENT golden at the OLD
# version (self-proof); any mismatch aborts — the mechanism is never trusted
# on a tree it cannot reproduce. Emits BUMPGEN plan lines; writes no repo file.
# ---------------------------------------------------------------------------
GEN="_build/bump_version_generator.exs"
mkdir -p _build
cat > "$GEN" <<'GENERATOR_EOF'
# Generated by scripts/bump_version.sh — do not edit; regenerate by running it.
# argv: [old_version, new_version]. Prints BUMPGEN lines; halts on any
# self-proof mismatch (exit 1).
defmodule BumpGen do
  @moduledoc false
  alias Ash.Info.Manifest
  alias Ash.Info.Manifest.{Action, Entrypoint}
  alias AshSurface.IR

  def proof!(fun, msg) do
    unless fun.() do
      IO.puts(:stderr, "BUMPGEN_SELFPROOF_FAIL: " <> msg)
      System.halt(1)
    end
  end

  def sha256(bin), do: bin |> then(&:crypto.hash(:sha256, &1)) |> Base.encode16(case: :lower)

  # Mirrors AshSurface.canonical_term/1 (frozen law, digest_test.exs moduledoc):
  # maps -> key-stringified 2-tuple lists sorted by key (byte order),
  # lists -> element-wise, other terms pass through.
  def canon(map) when is_map(map),
    do: map |> Enum.map(fn {k, v} -> {to_string(k), canon(v)} end) |> Enum.sort_by(&elem(&1, 0))

  def canon(list) when is_list(list), do: Enum.map(list, &canon/1)
  def canon(other), do: other

  def json_digest(json),
    do: json |> Jason.decode!() |> canon() |> then(&:erlang.term_to_binary/1) |> sha256()

  defp ep(resource, name, type, opts \\ []),
    do: %Entrypoint{
      resource: resource,
      action: struct!(Action, Keyword.merge([name: name, type: type, custom: %{}], opts))
    }

  defp manifest(entrypoints), do: %Manifest{entrypoints: entrypoints}

  # Mirror of AshSurface.DigestTest.golden_fixtures/0, guarded by self-proof:
  # if the test's fixtures change, this mirror stops reproducing @golden and
  # the bump refuses (update this mirror in the same change).
  def digest_test_fixtures do
    large_profile = Map.new(1..40, fn i -> {"opt" <> String.pad_leading(Integer.to_string(i), 2, "0"), i} end)

    [
      {:minimal_read, manifest([ep(AshSurface.DigestPost, :read, :read)]), %{}},
      {:two_actions,
       manifest([ep(AshSurface.DigestPost, :read, :read), ep(AshSurface.DigestPost, :record, :create)]), %{}},
      {:profiled_action,
       manifest([ep(AshSurface.DigestLedger, :record, :create, description: "Records an externally witnessed milestone")]),
       %{audience: :public, actions: %{"AshSurface.DigestLedger#record" => %{receiptRequired: false, evidenceRequired: true}}}},
      {:transport_metadata,
       manifest([ep(AshSurface.DigestPost, :list, :read, description: "Lists digests v1")]),
       %{audience: :internal, transports: [:http, :phoenix_channel], flags: %{verify_receipts: true}}},
      {:large_map_profile,
       manifest([ep(AshSurface.DigestLedger, :read, :read), ep(AshSurface.DigestLedger, :submit, :create, description: "Submits for receipt")]),
       Map.merge(large_profile, %{"actions" => %{"AshSurface.DigestLedger#submit" => %{"possibleRefusals" => ["REFUSED_NO_AUTHORITY"]}}})}
    ]
  end

  # JS single-quoted-string unescape for the contractJson fixtures: \\ \' \"
  # \n \t \r are processed left-to-right (Regex.replace pairs escapes), any
  # other byte passes through. Self-proof against the pinned digest refuses
  # the bump if this ever drifts from JavaScript's semantics.
  def js_unescape(raw) do
    Regex.replace(~r/\\(['"\\ntr])/, raw, fn _, c ->
      case c do
        "n" -> "\n"
        "t" -> "\t"
        "r" -> "\r"
        other -> other
      end
    end)
  end

  # Mirror of test/ash_surface/ir_codec_test.exs canonical_maps/0 (the
  # @golden digest preimages), guarded by self-proof: if the test's fixtures
  # change, this mirror stops reproducing @golden and the bump refuses
  # (update this mirror in the same change). The version participates via
  # identity; it is parameterized so the same mirror derives the OLD
  # (self-proof) and NEW (re-freeze) digests through the real Codec pipeline.
  def ir_codec_fixtures(v) do
    large_profile = Map.new(1..40, fn i -> {"opt" <> String.pad_leading(Integer.to_string(i), 2, "0"), i} end)

    [
      identity_only: %{
        "actions" => nil,
        "identity" => %{"surfaceSchemaVersion" => v, "generatorIdentity" => "ash_surface:v" <> v},
        "profile" => nil,
        "resources" => nil,
        "transports" => nil
      },
      full_surface: %{
        "actions" => %{
          "entries" => [
            %{"id" => "AshSurface.IrPost#read", "authorityBoundary" => "OBSERVE", "doAuthority" => false},
            %{"id" => "AshSurface.IrLedger#record", "authorityBoundary" => "DO", "doAuthority" => true}
          ]
        },
        "identity" => %{"surfaceSchemaVersion" => v, "generatorIdentity" => "ash_surface:v" <> v, "manifestDigest" => "deadbeef"},
        "profile" => %{"audience" => "internal", "flags" => %{"verifyReceipts" => true}},
        "resources" => %{"AshSurface.IrPost" => %{"attributes" => ["id", "body"]}},
        "transports" => %{"declared" => ["http", "phoenix_channel"], "preferred" => "http"}
      },
      sparse: %{
        "actions" => %{"entries" => [%{"id" => "AshSurface.IrPost#read", "authorityBoundary" => "OBSERVE"}]},
        "identity" => %{"surfaceSchemaVersion" => v},
        "profile" => nil,
        "resources" => nil,
        "transports" => nil
      },
      large_profile: %{
        "actions" => nil,
        "identity" => %{"surfaceSchemaVersion" => v},
        "profile" => large_profile,
        "resources" => nil,
        "transports" => nil
      },
      refusal_actions: %{
        "actions" => %{
          "entries" => [
            %{"id" => "AshSurface.IrLedger#submit", "possibleRefusals" => ["REFUSED_NO_AUTHORITY", "REFUSED_UNKNOWN_REVERSIBILITY"]},
            %{"id" => "AshSurface.IrLedger#read", "possibleRefusals" => []}
          ]
        },
        "identity" => %{"surfaceSchemaVersion" => v, "generatorIdentity" => "ash_surface:v" <> v},
        "profile" => %{"audience" => "public"},
        "resources" => nil,
        "transports" => %{"declared" => ["http"]}
      }
    ]
  end

  # Mirror of test/js/ir_projector_deep.test.mjs IR_ACTIONS — the v18 fixture
  # IR reconstructed as raw AshSurface.IR structs that Projector.IREntry
  # normalizes into the frozen entries. Self-proof: Projectors.JS over this
  # mirror must reproduce FROZEN_SHA256 byte-for-byte, else the bump refuses.
  defp fixture_ir(resource, action, action_type, opts \\ []) do
    %IR{
      ash: %IR.Ash{
        resource: resource,
        action: action,
        action_type: action_type,
        inputs: [],
        outputs: [],
        policies: Keyword.get(opts, :policies, [])
      },
      semantic: %IR.Semantic{capability_iri: Keyword.get(opts, :capability_iri)},
      capability: %IR.Capability{receipt_required: Keyword.get(opts, :receipt_required, false)},
      presentation: %IR.Presentation{label: Keyword.get(opts, :label)},
      schema: %IR.Schema{zod: Keyword.get(opts, :zod)}
    }
  end

  def artifact_fixture_irs do
    [
      fixture_ir("Member", :deactivate, :destroy),
      fixture_ir("Member", :profile, :read, label: "Member profile"),
      fixture_ir("Todo", :create, :create,
        policies: [%{"authorityBoundary" => "DO"}],
        receipt_required: true,
        capability_iri: "cap:todo.write",
        label: "Create todo",
        zod: "z.object({\n  title: z.string().min(1),\n  due_on: z.string().optional()\n})"
      ),
      fixture_ir("Todo", :list, :read,
        policies: [%{"authorityBoundary" => "OBSERVE"}],
        zod: "z.object({\n  status: z.enum([\"open\", \"done\"]).optional()\n})"
      )
    ]
  end
end

[old_v, new_v] = System.argv()
BumpGen.proof!(fn -> byte_size(old_v) > 0 and byte_size(new_v) > 0 end, "argv sanity")

# --- 1. RUNTIME_SHA (t09): golden SHA-256 over the shipped runtime file ----
rt = File.read!("priv/static/ash_surface_runtime.mjs")
[pinned_rt] = Regex.run(~r/@golden_runtime_sha256\s+"([0-9a-f]{64})"/, File.read!("test/ash_surface/runtime_source_test.exs"), capture: :all_but_first)
BumpGen.proof!(fn -> BumpGen.sha256(rt) == pinned_rt end, "runtime_source_test golden does not match the on-disk runtime file")
new_rt = String.replace(rt, old_v, new_v)
BumpGen.proof!(fn -> new_rt != rt end, "runtime file carries no old version")
IO.puts("BUMPGEN\tRUNTIME_SHA\truntime_sha256\t#{pinned_rt}\t#{BumpGen.sha256(new_rt)}")

# --- 2. CONTRACT_DIGEST: 5 frozen digests over the full contract -----------
golden_src = File.read!("test/ash_surface/digest_test.exs")
pins =
  Regex.scan(~r/(minimal_read|two_actions|profiled_action|transport_metadata|large_map_profile):\s*"([0-9a-f]{64})"/, golden_src)
  |> Map.new(fn [_, name, hex] -> {String.to_atom(name), hex} end)
BumpGen.proof!(fn -> map_size(pins) == 5 end, "expected 5 @golden pins in digest_test.exs, found #{map_size(pins)}")

for {name, m, profile} <- BumpGen.digest_test_fixtures() do
  {:ok, surface} = AshSurface.from_manifest(m, profile: profile)
  json = Jason.encode!(surface.contract)
  # Self-proof A: the JSON round-trip pipeline reproduces the real digest/1.
  BumpGen.proof!(fn -> BumpGen.json_digest(json) == surface.digest end, "#{name}: JSON round-trip digest != surface.digest")
  # Self-proof B: the fixture mirror reproduces the frozen golden at OLD.
  pin = Map.fetch!(pins, name)
  BumpGen.proof!(fn -> surface.digest == pin end, "#{name}: mirrored fixture digest #{surface.digest} != frozen golden #{pin}")
  new_digest = BumpGen.json_digest(String.replace(json, old_v, new_v))
  BumpGen.proof!(fn -> new_digest != pin end, "#{name}: digest did not change across the bump")
  IO.puts("BUMPGEN\tCONTRACT_DIGEST\t#{name}\t#{pin}\t#{new_digest}")
end

# --- 3. JS_DIGEST: 3 elixirDigest pins over embedded contractJson fixtures -
js_src = File.read!("test/js/digest_cross_language.test.mjs")
triples =
  Regex.scan(~r/name:\s*"([^"]+)",\s*elixirDigest:\s*"([0-9a-f]{64})",\s*contractJson:\s*'([^']+)'/s, js_src)
  |> Enum.map(fn [_, name, hex, json] -> {name, hex, json} end)
BumpGen.proof!(fn -> length(triples) == 3 end, "expected 3 elixirDigest goldens in digest_cross_language.test.mjs, found #{length(triples)}")

for {name, pin, json} <- triples do
  BumpGen.proof!(fn -> BumpGen.json_digest(json) == pin end, "#{name}: embedded contractJson digest != pinned elixirDigest")
  new_digest = BumpGen.json_digest(String.replace(json, old_v, new_v))
  BumpGen.proof!(fn -> new_digest != pin end, "#{name}: JS digest did not change across the bump")
  IO.puts("BUMPGEN\tJS_DIGEST\t#{name}\t#{pin}\t#{new_digest}")
end
GENERATOR_EOF

if ! GEN_OUT="$(MIX_ENV=test mix run "$GEN" "$OLD" "$NEW" 2>&1 | grep '^BUMPGEN[[:space:]]' || true)" \
   || [ -z "$GEN_OUT" ]; then
  echo "BUMP_FAIL: golden generator produced no plan (self-proof failed or mix errored). Rerun:" >&2
  echo "  MIX_ENV=test mix run $GEN $OLD $NEW" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Plan assembly: every old hex must be the exact, unique pin in its file.
# ---------------------------------------------------------------------------
TAB=$'\t'
PLAN_LINES=""
PLAN_HEX=""
while IFS=$'\t' read -r tag kind name old_hex new_hex; do
  [ "$tag" = "BUMPGEN" ] || continue
  case "$kind" in
    RUNTIME_SHA)     file="$GOLDEN_RUNTIME" ;;
    CONTRACT_DIGEST) file="$GOLDEN_DIGEST" ;;
    JS_DIGEST)       file="$GOLDEN_JS" ;;
    *) die "unknown golden kind from generator: $kind" ;;
  esac
  [ "$(count_of "$file" "$old_hex")" -eq 1 ] \
    || die "golden $name: expected exactly 1 occurrence of $old_hex in $file"
  PLAN_LINES="${PLAN_LINES}$(printf '  %-44s %-18s %s.. -> %s..' "$file" "$name" "${old_hex:0:12}" "${new_hex:0:12}")
"
  PLAN_HEX="${PLAN_HEX}${file}${TAB}${old_hex}${TAB}${new_hex}${TAB}${name}
"
done < <(printf '%s\n' "$GEN_OUT")
TAB=$'\t'

GATE_COUNT=3

# ---------------------------------------------------------------------------
# Print / apply
# ---------------------------------------------------------------------------
echo "BUMP PLAN: $OLD -> $NEW  (mode: $([ "$CHECK" -eq 1 ] && echo CHECK || echo APPLY))"
echo
echo "[1/3] version constants — literal '$OLD' -> '$NEW' (text rewrite)"
for f in $TEXT_FILES; do printf '  %-55s %s occurrence(s)\n' "$f" "$(count_of "$f" "$OLD")"; done
echo
echo "[2/3] computed goldens — regenerated from the real pipelines,"
echo "      self-proven by reproducing every current pin at $OLD:"
printf '%s' "$PLAN_LINES"
echo
echo "[3/3] unhandled drift scan: clean (no '$OLD' outside the handled set)"
echo

if [ "$CHECK" -eq 1 ]; then
  echo "BUMP_CHECK_OK: plan complete; nothing was modified."
  exit 0
fi

echo "APPLYING..."
for f in $TEXT_FILES; do
  perl -pi -e "s/\Q$OLD\E/$NEW/g" "$f"
done
while IFS=$'\t' read -r file old_hex new_hex name; do
  [ -n "$file" ] || continue
  perl -pi -e "s/\Q$old_hex\E/$new_hex/g" "$file"
done <<EOF2
$PLAN_HEX
EOF2

# Post-apply invariants: zero occurrences of OLD anywhere; NEW present in
# every handled text file; every old golden hex gone, new golden hex present.
if [ -n "$(scan_old)" ]; then
  echo "BUMP_FAIL: '$OLD' still present after apply:" >&2
  scan_old >&2
  exit 1
fi
for f in $TEXT_FILES; do
  grep -qF -- "$NEW" "$f" || die "post-apply: '$NEW' missing from $f"
done
while IFS=$'\t' read -r file old_hex new_hex name; do
  [ -n "$file" ] || continue
  grep -qF -- "$new_hex" "$file" || die "post-apply: new golden for $name missing from $file"
  if grep -qF -- "$old_hex" "$file"; then die "post-apply: old golden for $name still in $file"; fi
done <<EOF3
$PLAN_HEX
EOF3

echo "GATES:"
GATE_FAILED=0
while IFS= read -r gate; do
  [ -n "$gate" ] || continue
  echo "  \$ $gate"
  if eval "$gate" > /dev/null; then
    echo "  -> exit 0"
  else
    echo "BUMP_FAIL: gate failed: $gate (run it directly for diagnostics)" >&2
    GATE_FAILED=1
  fi
done <<EOF4
$(echo "$GATE_LIST" | tr '|' '\n')
EOF4
[ "$GATE_FAILED" -eq 0 ] || exit 1

echo
echo "BUMP_OK: $OLD -> $NEW — constants rewritten, goldens regenerated, gates green."
