// @generated by AshSurface.Projector.Expo (CalVer 26.9.13)
// Complete, executable client manufactured with pre-bound Zod boundary schemas.

import { createClient } from "ash_surface";
import { SCHEMAS } from "./zoela_surface.schemas.mjs";
import { ACTIONS } from "./zoela_surface.actions.mjs";

export function createZoelaClient({ contract, transports = {}, prefer = "http", reconcileEndpoint }) {
  const client = createClient({
    contract,
    transports,
    prefer,
    schemas: SCHEMAS,
  });

  return Object.freeze({
    ...client,
    actionsMetadata: ACTIONS,
    async reconcile(commandId) {
      if (!reconcileEndpoint) {
        throw new Error("No reconcileEndpoint configured on client");
      }
      const res = await fetch(`${reconcileEndpoint}?commandId=${encodeURIComponent(commandId)}`);
      if (!res.ok) return { status: "STILL_UNKNOWN" };
      return await res.json();
    }
  });
}
