// @generated by AshSurface.Projector.Expo (CalVer 26.9.13)
// Read-only realtime observation and event projection layer.

import { z } from "zod";

export const eventProjectionSchema = z.object({
  eventId: z.string().min(1),
  sequence: z.number().int().nonnegative(),
  subjectRef: z.string().min(1),
  eventType: z.string().min(1),
  stateDigest: z.string().min(1),
  evidenceRef: z.string().optional(),
  receiptRef: z.string().optional(),
  occurredAt: z.string().min(1),
  authorityBoundary: z.literal("OBSERVE").default("OBSERVE"),
}).passthrough();

export function parseEvent(raw) {
  return eventProjectionSchema.parse(raw);
}
