defmodule AshSurface.DigestParityFixtureTest do
  @moduledoc """
  Guard for the cross-language digest parity fixture artifact
  (chicago-digest-parity-051).

  The on-disk file `test/js/fixtures/digest_cross_language_fixtures.json` is
  a byte-frozen projection of the REAL digest pipeline: it is generated by
  `AshSurface.DigestParityFixtures` driving `AshSurface.from_manifest/2`,
  `AshSurface.Event.create/4`, `AshSurface.Observation.create/3`,
  `AshSurface.IR.Codec.from_map/1`, and `AshSurface.CanonicalJSON.sha256_hex/1`
  in this exact tree. The JavaScript parity suite
  (`test/js/digest_cross_language_v3.test.mjs`) reads exactly those committed
  bytes and recomputes every digest with its JS twins.

  What this guard pins, state-based:

    * the on-disk bytes equal a fresh real-pipeline encoding — any upstream
      drift in a digest law (manifest serialization, canonical term, canonical
      JSON, ETF input shapes) breaks this test BEFORE the JS suite can drift
      silently;
    * the document carries all five parity tables with their exact rows;
    * every golden is 64-hex lowercase and content ids derive from their
      digest (`ev_`/`obs_` + first 32 hex chars);
    * order-twin rows agree (canonical sort erases insertion order) while
      distinct-content rows disagree.
  """

  use ExUnit.Case, async: true

  alias AshSurface.DigestParityFixtures

  @hex64 ~r/^[0-9a-f]{64}$/

  defp on_disk_bytes do
    File.read!(Path.expand(DigestParityFixtures.output_path()))
  end

  defp parsed do
    document = Jason.decode!(on_disk_bytes())
    assert %{"generator" => _, "lawVersion" => "26.9.17", "tables" => tables} = document
    tables
  end

  test "on-disk fixture bytes are exactly the fresh real-pipeline encoding" do
    assert on_disk_bytes() == DigestParityFixtures.encode()
  end

  test "the document carries all five parity tables with the frozen rows" do
    tables = parsed()

    assert %{
             "contract" => contract,
             "event" => events,
             "observation" => observations,
             "ir" => irs,
             "receipt" => receipts
           } = tables

    assert [%{"name" => "C1 " <> _, "elixirDigest" => _, "contract" => %{"surface" => _}} | _] =
             contract

    assert length(contract) == 2
    assert length(events) == 3
    assert length(observations) == 3
    assert length(irs) == 3
    assert length(receipts) == 3
  end

  test "every golden is 64-hex lowercase and content ids derive from the digest" do
    tables = parsed()

    for %{"elixirDigest" => digest} <- tables["contract"] do
      assert digest =~ @hex64
    end

    for %{"elixirStateDigest" => digest, "elixirEventId" => id} <- tables["event"] do
      assert digest =~ @hex64
      assert id == "ev_" <> binary_part(digest, 0, 16)
    end

    for %{"elixirStateDigest" => digest, "elixirObservationId" => id} <- tables["observation"] do
      assert digest =~ @hex64
      assert id == "obs_" <> binary_part(digest, 0, 16)
    end

    for %{"elixirDigest" => digest} <- tables["ir"] do
      assert digest =~ @hex64
    end

    for %{"elixirReceiptHash" => digest} <- tables["receipt"] do
      assert digest =~ @hex64
    end
  end

  test "order-twin rows agree; distinct-content rows disagree" do
    tables = parsed()

    for {table, digest_key} <- [
          {"event", "elixirStateDigest"},
          {"observation", "elixirStateDigest"},
          {"receipt", "elixirReceiptHash"}
        ] do
      [twin_a, twin_b, distinct] = tables[table]
      a = Map.fetch!(twin_a, digest_key)
      b = Map.fetch!(twin_b, digest_key)
      d = Map.fetch!(distinct, digest_key)

      assert a == b,
             "#{table}: order-twin rows must share one digest, got: #{inspect([a, b])}"

      assert d != a,
             "#{table}: distinct-content row must not collide with the twins, got: #{d}"
    end

    # Contract and IR rows are all distinct content: all digests pairwise distinct.
    for {table, digest_key} <- [{"contract", "elixirDigest"}, {"ir", "elixirDigest"}] do
      digests = Enum.map(tables[table], &Map.fetch!(&1, digest_key))
      assert length(Enum.uniq(digests)) == length(digests), "#{table}: digests must be distinct"
    end
  end
end
