defmodule AshSurface.FromManifestTest.RealPost do
  @moduledoc """
  A real Ash resource consumed through `Ash.Info.Manifest.generate/1`.

  The ETS data layer keeps this state-based suite free of any database,
  environment, or network dependency. `:update` and `:destroy` are declared on
  the resource but never exposed as manifest entrypoints, so they exercise the
  exact public action set boundary.
  """

  use Ash.Resource,
    domain: nil,
    data_layer: Ash.DataLayer.Ets

  attributes do
    uuid_primary_key(:id)
    attribute(:title, :string, public?: true, allow_nil?: false)
  end

  actions do
    defaults([:read, :create, :update, :destroy])
  end
end

defmodule AshSurface.FromManifestTest do
  @moduledoc """
  Chicago-style, state-based tests for `AshSurface.from_manifest/2`.

  Manifests are real: either generated by `Ash.Info.Manifest.generate/1` from
  `RealPost` above, or literal structs matching that module's published
  contract. The invariants under test:

    * projection metadata is placed only under `custom.ash_surface`, beside -
      never replacing - foreign extension custom data;
    * the exact public action set of the manifest is the only admissible
      action profile key space;
    * invalid projection metadata is refused with typed errors, and transport
      kind validation stays owned by `AshSurface.Transport` (a transport facet
      is metadata to `from_manifest/2`, never action identity);
    * the decorated manifest round-trips through
      `Ash.Info.Manifest.JsonSerializer` while `custom.ash_surface` metadata
      stays owned by the surface envelope instead of leaking into serialized
      Ash semantics.
  """

  use ExUnit.Case, async: true

  alias Ash.Info.Manifest
  alias Ash.Info.Manifest.{Action, Entrypoint, JsonSerializer}
  alias AshSurface.Transport

  @resource AshSurface.FromManifestTest.RealPost
  @read_id "AshSurface.FromManifestTest.RealPost#read"
  @create_id "AshSurface.FromManifestTest.RealPost#create"

  defp literal_manifest do
    %Manifest{
      custom: %{vendor: %{owned: true}},
      entrypoints: [
        %Entrypoint{
          resource: @resource,
          action: %Action{name: :read, type: :read, custom: %{other: %{kept: 1}}}
        },
        %Entrypoint{
          resource: @resource,
          action: %Action{name: :create, type: :create, custom: %{}}
        }
      ]
    }
  end

  defp generated_manifest do
    assert {:ok, manifest} =
             Manifest.generate(
               otp_app: :ash_surface,
               action_entrypoints: [
                 {@resource, :read},
                 {@resource, :create}
               ]
             )

    manifest
  end

  defp entrypoint(manifest, action_name) do
    Enum.find(manifest.entrypoints, &(&1.action.name == action_name))
  end

  describe "metadata placement under custom.ash_surface" do
    test "decorates only custom.ash_surface and preserves foreign custom keys" do
      profile = %{
        audience: :public,
        actions: %{@read_id => %{consumer: :web}}
      }

      assert {:ok, surface} = AshSurface.from_manifest(literal_manifest(), profile: profile)

      assert surface.manifest.custom == %{
               vendor: %{owned: true},
               ash_surface: %{
                 "schemaVersion" => AshSurface.schema_version(),
                 "profile" => %{"audience" => "public"}
               }
             }

      assert entrypoint(surface.manifest, :read).action.custom == %{
               other: %{kept: 1},
               ash_surface: %{"id" => @read_id, "profile" => %{"consumer" => "web"}}
             }

      assert entrypoint(surface.manifest, :create).action.custom == %{
               ash_surface: %{"id" => @create_id, "profile" => %{}}
             }
    end

    test "leaves the caller's manifest state untouched" do
      manifest = literal_manifest()

      assert {:ok, _surface} =
               AshSurface.from_manifest(manifest, profile: %{actions: %{@read_id => %{}}})

      assert manifest.custom == %{vendor: %{owned: true}}
      assert manifest.custom[:ash_surface] == nil

      assert Enum.all?(manifest.entrypoints, &(Map.get(&1.action.custom, :ash_surface) == nil))
    end
  end

  describe "exact public action set" do
    test "action_ids are exactly the manifest's public entrypoints" do
      assert {:ok, surface} =
               AshSurface.from_manifest(generated_manifest(),
                 profile: %{actions: %{@read_id => %{}, @create_id => %{}}}
               )

      assert surface.action_ids == [@create_id, @read_id]

      assert surface.manifest.entrypoints
             |> Enum.map(& &1.action.custom.ash_surface["id"])
             |> Enum.sort() == surface.action_ids
    end

    test "action profiles outside the exact public action set are refused with sorted unknowns" do
      # :update and :destroy exist on the resource but are not public entrypoints.
      assert {:error, {:unknown_action_profile, unknown}} =
               AshSurface.from_manifest(generated_manifest(),
                 profile: %{
                   actions: %{
                     "AshSurface.FromManifestTest.RealPost#update" => %{},
                     "AshSurface.FromManifestTest.RealPost#destroy" => %{}
                   }
                 }
               )

      assert Enum.sort(unknown) == [
               "AshSurface.FromManifestTest.RealPost#destroy",
               "AshSurface.FromManifestTest.RealPost#update"
             ]

      assert {:error, {:unknown_action_profile, ["Missing#action"]}} =
               AshSurface.from_manifest(literal_manifest(),
                 profile: %{actions: %{"Missing#action" => %{consumer: :web}}}
               )
    end
  end

  describe "typed rejections of invalid projection metadata" do
    test "non-map profile and non-map actions are refused" do
      manifest = literal_manifest()

      assert {:error, :profile_must_be_a_map} =
               AshSurface.from_manifest(manifest, profile: [audience: "public"])

      assert {:error, :profile_actions_must_be_a_map} =
               AshSurface.from_manifest(manifest, profile: %{actions: [@read_id]})
    end

    test "non-serializable profile values and keys are refused with the offending term" do
      manifest = literal_manifest()

      assert {:error, {:profile_value_not_serializable, pid}} =
               AshSurface.from_manifest(manifest, profile: %{watcher: self()})

      assert is_pid(pid)

      assert {:error, {:profile_key_not_serializable, {1, :x}}} =
               AshSurface.from_manifest(manifest, profile: %{{1, :x} => 1})
    end
  end

  test "transport kinds and offline classes are profile data; typed transport refusal belongs to Transport" do
    profile = %{
      actions: %{@read_id => %{transports: [:grpc], offlineClass: :bad_class}}
    }

    # from_manifest/2 owns placement and the public action set, not transport
    # kind checking: a wrong transport kind must not become a second application
    # model here. It is admitted as data and typed-refused at the owning module.
    assert {:ok, surface} = AshSurface.from_manifest(generated_manifest(), profile: profile)

    assert entrypoint(surface.manifest, :read).action.custom.ash_surface["profile"] == %{
             "transports" => ["grpc"],
             "offlineClass" => "bad_class"
           }

    assert {:error, {:unknown_transport, [:grpc]}} = Transport.select([:grpc], [:grpc])
  end

  # chicago-ontology-producer-039: re-adjudication of 015's
  # keep-typed-optional-no-producer on the post-F4 tree. The honest-producer
  # side is REFUSED by law and the absence is ENFORCED by the rows below:
  #
  #   * contract/2 receives a Manifest + profile only — no ontology and no
  #     release identity crosses the surface boundary (Ash's serializer omits
  #     extension custom data and entrypoint config);
  #   * F4 (MXEpisode.compose/1) binds surface.digest and the subject
  #     repo/head at the EPISODE layer from operator-supplied inputs — it
  #     adds no surface input, so it cannot feed a contract-layer producer;
  #   * surface.digest -> ontologyDigest is circular: Surface.digest digests
  #     the very contract that would carry the field;
  #   * generator identity -> applicationReleaseIdentity mislabels
  #     provenance: generatorIdentity already has its own field, and the
  #     witnessed upstream value (the F5 fixture's "ash-surface-wt/v43@282f3ca")
  #     is a generation-time repo/head fact, not derivable from the manifest;
  #   * environment reads (repo ontology.ttl, Mix version, git head) would
  #     make Surface.digest environment-dependent, breaking the frozen golden
  #     determinism law pinned in AshSurface.DigestTest.
  #
  # Presence of either field in contract/2 output is therefore RED. This
  # suite is the enforcement anchor; the typed optional schema rows in
  # priv/static/ash_surface_runtime.mjs keep admitting witnessed upstream
  # values (the schema accepts, the Elixir producer never emits).
  @absence_law_fields ["ontologyDigest", "applicationReleaseIdentity"]

  @lawful_envelope_keys ~w(ashManifestSchemaVersion generatorIdentity manifest
    manifestDigest marketplaceIdentity surface surfaceSchemaVersion)

  describe "enforced absence law: ontologyDigest / applicationReleaseIdentity" do
    test "contract/2 emits neither delegated-identity field (presence is RED by law)" do
      assert {:ok, surface} = AshSurface.from_manifest(generated_manifest(), profile: %{})

      for field <- @absence_law_fields do
        refute Map.has_key?(surface.contract, field),
               "#{field} appeared in contract/2 output — the surface boundary " <>
                 "receives no ontology or release input; emitting it would " <>
                 "fabricate delegated provenance"
      end

      # The envelope is a closed seven-key projection; this pin makes ANY
      # added identity field red until the law itself is consciously changed.
      assert surface.contract |> Map.keys() |> Enum.sort() == Enum.sort(@lawful_envelope_keys)
    end

    test "even the maximal delegated state carries no ontology or release identity" do
      # All four delegated facts admitted through the action profile (the
      # custom.ash_surface IR section): they surface where delegation puts
      # them — per action in the surface envelope — and nowhere else.
      profile = %{
        actions: %{
          @read_id => %{
            "semanticId" => "zoe:RealPostRead",
            "authorityBoundary" => "OBSERVE",
            "doAuthority" => false,
            "receiptRequired" => true
          }
        }
      }

      assert {:ok, surface} = AshSurface.from_manifest(generated_manifest(), profile: profile)

      action = Enum.find(surface.contract["surface"]["actions"], &(&1["id"] == @read_id))
      assert action["semanticId"] == "zoe:RealPostRead"
      assert action["authorityBoundary"] == "OBSERVE"
      assert action["doAuthority"] == false
      assert action["receiptRequired"] == true

      for field <- @absence_law_fields do
        refute Map.has_key?(surface.contract, field)
      end
    end

    test "consumer profile data may repeat the names; the envelope producer still emits neither" do
      profile = %{
        ontologyDigest: "consumer-profile-data",
        applicationReleaseIdentity: "consumer@1"
      }

      assert {:ok, surface} = AshSurface.from_manifest(literal_manifest(), profile: profile)

      assert surface.contract["surface"]["profile"]["ontologyDigest"] == "consumer-profile-data"
      assert surface.contract["surface"]["profile"]["applicationReleaseIdentity"] == "consumer@1"

      # The law binds the envelope producer's top-level output, not consumer
      # profile data carried below surface.profile.
      for field <- @absence_law_fields do
        refute Map.has_key?(surface.contract, field)
      end
    end
  end

  describe "Ash.Info.Manifest.JsonSerializer round-trip" do
    test "the decorated manifest serializes and decodes to its canonical map" do
      assert {:ok, surface} =
               AshSurface.from_manifest(generated_manifest(), profile: %{audience: :public})

      assert {:ok, json} = JsonSerializer.to_json(surface.manifest)

      decoded = Jason.decode!(json)

      assert decoded == JsonSerializer.to_map(surface.manifest)
      assert surface.contract["manifest"] == decoded
    end

    test "custom.ash_surface metadata stays owned by the surface envelope, not serialized semantics" do
      profile = %{actions: %{@read_id => %{consumer: :web}}}

      assert {:ok, surface} = AshSurface.from_manifest(generated_manifest(), profile: profile)

      assert {:ok, json} = JsonSerializer.to_json(surface.manifest)

      # Ash's serializer intentionally omits extension custom data; the surface
      # envelope is the only carrier of ash_surface projection metadata.
      refute String.contains?(json, "ash_surface")

      envelope_ids =
        surface.contract["surface"]["actions"] |> Enum.map(& &1["id"]) |> Enum.sort()

      assert envelope_ids == surface.action_ids
    end
  end
end
