defmodule AshSurface.VersionSyncTest do
  @moduledoc """
  Version law: the JavaScript runtime's SURFACE_RUNTIME_VERSION, the mix.exs
  @version, and the package.json version (when set) must all agree with the
  version exposed by `AshSurface.schema_version/0`. Every projector CalVer
  header under lib/ash_surface/projectors/ must equal it too, and the
  projectors must emit it — a projector header diverging from the surface
  version fails closed here (and in scripts/bump_version.sh, whose OLD-value
  drift scan cannot see a stale header because its value != OLD).

  The golden below is the pinned truth for this checkout; a failure here means
  a version was bumped without its counterparts (or vice versa).
  """

  use ExUnit.Case, async: true

  @golden_version "26.9.17"
  @runtime_rel "priv/static/ash_surface_runtime.mjs"
  @projector_dir "lib/ash_surface/projectors"

  # Projectors known to carry a CalVer header. The scan below is open-set
  # (every *.ex in the dir is scanned, so a NEW header cannot hide); this pin
  # makes a silently REMOVED header fail too.
  @calver_carriers ["aria.ex", "js.ex"]

  describe "version law across the surface, the runtime, and the manifests" do
    test "AshSurface.schema_version/0 matches the pinned golden version" do
      assert AshSurface.schema_version() == @golden_version
    end

    test "the JavaScript runtime SURFACE_RUNTIME_VERSION matches the Elixir surface version" do
      assert {:ok, source} = AshSurface.runtime_source(),
             "runtime adapter not readable at #{@runtime_rel} via AshSurface.runtime_source/0"

      assert runtime_constant(source) == AshSurface.schema_version(),
             "SURFACE_RUNTIME_VERSION in #{@runtime_rel} drifted from AshSurface.schema_version/0"
    end

    test "mix.exs @version matches the Elixir surface version" do
      assert {:ok, mix_source} = File.read("mix.exs")

      assert mix_exs_version(mix_source) == AshSurface.schema_version(),
             "mix.exs @version drifted from AshSurface.schema_version/0"
    end

    test "package.json version, when set, matches the Elixir surface version" do
      assert {:ok, raw} = File.read("package.json")
      assert {:ok, pkg} = Jason.decode(raw)

      case Map.get(pkg, "version") do
        nil ->
          # The JS projection package is private and ships no version;
          # the convention only binds package.json when it sets one.
          :ok

        version ->
          assert version == AshSurface.schema_version(),
                 "package.json version drifted from AshSurface.schema_version/0"
      end
    end
  end

  describe "projector CalVer law: no projector header can diverge silently" do
    test "every projector CalVer header matches the Elixir surface version" do
      scanned = Path.wildcard("#{@projector_dir}/*.ex")
      refute scanned == [], "no projector files found under #{@projector_dir}"

      drifted =
        scanned
        |> Map.new(fn path ->
          versions =
            path
            |> File.read!()
            |> then(&Regex.scan(~r/@calver\s+"([^"]+)"/, &1, capture: :all_but_first))
            |> List.flatten()
            |> Enum.uniq()

          {path, versions}
        end)
        |> Map.filter(fn {_path, versions} ->
          versions != [] and versions != [AshSurface.schema_version()]
        end)

      assert drifted == %{},
             "projector CalVer headers drifted from AshSurface.schema_version/0: #{inspect(drifted)}"
    end

    test "the known CalVer carriers each still carry exactly one header" do
      for name <- @calver_carriers do
        path = Path.join(@projector_dir, name)
        assert File.exists?(path), "expected projector #{path} to exist"

        count =
          path
          |> File.read!()
          |> then(&Regex.scan(~r/@calver\s+"/, &1))
          |> length()

        assert count == 1, "expected exactly one @calver header in #{path}, found #{count}"
      end
    end

    test "the ARIA projector emits the surface version into its contract" do
      ir =
        AshSurface.IR.new(
          ash: %AshSurface.IR.Ash{resource: "Sync", action: :read, action_type: :read}
        )

      assert {:ok, contract, _meta} = AshSurface.Projectors.ARIA.project_ir(ir)

      assert contract["version"] == AshSurface.schema_version(),
             "the ARIA contract version drifted from AshSurface.schema_version/0"
    end

    test "the JS projector's artifact header carries the surface version" do
      assert {:ok, %{"ash_surface_client.mjs" => code}, _meta} =
               AshSurface.Projectors.JS.project_ir([])

      assert code =~
               ~r|// @generated by AshSurface.Projectors.JS \(CalVer #{Regex.escape(AshSurface.schema_version())}\)|,
             "the JS artifact CalVer header drifted from AshSurface.schema_version/0"
    end
  end

  defp runtime_constant(source) do
    case Regex.run(~r/export\s+const\s+SURFACE_RUNTIME_VERSION\s*=\s*"([^"]+)"/, source) do
      [_, version] -> version
      other -> flunk("SURFACE_RUNTIME_VERSION not found in #{@runtime_rel}: #{inspect(other)}")
    end
  end

  defp mix_exs_version(source) do
    case Regex.run(~r/@version\s+"([^"]+)"/, source) do
      [_, version] -> version
      other -> flunk("@version not found in mix.exs: #{inspect(other)}")
    end
  end
end
