defmodule AshSurfaceZoe.Projector.Human do
  @moduledoc """
  ZOE / DfCM human-surface projector (package `ash_surface_zoe`).

  Implements `AshSurface.Projector.IR` and emits ONLY the human-facing
  artifacts that used to ride inside `AshSurface.Projector.Expo`:

  - `{prefix}.human.mjs`: DfCM member-facing TODAY/BIBLE/LIFE/ZOE/YOU projection helpers
  - `{prefix}.demo.mjs`: deterministic human demo consumer (local playback + intent construction)

  The generic Expo artifacts (schemas, actions, events, receipts, client,
  tanstack) remain emitted by `AshSurface.Projector.Expo` in core. Both
  projectors accept the same `ash_surface.surface` IR and the same `:prefix` /
  `:target_dir` options, so a consumer runs both over one surface and gets the
  union of the previous file set.

  The emitted `human.mjs` imports its Zod schemas from `"ash_surface_zoe"`
  (this package's `priv/static/ash_surface_zoe.mjs`); that module in turn
  imports `SurfaceRuntimeError` from core's `"ash_surface"` runtime.
  """

  @behaviour AshSurface.Projector.IR

  @doc """
  Projects a surface carried as `ash_surface.surface` IR into the human/demo
  artifact pair. The surface is recovered (and its digest re-verified) with
  `AshSurface.Projector.IR.to_surface/1`; other IR kinds are refused with the
  same typed errors as core projectors.
  """
  @impl true
  @spec project_ir(AshSurface.Projector.IR.input(), keyword()) ::
          {:ok, %{optional(String.t()) => String.t()}, map()} | {:error, term()}
  def project_ir(irs, opts \\ []) do
    with {:ok, %AshSurface.Surface{}} <- AshSurface.Projector.IR.to_surface(irs) do
      prefix = Keyword.get(opts, :prefix, "zoela_surface")
      target_dir = Keyword.get(opts, :target_dir)

      artifacts = %{
        "#{prefix}.human.mjs" => render_human(),
        "#{prefix}.demo.mjs" => render_demo(prefix)
      }

      if target_dir do
        File.mkdir_p!(target_dir)

        Enum.each(artifacts, fn {filename, content} ->
          File.write!(Path.join(target_dir, filename), content)
        end)
      end

      {:ok, artifacts, %{prefix: prefix, human_surface: true}}
    end
  end

  defp render_human do
    """
    // @generated by AshSurfaceZoe.Projector.Human (CalVer 26.9.21)
    // Human projection helpers. This artifact presents choices and commitments,
    // but cannot acquire DO authority or dispatch a consequence.

    import {
      humanSurfaceSchema,
      parseHumanSurfaceProjection,
    } from "ash_surface_zoe";

    export const HUMAN_AREAS = Object.freeze(["TODAY", "BIBLE", "LIFE", "ZOE", "YOU"]);
    export const HUMAN_GRAMMAR = Object.freeze([
      "SEE",
      "UNDERSTAND",
      "EXPLORE",
      "CHOOSE",
      "ACT",
      "LEARN",
    ]);

    export function parseHumanSurface(raw) {
      return parseHumanSurfaceProjection(raw);
    }

    export function getArea(raw, areaName) {
      const surface = humanSurfaceSchema.parse(raw);
      if (!HUMAN_AREAS.includes(areaName)) {
        throw new TypeError("Unknown human area: " + String(areaName));
      }

      return surface[areaName.toLowerCase()];
    }

    export function preservedPossibilities(raw) {
      const surface = humanSurfaceSchema.parse(raw);

      return surface.possibilitySets.flatMap((set) =>
        set.possibilities.filter(
          (option) => option.status === "PRESERVED" || option.status === "CANDIDATE",
        ),
      );
    }

    export function explanationsFor(raw, subjectRef) {
      const surface = humanSurfaceSchema.parse(raw);
      return surface.explanations.filter((explanation) => explanation.subjectRef === subjectRef);
    }

    export function personalizationContext(raw, contextId) {
      const surface = humanSurfaceSchema.parse(raw);
      return surface.personalizationContexts.find((item) => item.contextId === contextId) ?? null;
    }

    export function manufactureTraceFor(raw, artifactRef) {
      const surface = humanSurfaceSchema.parse(raw);
      return surface.manufactureTraces.find((item) => item.artifactRef === artifactRef) ?? null;
    }

    export function devotionalQueue(raw, episodeId) {
      const surface = humanSurfaceSchema.parse(raw);
      const episode = surface.devotionalEpisodes.find((item) => item.episodeId === episodeId);
      if (!episode) return null;

      return Object.freeze({
        episodeId,
        title: episode.title,
        continuousPlay: episode.continuousPlay,
        playbackPolicy: episode.playbackPolicy,
        durationSeconds: episode.durationSeconds,
        segments: Object.freeze([...episode.segments].sort((a, b) => a.position - b.position)),
      });
    }

    export function commitmentPreview(raw, actionRef) {
      const surface = humanSurfaceSchema.parse(raw);
      const boundary = surface.commitmentBoundaries.find((item) => item.actionRef === actionRef);
      if (!boundary) return null;

      return Object.freeze({
        boundaryId: boundary.boundaryId,
        actionRef: boundary.actionRef,
        consequenceSummary: boundary.consequenceSummary,
        externalEffects: Object.freeze([...boundary.externalEffects]),
        reversibility: boundary.reversibility,
        confirmationState: boundary.confirmationState,
        confirmationRequired: boundary.confirmationRequired,
        nextHandoff: boundary.nextHandoff,
        authorityCeiling: boundary.authorityCeiling,
        doAuthority: boundary.doAuthority,
      });
    }

    export function journeyTimeline(raw) {
      const surface = humanSurfaceSchema.parse(raw);

      return Object.freeze(
        surface.journeys
          .flatMap((journey) =>
            journey.entries.map((entry) => ({
              ...entry,
              journeyId: journey.journeyId,
              privacyScope: journey.privacyScope,
            })),
          )
          .sort((left, right) => left.occurredAt.localeCompare(right.occurredAt)),
      );
    }

    export function assertNoDoAuthority(raw) {
      const surface = humanSurfaceSchema.parse(raw);

      if (surface.doAuthority !== false || surface.authorityBoundary !== "OBSERVE") {
        throw new Error("Human surface attempted to exceed OBSERVE authority");
      }

      for (const set of surface.possibilitySets) {
        for (const option of set.possibilities) {
          if (option.doAuthority !== false || option.authorityCeiling === "DO") {
            throw new Error("Possibility " + option.possibilityId + " attempted DO authority");
          }
        }
      }

      for (const context of surface.personalizationContexts) {
        if (
          context.doAuthority !== false ||
          context.authorityBoundary !== "OBSERVE" ||
          context.privacyScope !== "SUBJECT_PRIVATE" ||
          context.shareScope !== "SUBJECT_ONLY"
        ) {
          throw new Error("Personalization context " + context.contextId + " violates privacy/authority");
        }
      }

      for (const trace of surface.manufactureTraces) {
        if (trace.doAuthority !== false || trace.authorityBoundary !== "OBSERVE") {
          throw new Error("Manufacture trace " + trace.traceId + " attempted authority");
        }
      }

      for (const boundary of surface.commitmentBoundaries) {
        if (
          boundary.doAuthority !== false ||
          boundary.authorityCeiling !== "CONSTRUCT" ||
          boundary.nextHandoff !== "BRCE"
        ) {
          throw new Error("Commitment boundary " + boundary.boundaryId + " bypasses BRCE");
        }
      }

      return true;
    }
    """
  end

  defp render_demo(prefix) do
    """
    // @generated by AshSurfaceZoe.Projector.Human (CalVer 26.9.21)
    // Deterministic human demo consumer. Local playback and intent construction
    // are allowed; network dispatch, provider reads, and consequence-bearing DO
    // are deliberately absent.

    import {
      parseHumanSurface,
      preservedPossibilities,
      explanationsFor,
      personalizationContext,
      manufactureTraceFor,
      devotionalQueue,
      commitmentPreview,
      journeyTimeline,
      assertNoDoAuthority,
    } from "./#{prefix}.human.mjs";

    export function buildZoeDemoViewModel(raw) {
      const surface = parseHumanSurface(raw);
      assertNoDoAuthority(surface);

      if (surface.zoe?.liveProviderReads !== false) {
        throw new Error("ZOE demo consumer requires liveProviderReads=false");
      }

      const possibilities = preservedPossibilities(surface);
      const episodeId = surface.bible?.devotionalEpisodeRefs?.[0] ?? null;
      const devotional = episodeId ? devotionalQueue(surface, episodeId) : null;
      const contextId = surface.life?.personalizationContextRefs?.[0] ?? null;
      const context = contextId ? personalizationContext(surface, contextId) : null;
      const traceRef = surface.life?.manufactureTraceRefs?.[0] ?? null;
      const trace =
        surface.manufactureTraces.find((item) => item.traceId === traceRef) ??
        surface.manufactureTraces[0] ??
        null;
      const whySubject = trace?.artifactRef ?? devotional?.episodeId ?? null;
      const explanations = whySubject ? explanationsFor(surface, whySubject) : [];
      const why = explanations[0] ?? surface.explanations[0] ?? null;
      const commitment =
        surface.commitmentBoundaries.length > 0
          ? commitmentPreview(surface, surface.commitmentBoundaries[0].actionRef)
          : null;

      return Object.freeze({
        syntheticOnly: true,
        exactSubject: surface.exactSubject,
        areas: Object.freeze([...surface.areas]),
        grammar: Object.freeze([...surface.grammar]),
        possibilities: Object.freeze([...possibilities]),
        devotional,
        whyThis: why,
        personalization: context,
        manufactureTrace: trace,
        journey: journeyTimeline(surface),
        commitment,
        authorityBoundary: surface.authorityBoundary,
        doAuthority: false,
        liveProviderReads: false,
      });
    }

    export function createContinuousDevotionalPlayer(raw, episodeId, options = {}) {
      const surface = parseHumanSurface(raw);
      assertNoDoAuthority(surface);
      const queue = devotionalQueue(surface, episodeId);

      if (!queue) throw new Error("Unknown devotional episode: " + String(episodeId));
      if (queue.continuousPlay !== true || queue.playbackPolicy !== "STRAIGHT_THROUGH") {
        throw new Error("Devotional episode is not admitted for straight-through playback");
      }

      const adapter = options.adapter ?? createTimedDemoPlaybackAdapter();
      const listeners = new Set();
      let currentHandle = null;
      let runPromise = null;
      let cancelled = false;
      let state = Object.freeze({
        status: "IDLE",
        episodeId,
        index: -1,
        segmentRef: null,
        receipt: null,
      });

      const emit = (next) => {
        state = Object.freeze({ ...state, ...next });
        for (const listener of listeners) listener(state);
      };

      async function run() {
        cancelled = false;

        for (let index = 0; index < queue.segments.length; index += 1) {
          if (cancelled) break;

          const segment = queue.segments[index];
          currentHandle = adapter.open(segment);
          if (!currentHandle || typeof currentHandle.play !== "function") {
            throw new TypeError("playback adapter must return a handle with play()");
          }

          emit({
            status: "PLAYING",
            index,
            segmentRef: segment.ref,
            receipt: null,
          });

          await currentHandle.play();
          currentHandle = null;
        }

        if (!cancelled) {
          const receipt = Object.freeze({
            kind: "LOCAL_PLAYBACK_COMPLETED",
            episodeId,
            segmentRefs: Object.freeze(queue.segments.map((segment) => segment.ref)),
            externalEffects: false,
            authorityBoundary: "OBSERVE",
            doAuthority: false,
          });

          emit({
            status: "COMPLETED",
            index: queue.segments.length - 1,
            segmentRef: queue.segments.at(-1)?.ref ?? null,
            receipt,
          });
        }

        runPromise = null;
        return state;
      }

      return Object.freeze({
        snapshot() {
          return state;
        },
        subscribe(listener) {
          if (typeof listener !== "function") throw new TypeError("listener must be a function");
          listeners.add(listener);
          listener(state);
          return () => listeners.delete(listener);
        },
        start() {
          if (!runPromise) runPromise = run();
          return runPromise;
        },
        pause() {
          if (state.status !== "PLAYING" || !currentHandle?.pause) return state;
          currentHandle.pause();
          emit({ status: "PAUSED" });
          return state;
        },
        resume() {
          if (state.status !== "PAUSED" || !currentHandle?.resume) return state;
          currentHandle.resume();
          emit({ status: "PLAYING" });
          return state;
        },
        stop() {
          cancelled = true;
          currentHandle?.stop?.();
          currentHandle = null;
          emit({ status: "STOPPED", receipt: null });
          return state;
        },
      });
    }

    export function createTimedDemoPlaybackAdapter(options = {}) {
      const millisPerSecond = options.millisPerSecond ?? 1;

      return Object.freeze({
        open(segment) {
          let remaining = Math.max(0, segment.durationSeconds * millisPerSecond);
          let timer = null;
          let startedAt = null;
          let settled = false;
          let resolveDone;

          const done = new Promise((resolve) => {
            resolveDone = resolve;
          });

          const arm = () => {
            if (settled) return;
            startedAt = Date.now();
            timer = setTimeout(() => {
              settled = true;
              timer = null;
              remaining = 0;
              resolveDone();
            }, remaining);
          };

          return Object.freeze({
            play() {
              if (!settled && timer === null) arm();
              return done;
            },
            pause() {
              if (settled || timer === null) return;
              clearTimeout(timer);
              timer = null;
              remaining = Math.max(0, remaining - (Date.now() - startedAt));
            },
            resume() {
              if (!settled && timer === null) arm();
              return done;
            },
            stop() {
              if (timer !== null) clearTimeout(timer);
              timer = null;
              if (!settled) {
                settled = true;
                resolveDone();
              }
            },
          });
        },
      });
    }

    export function createHtmlAudioAdapter(options = {}) {
      const resolveAudioRef = options.resolveAudioRef ?? ((audioRef) => audioRef);
      const audioFactory =
        options.audioFactory ??
        ((src) => {
          if (typeof Audio !== "function") {
            throw new Error("HTML Audio is unavailable; provide audioFactory");
          }
          return new Audio(src);
        });

      return Object.freeze({
        open(segment) {
          if (!segment.audioRef) {
            return createTimedDemoPlaybackAdapter({ millisPerSecond: 0 }).open(segment);
          }

          const src = resolveAudioRef(segment.audioRef, segment);
          if (!src) throw new Error("No admitted media source for " + segment.audioRef);

          const audio = audioFactory(src, segment);
          let settled = false;
          let resolveDone;
          let rejectDone;
          const done = new Promise((resolve, reject) => {
            resolveDone = resolve;
            rejectDone = reject;
          });

          const cleanup = () => {
            audio.removeEventListener?.("ended", onEnded);
            audio.removeEventListener?.("error", onError);
          };
          const onEnded = () => {
            if (settled) return;
            settled = true;
            cleanup();
            resolveDone();
          };
          const onError = (event) => {
            if (settled) return;
            settled = true;
            cleanup();
            rejectDone(event instanceof Error ? event : new Error("audio playback failed"));
          };

          audio.addEventListener?.("ended", onEnded);
          audio.addEventListener?.("error", onError);

          return Object.freeze({
            async play() {
              await audio.play();
              return done;
            },
            pause() {
              audio.pause();
            },
            async resume() {
              await audio.play();
              return done;
            },
            stop() {
              audio.pause();
              try {
                audio.currentTime = 0;
              } catch {
                // Some injected media handles expose read-only currentTime.
              }
              if (!settled) {
                settled = true;
                cleanup();
                resolveDone();
              }
            },
          });
        },
      });
    }

    export function constructBrceIntent(raw, actionRef) {
      const surface = parseHumanSurface(raw);
      assertNoDoAuthority(surface);
      const boundary = commitmentPreview(surface, actionRef);

      if (!boundary) throw new Error("No commitment boundary for " + String(actionRef));

      return Object.freeze({
        kind: "CONSTRUCT_INTENT",
        exactSubject: surface.exactSubject,
        boundaryId: boundary.boundaryId,
        actionRef: boundary.actionRef,
        consequenceSummary: boundary.consequenceSummary,
        externalEffects: Object.freeze([...boundary.externalEffects]),
        reversibility: boundary.reversibility,
        confirmationRequired: boundary.confirmationRequired,
        authorityCeiling: "CONSTRUCT",
        nextHandoff: "BRCE",
        dispatched: false,
        doAuthority: false,
      });
    }

    export function renderZoeDemoHtml(raw) {
      const view = buildZoeDemoViewModel(raw);
      const esc = escapeHtml;
      const why = view.whyThis;
      const trace = view.manufactureTrace;
      const context = view.personalization;
      const commitment = view.commitment;

      const possibilities = view.possibilities
        .map(
          (option) =>
            '<li data-testid="possibility"><strong>' +
            esc(option.label) +
            "</strong><span>" +
            esc(option.summary ?? "") +
            "</span></li>",
        )
        .join("");

      const basis = (why?.basis ?? []).map((item) => "<li>" + esc(item) + "</li>").join("");
      const caveats = (why?.caveats ?? []).map((item) => "<li>" + esc(item) + "</li>").join("");
      const journey = view.journey
        .map(
          (entry) =>
            '<li data-testid="journey-entry"><strong>' +
            esc(entry.label) +
            "</strong><span>" +
            esc(entry.occurredAt) +
            "</span></li>",
        )
        .join("");

      return [
        '<main data-testid="zoe-demo" data-authority="OBSERVE">',
        '<p data-testid="demo-ceiling">Synthetic demo · no live provider reads · no external effects</p>',
        "<h1>Today</h1>",
        '<ul data-testid="dfcm-frontier">' + possibilities + "</ul>",
        '<section data-testid="devotional"><h2>' + esc(view.devotional?.title ?? "Devotional") + "</h2>",
        '<p>Straight-through playback: ' + esc(String(view.devotional?.continuousPlay === true)) + "</p>",
        '<button data-demo-action="play">Play straight through</button>',
        '<button data-demo-action="pause">Pause</button>',
        '<button data-demo-action="resume">Resume</button>',
        '<output data-testid="playback-status">IDLE</output></section>',
        '<section data-testid="why-this"><h2>' + esc(why?.title ?? "Why this?") + "</h2>",
        "<p>" + esc(why?.summary ?? "") + "</p>",
        "<p>Claim: " + esc(why?.claimKind ?? "") + " · Evidence: " + esc(why?.evidenceState ?? "") + "</p>",
        "<p>Falsifier: " + esc(why?.falsifier ?? "") + "</p>",
        "<ul>" + basis + "</ul><ul>" + caveats + "</ul>",
        "<p>Personalization source: " + esc(context?.facets?.[0]?.source ?? "NONE") + "</p>",
        '<p data-testid="chatman-equation">' + esc(trace?.equation ?? "") + "</p>",
        "<p>O*: " + esc((trace?.oStarRefs ?? []).join(", ")) + "</p>",
        "<p>Receipt: " + esc((trace?.receiptRefs ?? []).join(", ")) + "</p></section>",
        '<section data-testid="journey"><h2>You</h2><ol>' + journey + "</ol></section>",
        '<section data-testid="commitment"><h2>ZOE</h2>',
        "<p>" + esc(commitment?.consequenceSummary ?? "") + "</p>",
        "<p>Next handoff: " + esc(commitment?.nextHandoff ?? "") + "</p>",
        '<button data-demo-action="construct-brce-intent">Confirm intent</button>',
        '<output data-testid="brce-status">Not constructed</output></section>',
        "</main>",
      ].join("");
    }

    function escapeHtml(value) {
      return String(value)
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#039;");
    }
    """
  end
end
