// @generated by AshSurface.Projectors.JS (CalVer 26.10.1); prefix "ash_surface_client"
// Do not edit directly; change the admitted IR sources, then re-project.
// Law: pi_JS(IR) = JavaScript + JSDoc + Zod. TypeScript-free, no build step.
// DO-boundary actions project dispatch-INTENT descriptors only: an intent
// is data and carries no execution authority; this artifact contains no
// invoke/dispatch execution path.

import { z } from "zod";

/**
 * A dispatch intent for a DO-boundary action. DATA ONLY: minting an
 * intent never executes the action. Execution requires a separately
 * admitted, brokered, receipt-bearing dispatch path.
 * @typedef {Object} DispatchIntent
 * @property {"DISPATCH_INTENT"} kind
 * @property {string} actionId
 * @property {Record<string, unknown>} input - boundary-validated by the action Zod schema when present
 */

/**
 * JSDoc-typed namespace for resource `Todo` (1 action: list).
 * @typedef {Object} TodoNamespace
 * @property {Object} list - `Todo.list` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 */
export const Todo = Object.freeze({
  /** `Todo.list` — not delegated; no dispatch intent. */
  list: Object.freeze({
    id: "Todo.list",
    resource: "Todo",
    action: "list",
    actionType: "action",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: "啹󦖵򁲚",
    schema: null
  })
});

/**
 * JSDoc-typed namespace for resource `Todo_create_schema` (1 action: create).
 * @typedef {Object} Todo_create_schemaNamespace
 * @property {Object} create - `Todo_create_schema.create` (authorityBoundary: not delegated, descriptorKind: "DESCRIPTOR")
 */
export const Todo_create_schema = Object.freeze({
  /** `Todo_create_schema.create` — not delegated; no dispatch intent. */
  create: Object.freeze({
    id: "Todo_create_schema.create",
    resource: "Todo_create_schema",
    action: "create",
    actionType: "action",
    authorityBoundary: null,
    receiptRequired: false,
    descriptorKind: "DESCRIPTOR",
    capabilityIri: null,
    label: null,
    schema: null
  })
});

/**
 * Every action descriptor, sorted by id. DO-boundary descriptors carry
 * descriptorKind "DISPATCH_INTENT"; every other descriptor is a plain
 * "DESCRIPTOR". Members are the namespace objects themselves, so
 * descriptor identity is shared.
 */
export const ACTIONS = Object.freeze([
  Todo.list,
  Todo_create_schema.create
]);

/** Zod boundary schemas by action id, present only where the IR delegated one. */
export const SCHEMAS = Object.freeze({

});

/** Resource namespaces, sorted by resource name. */
export const NAMESPACES = Object.freeze({
  Todo,
  Todo_create_schema
});

/** Descriptor lookup by action id; null when unknown. */
export function getAction(id) {
  return ACTIONS.find((a) => a.id === id) ?? null;
}

/**
 * Mints a dispatch INTENT for a DO-boundary action. Refused for unknown
 * actions and for any action whose delegated boundary is not exactly
 * "DO". Input is boundary-validated by the action's Zod schema when the
 * IR delegated one. Never executes anything.
 * @param {string} id
 * @param {Record<string, unknown>} input
 * @returns {DispatchIntent}
 */
export function dispatchIntent(id, input) {
  const action = getAction(id);
  if (action === null) {
    throw new Error("REFUSED_UNKNOWN_ACTION: " + id);
  }
  if (action.descriptorKind !== "DISPATCH_INTENT") {
    throw new Error("REFUSED_NOT_DO_BOUNDARY: " + id + " has descriptorKind " + action.descriptorKind);
  }
  const parsed = action.schema ? action.schema.parse(input) : input;
  return Object.freeze({ kind: "DISPATCH_INTENT", actionId: id, input: parsed });
}
